--- 
title: "Clinical Trials 4H - lecture notes"
author: "Rachel Oughton"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
geometry: margin=3cm
output: 
  bookdown::pdf_document2:
    highlight: tango
    classoption:
      - onecolumn
      - portrait
    extra_dependencies: 
      hyperref: ["breaklinks=true"]
    latex_engine: pdflatex
    toc: true
    keep_tex: yes
    citation_package: natbib
    df_print: kable
documentclass: book
classoption: openany
bibliography: [ct4h.bib]
biblio-style: apalike
always_allow_html: true
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "These notes mirror what we'll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)."
---

```{r setup, include = F}
knitr::opts_chunk$set(echo=FALSE, message = FALSE, warning = FALSE)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
# This line sometimes needs commenting out to first generate the html file
options(knitr.table.format = function() {
  if (knitr::is_latex_output())
    "latex" else "pipe"
 })
```

```{r, echo=F}
library(medicaldata)
library(ggplot2)
library(gridExtra)
library(knitr)
library(kableExtra)
library(magick)
library(htmlTable)
library(magrittr)
library(rstatix)
library(mvtnorm)
library(pROC)
```


# Introduction

This is just here to preserve the numbering!




