# Working with binary data

So far all everything we've covered has related to continuous outcome variables, which we assumed to be normally distributed. This allowed us to use familiar techniques such as the $t$-test, and to take baseline information into account in an accessible way (the linear model / ANCOVA). However, very often clinical trials do not have a continuous, normally distributed output, and in the next two sections we will look at two other common possibilities: binary data (this section) and survival data (next section).

The primary outcome of a trial will often be in the realm of 'success' or 'fail'. Did the participant's symptoms clear up? Did the participant survive? Was the baby born at full term? and so on. We've already covered sample size estimation in Section \@ref(ss-bin), where we set up the following binomial model.

For a group $n$ of participants, we will have allocated $n_C$ to the control group (group $C$), and $n_T$ to the treatment group (group $T$). The natural statistical model to apply to this situation is therefore a binomial distribution, for example in group $C$ the number of 'successes' would be modelled by

$$R_C \sim \operatorname{Bi}\left(n_C,\,\pi_C\right).$$

Similarly the number of successes in the treatment group can be modelled as 
$$R_T \sim\operatorname{Bi}\left(n_T,\,\pi_T\right),$$
and the focus of our analysis is on comparing $\pi_C$ and $\pi_T$. To do this we will require point estimates of both quantities and interval estimates for some measure of the discrepancy between them. We will also need ways to test the null hypothesis that $\pi_C = \pi_T.$

## Point estimates and Hypothesis tests

First of all, we can tabulate the results of a trial with a binary outcome like this: 

                   Successes   Failures    Total     
-----------------  ----------  ---------   --------------
    **Treatment**  $r_T$       $n_T-r_T$   $n_T$     
      **Control**  $r_C$       $n_C-r_C$   $n_C$     
        **Total**  $r$         $n - r$     $n$       

Note that because this is a table of observed values, they are now all in lower case.

We can estimate $\pi_C$ and $\pi_T$ by the sample proportions

$$
\begin{aligned}
p_C &= \frac{r_C}{n_C}\\
p_T &= \frac{r_T}{n_T}
\end{aligned}.
$$

We know from the properties of the binomial distribtion that $\operatorname{E}\left(p_C\right) = \pi_C$ and 
$$\operatorname{Var}\left(p_C\right) = \frac{\pi_C\left(1-\pi_C\right)}{n_C},$$
and similarly for $\operatorname{E}\left(p_T\right)$ and $\operatorname{Var}\left(p_T\right)$.

If we think in terms of individual participants, we have the variable $y_{iC}$ for the outcome of the $i$-th patient in group $C$, with $y_{iC}=1$ if the participant's outcome is 'success' and $y_{iC}=0$ otherwise. Then we have 

$$r_C = \sum\limits_{i=1}^{n_C} y_{iC},$$
and similarly for group $T$. Since $p_C$ and $p_T$ are therefore sample means, we can apply the Central Limit Theorem to conclude that $p_C$ and $p_P$ can be approximated by normal distributions:

$$
\begin{aligned}
p_C & \sim N\left(\pi_C,\, \frac{\pi_C\left(1-\pi_c\right)}{n_C}\right)\\
p_T & \sim N\left(\pi_T,\, \frac{\pi_T\left(1-\pi_T\right)}{n_T}\right).
\end{aligned}
$$

This means we can test the null hypothesis that $\pi_C = \pi_T$ by referring our observed value of $p_T - p_C$ to a normal distribution with mean 0 and variance

$$ \frac{\pi_T\left(1-\pi_T\right)}{n_T} + \frac{\pi_C\left(1-\pi_c\right)}{n_C},$$

which we can approximate by substituting in $p_C$ and $p_T$.

However, since under the null hypothesis $\pi_C = \pi_T = \pi$, it would be more appropriate to use this as the common variance. In this case, the variance of $p_T - p_C$ becomes

$$\pi\left(1-\pi\right)\left(\frac{1}{n_C} + \frac{1}{n_T}\right), $$
and in calculations we replace $\pi$ with $p = r/n$.

Putting all this together, our test statistic is 

$$Z = \frac{p_T - p_C}{\sqrt{p\left(1-p\right)\left(\frac{1}{n_T} + \frac{1}{n_C}\right)}}.$$

::: {.example}

The data in this example comes from @terbinafine, in which two new oral antifungal medicines were compared in terms of their effectiveness at treating toenail infections, with 107 participants. The two treatments are terbinafine and itraconazole 


```{r}

# Maybe this is more complicated than I imagined!
data(strep_tb)

table(strep_tb[,c(2,13)])

```

We therefore have

$$
\begin{aligned}
p_C & = \frac{17}{17+35} & = 0.327\\
p_T & = \frac{38}{38+17} & = 0.691\\
p & = \frac{38+17}{107} &= 0.514. 
\end{aligned}
$$


:::