<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>B Computer Practical 2 | Clinical Trials 4H</title>
  <meta name="description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="B Computer Practical 2 | Clinical Trials 4H" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="B Computer Practical 2 | Clinical Trials 4H" />
  
  <meta name="twitter:description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  

<meta name="author" content="Rachel Oughton" />


<meta name="date" content="2024-02-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="computer-practical-1.html"/>
<link rel="next" href="references.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Clinical Trials 4H!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#practical-details"><i class="fa fa-check"></i>Practical details</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#lectures"><i class="fa fa-check"></i>Lectures</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#computer-classes"><i class="fa fa-check"></i>Computer classes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#office-hour"><i class="fa fa-check"></i>Office Hour</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i>Assessment</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#books"><i class="fa fa-check"></i>Books</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-to-expect-from-this-module"><i class="fa fa-check"></i>What to expect from this module</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-i-expect-from-you"><i class="fa fa-check"></i>What I expect from you</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="rct-intro.html"><a href="rct-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction to Clinical Trials</a>
<ul>
<li class="chapter" data-level="1.1" data-path="rct-intro.html"><a href="rct-intro.html#causal-inference-and-clinical-trials"><i class="fa fa-check"></i><b>1.1</b> Causal inference and clinical trials</a></li>
<li class="chapter" data-level="1.2" data-path="rct-intro.html"><a href="rct-intro.html#the-structure-of-a-clinical-trial"><i class="fa fa-check"></i><b>1.2</b> The structure of a clinical trial</a>
<ul>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#the-population-of-eligible-patients"><i class="fa fa-check"></i>The population of eligible patients</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#entry-to-the-trial"><i class="fa fa-check"></i>Entry to the trial</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#allocation-to-groups"><i class="fa fa-check"></i>Allocation to groups</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#comparing-results"><i class="fa fa-check"></i>Comparing results</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#why-bother-with-a-control-group"><i class="fa fa-check"></i>Why bother with a control group?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="rct-intro.html"><a href="rct-intro.html#primout"><i class="fa fa-check"></i><b>1.3</b> The primary outcome</a></li>
<li class="chapter" data-level="1.4" data-path="rct-intro.html"><a href="rct-intro.html#ethical-issues"><i class="fa fa-check"></i><b>1.4</b> Ethical issues</a></li>
<li class="chapter" data-level="1.5" data-path="rct-intro.html"><a href="rct-intro.html#phases-of-clinical-trials"><i class="fa fa-check"></i><b>1.5</b> Phases of clinical trials</a>
<ul>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-zero"><i class="fa fa-check"></i>Phase zero</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-one"><i class="fa fa-check"></i>Phase one</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-two"><i class="fa fa-check"></i>Phase two</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-three"><i class="fa fa-check"></i>Phase three</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-four"><i class="fa fa-check"></i>Phase four</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Part I: Continuous outcome variables</b></span></li>
<li class="chapter" data-level="2" data-path="rct-plan.html"><a href="rct-plan.html"><i class="fa fa-check"></i><b>2</b> Sample size for a normally distributed primary outcome variable</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rct-plan.html"><a href="rct-plan.html#the-treatment-effect"><i class="fa fa-check"></i><b>2.1</b> The treatment effect</a></li>
<li class="chapter" data-level="2.2" data-path="rct-plan.html"><a href="rct-plan.html#reminder-hypothesis-tests-with-a-focus-on-rcts"><i class="fa fa-check"></i><b>2.2</b> Reminder: hypothesis tests (with a focus on RCTs)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="rct-plan.html"><a href="rct-plan.html#insignificant-results"><i class="fa fa-check"></i><b>2.2.1</b> Insignificant results</a></li>
<li class="chapter" data-level="2.2.2" data-path="rct-plan.html"><a href="rct-plan.html#one-tailed-or-two-tailed"><i class="fa fa-check"></i><b>2.2.2</b> One-tailed or two-tailed?</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="rct-plan.html"><a href="rct-plan.html#sec-measDcont"><i class="fa fa-check"></i><b>2.3</b> Constructing a measure of effect size</a></li>
<li class="chapter" data-level="2.4" data-path="rct-plan.html"><a href="rct-plan.html#sec-power"><i class="fa fa-check"></i><b>2.4</b> Power: If <span class="math inline">\(H_0\)</span> is false</a></li>
<li class="chapter" data-level="2.5" data-path="rct-plan.html"><a href="rct-plan.html#sec-ssformulacont"><i class="fa fa-check"></i><b>2.5</b> A sample size formula</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="alloc.html"><a href="alloc.html"><i class="fa fa-check"></i><b>3</b> Allocation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="alloc.html"><a href="alloc.html#bias"><i class="fa fa-check"></i><b>3.1</b> Bias</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="alloc.html"><a href="alloc.html#where-does-bias-come-from"><i class="fa fa-check"></i><b>3.1.1</b> Where does bias come from?</a></li>
<li class="chapter" data-level="3.1.2" data-path="alloc.html"><a href="alloc.html#implications-for-allocation"><i class="fa fa-check"></i><b>3.1.2</b> Implications for allocation</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="alloc.html"><a href="alloc.html#sec-allocation"><i class="fa fa-check"></i><b>3.2</b> Allocation methods</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="alloc.html"><a href="alloc.html#simple-random-allocation"><i class="fa fa-check"></i><b>3.2.1</b> Simple random allocation</a></li>
<li class="chapter" data-level="3.2.2" data-path="alloc.html"><a href="alloc.html#random-permuted-blocks"><i class="fa fa-check"></i><b>3.2.2</b> Random permuted blocks</a></li>
<li class="chapter" data-level="3.2.3" data-path="alloc.html"><a href="alloc.html#bcurn"><i class="fa fa-check"></i><b>3.2.3</b> Biased coin designs and urn schemes</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="alloc.html"><a href="alloc.html#incorporating-baseline-measurements"><i class="fa fa-check"></i><b>3.3</b> Incorporating baseline measurements</a></li>
<li class="chapter" data-level="3.4" data-path="alloc.html"><a href="alloc.html#stratified-sampling"><i class="fa fa-check"></i><b>3.4</b> Stratified sampling</a></li>
<li class="chapter" data-level="3.5" data-path="alloc.html"><a href="alloc.html#minimization"><i class="fa fa-check"></i><b>3.5</b> Minimization</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="alloc.html"><a href="alloc.html#minimization-algorithm"><i class="fa fa-check"></i><b>3.5.1</b> Minimization algorithm</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="alloc.html"><a href="alloc.html#problems-around-allocation"><i class="fa fa-check"></i><b>3.6</b> Problems around allocation</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rct-analysis.html"><a href="rct-analysis.html"><i class="fa fa-check"></i><b>4</b> Analyzing RCT data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="rct-analysis.html"><a href="rct-analysis.html#ttest"><i class="fa fa-check"></i><b>4.1</b> Confidence intervals and P-values</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="rct-analysis.html"><a href="rct-analysis.html#what-do-we-do-with-this-outcome"><i class="fa fa-check"></i><b>4.1.1</b> What do we do with this outcome?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="rct-analysis.html"><a href="rct-analysis.html#baseline"><i class="fa fa-check"></i><b>4.2</b> Using baseline values</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="rct-analysis.html"><a href="rct-analysis.html#a-dodgy-way-to-use-baseline-variables"><i class="fa fa-check"></i><b>4.2.1</b> A dodgy way to use baseline variables</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="rct-analysis.html"><a href="rct-analysis.html#analysis-of-covariance-ancova"><i class="fa fa-check"></i><b>4.3</b> Analysis of covariance (ANCOVA)</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="rct-analysis.html"><a href="rct-analysis.html#ancovatheory"><i class="fa fa-check"></i><b>4.3.1</b> The theory</a></li>
<li class="chapter" data-level="4.3.2" data-path="rct-analysis.html"><a href="rct-analysis.html#ancova-practice"><i class="fa fa-check"></i><b>4.3.2</b> The practice</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="rct-analysis.html"><a href="rct-analysis.html#some-follow-up-questions."><i class="fa fa-check"></i><b>4.4</b> Some follow-up questions….</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="rct-analysis.html"><a href="rct-analysis.html#didnt-we-say-that-x_t---x_c-was-an-unbiased-estimator-of-tau"><i class="fa fa-check"></i><b>4.4.1</b> Didn’t we say that <span class="math inline">\(X_T - X_C\)</span> was an unbiased estimator of <span class="math inline">\(\tau\)</span>?</a></li>
<li class="chapter" data-level="4.4.2" data-path="rct-analysis.html"><a href="rct-analysis.html#what-if-the-lines-shouldnt-be-parallel-the-unequal-slopes-model"><i class="fa fa-check"></i><b>4.4.2</b> What if the lines shouldn’t be parallel? The unequal slopes model</a></li>
<li class="chapter" data-level="4.4.3" data-path="rct-analysis.html"><a href="rct-analysis.html#can-we-include-any-other-baseline-covariates"><i class="fa fa-check"></i><b>4.4.3</b> Can we include any other baseline covariates?</a></li>
<li class="chapter" data-level="" data-path="rct-analysis.html"><a href="rct-analysis.html#an-important-caution"><i class="fa fa-check"></i>An important caution!</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Part II: Binary outcome variable</b></span></li>
<li class="chapter" data-level="5" data-path="ss-bin.html"><a href="ss-bin.html"><i class="fa fa-check"></i><b>5</b> Sample size for a binary variable</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ss-bin.html"><a href="ss-bin.html#delta-method"><i class="fa fa-check"></i><b>5.1</b> The Delta Method</a></li>
<li class="chapter" data-level="5.2" data-path="ss-bin.html"><a href="ss-bin.html#a-sample-size-formula"><i class="fa fa-check"></i><b>5.2</b> A sample size formula</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html"><i class="fa fa-check"></i><b>6</b> Analysis for binary outcomes</a>
<ul>
<li class="chapter" data-level="6.1" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#point-estimates-and-hypothesis-tests"><i class="fa fa-check"></i><b>6.1</b> Point estimates and Hypothesis tests</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#an-alternative-approach-chi-squared"><i class="fa fa-check"></i><b>6.1.1</b> An alternative approach: chi-squared</a></li>
<li class="chapter" data-level="6.1.2" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#likelihood-a-more-rigorous-way"><i class="fa fa-check"></i><b>6.1.2</b> Likelihood: A more rigorous way</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#measures-of-difference-for-binary-data"><i class="fa fa-check"></i><b>6.2</b> Measures of difference for binary data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#ard-and-nnt"><i class="fa fa-check"></i><b>6.2.1</b> Absolute risk difference and Number Needed to Treat</a></li>
<li class="chapter" data-level="6.2.2" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#risk-ratio-rr-and-odds-ratio-or"><i class="fa fa-check"></i><b>6.2.2</b> Risk Ratio (RR) and Odds ratio (OR)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#accounting-for-baseline-observations-logistic-regression"><i class="fa fa-check"></i><b>6.3</b> Accounting for baseline observations: logistic regression</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#what-does-this-model-tell-us"><i class="fa fa-check"></i><b>6.3.1</b> What does this model tell us?</a></li>
<li class="chapter" data-level="6.3.2" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#fitting-a-logistic-regression-model"><i class="fa fa-check"></i><b>6.3.2</b> Fitting a logistic regression model</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#diagnostics-for-logistic-regression"><i class="fa fa-check"></i><b>6.4</b> Diagnostics for logistic regression</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#discrimination"><i class="fa fa-check"></i><b>6.4.1</b> Discrimination</a></li>
<li class="chapter" data-level="6.4.2" data-path="analysis-for-binary-outcomes.html"><a href="analysis-for-binary-outcomes.html#calibration"><i class="fa fa-check"></i><b>6.4.2</b> Calibration</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Part III: Survival data</b></span></li>
<li class="chapter" data-level="7" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html"><i class="fa fa-check"></i><b>7</b> Working with time-to-event data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#censored-times"><i class="fa fa-check"></i><b>7.1</b> Censored times</a></li>
<li class="chapter" data-level="7.2" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#survhaz"><i class="fa fa-check"></i><b>7.2</b> The Survival Curve and the Hazard function</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#the-kaplan-meier-estimator"><i class="fa fa-check"></i><b>7.2.1</b> The Kaplan-Meier estimator</a></li>
<li class="chapter" data-level="7.2.2" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#a-parametric-approach"><i class="fa fa-check"></i><b>7.2.2</b> A parametric approach</a></li>
<li class="chapter" data-level="7.2.3" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#the-weibull-distribution"><i class="fa fa-check"></i><b>7.2.3</b> The Weibull distribution</a></li>
<li class="chapter" data-level="" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#aside-sample-size-calculations-for-time-to-event-data"><i class="fa fa-check"></i>Aside: Sample size calculations for time-to-event data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html"><i class="fa fa-check"></i><b>8</b> Comparing survival curves</a>
<ul>
<li class="chapter" data-level="8.1" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#survlrtest"><i class="fa fa-check"></i><b>8.1</b> Parametric: likelihood ratio test</a></li>
<li class="chapter" data-level="8.2" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#non-parametric-the-log-rank-test"><i class="fa fa-check"></i><b>8.2</b> Non-parametric: the log-rank test</a></li>
<li class="chapter" data-level="8.3" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#semi-parametric-the-proportional-hazards-model"><i class="fa fa-check"></i><b>8.3</b> Semi-parametric: the proportional hazards model</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#general-proportional-hazards-model"><i class="fa fa-check"></i><b>8.3.1</b> General proportional hazards model</a></li>
<li class="chapter" data-level="8.3.2" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#cox-regression"><i class="fa fa-check"></i><b>8.3.2</b> Cox regression</a></li>
<li class="chapter" data-level="" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#how-can-we-tell-if-a-proportional-hazards-model-is-appropriate"><i class="fa fa-check"></i>How can we tell if a proportional hazards model is appropriate?</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Part III: Further designs</b></span></li>
<li class="chapter" data-level="9" data-path="cluster-rct.html"><a href="cluster-rct.html"><i class="fa fa-check"></i><b>9</b> Cluster randomised trials</a>
<ul>
<li class="chapter" data-level="9.1" data-path="cluster-rct.html"><a href="cluster-rct.html#what-is-a-cluster-rct"><i class="fa fa-check"></i><b>9.1</b> What is a cluster RCT?</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="cluster-rct.html"><a href="cluster-rct.html#intracluster-correlation"><i class="fa fa-check"></i><b>9.1.1</b> Intracluster correlation</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="cluster-rct.html"><a href="cluster-rct.html#sample-size"><i class="fa fa-check"></i><b>9.2</b> Sample size</a></li>
<li class="chapter" data-level="9.3" data-path="cluster-rct.html"><a href="cluster-rct.html#allocation"><i class="fa fa-check"></i><b>9.3</b> Allocation</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="cluster-rct.html"><a href="cluster-rct.html#allocating-everyone-at-once"><i class="fa fa-check"></i><b>9.3.1</b> Allocating everyone at once</a></li>
<li class="chapter" data-level="9.3.2" data-path="cluster-rct.html"><a href="cluster-rct.html#covariate-constrained-randomization"><i class="fa fa-check"></i><b>9.3.2</b> Covariate constrained randomization</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="cluster-rct.html"><a href="cluster-rct.html#analysing-a-cluster-rct"><i class="fa fa-check"></i><b>9.4</b> Analysing a cluster RCT</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="cluster-rct.html"><a href="cluster-rct.html#at-the-cluster-level"><i class="fa fa-check"></i><b>9.4.1</b> At the cluster level</a></li>
<li class="chapter" data-level="9.4.2" data-path="cluster-rct.html"><a href="cluster-rct.html#at-the-individual-level-random-effects-models"><i class="fa fa-check"></i><b>9.4.2</b> At the individual level: Random effects models</a></li>
<li class="chapter" data-level="9.4.3" data-path="cluster-rct.html"><a href="cluster-rct.html#analysing-for-effect-modification---random-effects-model"><i class="fa fa-check"></i><b>9.4.3</b> Analysing for effect modification - Random effects model</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Computer practicals</b></span></li>
<li class="chapter" data-level="A" data-path="computer-practical-1.html"><a href="computer-practical-1.html"><i class="fa fa-check"></i><b>A</b> Computer Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="computer-practical-1.html"><a href="computer-practical-1.html#health-warning"><i class="fa fa-check"></i>Health warning!</a>
<ul>
<li class="chapter" data-level="" data-path="computer-practical-1.html"><a href="computer-practical-1.html#preliminaries"><i class="fa fa-check"></i>Preliminaries</a></li>
<li class="chapter" data-level="" data-path="computer-practical-1.html"><a href="computer-practical-1.html#r-practicalities"><i class="fa fa-check"></i>R practicalities</a></li>
</ul></li>
<li class="chapter" data-level="A.1" data-path="computer-practical-1.html"><a href="computer-practical-1.html#cp1allocation"><i class="fa fa-check"></i><b>A.1</b> Allocation</a>
<ul>
<li class="chapter" data-level="A.1.1" data-path="computer-practical-1.html"><a href="computer-practical-1.html#licorice-gargle-dataset"><i class="fa fa-check"></i><b>A.1.1</b> Licorice gargle dataset</a></li>
<li class="chapter" data-level="A.1.2" data-path="computer-practical-1.html"><a href="computer-practical-1.html#allocmethods"><i class="fa fa-check"></i><b>A.1.2</b> Allocation methods</a></li>
<li class="chapter" data-level="A.1.3" data-path="computer-practical-1.html"><a href="computer-practical-1.html#stratifying-the-dataset"><i class="fa fa-check"></i><b>A.1.3</b> Stratifying the dataset</a></li>
<li class="chapter" data-level="A.1.4" data-path="computer-practical-1.html"><a href="computer-practical-1.html#minimisation"><i class="fa fa-check"></i><b>A.1.4</b> Minimisation</a></li>
<li class="chapter" data-level="A.1.5" data-path="computer-practical-1.html"><a href="computer-practical-1.html#a-simulation-experiment"><i class="fa fa-check"></i><b>A.1.5</b> A simulation experiment!</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="computer-practical-1.html"><a href="computer-practical-1.html#cp1analysis"><i class="fa fa-check"></i><b>A.2</b> Analysis</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="computer-practical-1.html"><a href="computer-practical-1.html#polyps-data"><i class="fa fa-check"></i><b>A.2.1</b> Polyps data</a></li>
<li class="chapter" data-level="A.2.2" data-path="computer-practical-1.html"><a href="computer-practical-1.html#treatment-for-maternal-periodontal-disease"><i class="fa fa-check"></i><b>A.2.2</b> Treatment for maternal periodontal disease</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="computer-practical-2.html"><a href="computer-practical-2.html"><i class="fa fa-check"></i><b>B</b> Computer Practical 2</a>
<ul>
<li class="chapter" data-level="B.1" data-path="computer-practical-2.html"><a href="computer-practical-2.html#cp2sim"><i class="fa fa-check"></i><b>B.1</b> Sample size by simulation (part I)</a>
<ul>
<li class="chapter" data-level="B.1.1" data-path="computer-practical-2.html"><a href="computer-practical-2.html#the-simulation-method"><i class="fa fa-check"></i><b>B.1.1</b> The simulation method</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="computer-practical-2.html"><a href="computer-practical-2.html#analysis-for-binary-and-survival-data"><i class="fa fa-check"></i><b>B.2</b> Analysis for Binary and Survival data</a>
<ul>
<li class="chapter" data-level="B.2.1" data-path="computer-practical-2.html"><a href="computer-practical-2.html#binary-data"><i class="fa fa-check"></i><b>B.2.1</b> Binary data</a></li>
<li class="chapter" data-level="B.2.2" data-path="computer-practical-2.html"><a href="computer-practical-2.html#survival-data"><i class="fa fa-check"></i><b>B.2.2</b> Survival data</a></li>
<li class="chapter" data-level="B.2.3" data-path="computer-practical-2.html"><a href="computer-practical-2.html#fitting-a-survival-curve"><i class="fa fa-check"></i><b>B.2.3</b> Fitting a survival curve</a></li>
<li class="chapter" data-level="B.2.4" data-path="computer-practical-2.html"><a href="computer-practical-2.html#comparing-survival-curves-likelihood-ratio-test"><i class="fa fa-check"></i><b>B.2.4</b> Comparing survival curves: likelihood ratio test</a></li>
<li class="chapter" data-level="B.2.5" data-path="computer-practical-2.html"><a href="computer-practical-2.html#comparing-survival-curves-1"><i class="fa fa-check"></i><b>B.2.5</b> Comparing survival curves</a></li>
</ul></li>
<li class="chapter" data-level="B.3" data-path="computer-practical-2.html"><a href="computer-practical-2.html#cp2sim2"><i class="fa fa-check"></i><b>B.3</b> Sample size by simulation (part II)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Clinical Trials 4H</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="computer-practical-2" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">B</span> Computer Practical 2<a href="computer-practical-2.html#computer-practical-2" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this practical, we will focus on two main areas:</p>
<ul>
<li>Simulation methods for power analysis/determining sample size</li>
<li>Analysis methods for Binary and Survival data</li>
</ul>
<p>We’ll start with simulation for sample size, and apply that to a continuous outcome trial. We’ll then look at some analysis methods for binary and survival outcome data. Finally, we’ll use the the simulation method for sample size calculation for a survival outcome trial (more fitting, since we wimped out of tackling that problem in lectures!).</p>
<details>
<summary>
<strong>R practicalities - click here</strong>
</summary>
<p>There are many, many packages in R that implement methods for designing and analysing clinical trials (see a list at <a href="https://cran.r-project.org/web/views/ClinicalTrials.html">CRAN task view</a>). We will look at some of these, and will also write our own code for some tasks. Remember that to install a package, you can do</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="computer-practical-2.html#cb197-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;&lt;packagename&gt;&quot;</span>)</span></code></pre></div>
<p>If you have problems running R on your laptop, or on the university machines, the most foolproof way might be to use Github codespaces (thanks to Louis Aslett, who developed this for Data Science and Statistical Computing II). You may be familiar with this approach if you did Bayesian Computational Modelling III.</p>
<p>An advantage of this is that you can open the same codespace (the same instance of R) from any computer, so if you plan to work on things (for example your summative assignment, which will involve some R) from more than one computer, this might be ideal.</p>
<p>This requires you to have a github account (you can sign up for free <a href="https://github.com/">here</a>) and there is a short guide to creating a github account <a href="https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.louisaslett.com%2FCourses%2FDSSC%2Fnotes%2Fgithub.html&amp;data=05%7C02%7Cr.h.oughton%40durham.ac.uk%7Ccd09b90284364f8558ba08dc1ccf06f8%7C7250d88b4b684529be44d59a2d8a6f94%7C0%7C0%7C638416922691502641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=f5gJFI3CJPOQ1P16l%2FIdhtIAgQul7s5BhIPwi4GAyLk%3D&amp;reserved=0">here</a>.</p>
<p><a href="https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcodespaces.new%2Flouisaslett%2Fdssc%3Fquickstart%3D1&amp;data=05%7C02%7Cr.h.oughton%40durham.ac.uk%7Ccd09b90284364f8558ba08dc1ccf06f8%7C7250d88b4b684529be44d59a2d8a6f94%7C0%7C0%7C638416922691485947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=Lsw6mz0L5G%2FvZoZN29D2FgOyOkPMNboJgXPJt7BMPk8%3D&amp;reserved=0">Direct link to codespace</a></p>
<p><a href="https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.louisaslett.com%2FCourses%2FDSSC%2Fnotes%2Finstallr.html%23codespaces&amp;data=05%7C02%7Cr.h.oughton%40durham.ac.uk%7Ccd09b90284364f8558ba08dc1ccf06f8%7C7250d88b4b684529be44d59a2d8a6f94%7C0%7C0%7C638416922691495230%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=hNtp7fT0qZWiQXRwEOUXbMvPWxy1jMtsCd9J7nXlAug%3D&amp;reserved=0">Instructions for how to use codespace</a></p>
</details>
<div id="cp2sim" class="section level2 hasAnchor" number="11.1">
<h2><span class="header-section-number">B.1</span> Sample size by simulation (part I)<a href="computer-practical-2.html#cp2sim" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’ll make use of several packages in this section. Installing them all now should hopefully prevent it from disrupting your flow! We’ll load them as we go along.</p>
<p><strong>Notice that where there are code snippets like this one that you want to copy directly, you can hover your cursor in the top right of the code box and a ‘copy’ icon will appear.</strong></p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="computer-practical-2.html#cb198-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>())</span></code></pre></div>
<p>A method for sample size calculation that has become increasingly popular in recent years is to use simulation. In simple terms, we write code that runs the trial many, many times in order to determine how many participants we need to achieve the power required. We can estimate the power by the proportion of simulated trials in which the null hypothesis was rejected.</p>
<p>Because the code necessarily works by fixing the number of participants and investigating the effect on the power of the trial, this is often referred to as <em>power-calculation</em>, but it is the same sample size issue, approached from a different angle. <span class="citation">Arnold et al. (<a href="#ref-arnold2011simulation">2011</a>)</span> gives a thorough, readable and interesting case study of the use of power simulation in a cluster randomised trial investigating different sanitation-related interventions in rural communities in Bangladesh.</p>
<p>This approach has the following advantages over the formula-based methods presented in Section <a href="rct-plan.html#rct-plan">2</a>:</p>
<ol style="list-style-type: decimal">
<li><strong>Transparency</strong>: If the data generating mechanism is made clear, then the assumptions behind the trial are also clear, and the simulation can be replicated by anyone. Reproducibility is a big issue in clinical trials.</li>
<li><strong>Flexibility</strong>: Whereas the methods in Section <a href="rct-plan.html#rct-plan">2</a> are limited to very specific circumstances, one can simulate arbitrarily complex or unusual trials.</li>
<li><strong>Practice</strong>: This process requires us to perform our planned analysis at the planning stage, thus raising any potential issues early enough to adapt the statistical analysis plan.</li>
</ol>
<p>Arguably the first and third advantages could also be true (though aren’t automatically) of a well-planned trial that used conventional sample size formulae, but the second is an advantage unique to simulation.</p>
<div id="the-simulation-method" class="section level3 hasAnchor" number="11.1.1">
<h3><span class="header-section-number">B.1.1</span> The simulation method<a href="computer-practical-2.html#the-simulation-method" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Note: really we should be using more than 100 simulations, but so that the code runs in a sensible amount of time I’ve reduced the number. Feel free to increase it if you want to, but you’ll have to wait a little while for it to run.</strong></p>
<p>A power simulation starts by specifying the form of the model that will be used to analyse the data. We’ll start by assuming a continuous random variable as output, as we did in Section <a href="rct-plan.html#rct-plan">2</a>.</p>
<div id="power-simulation-for-a-t-test" class="section level4 hasAnchor" number="11.1.1.1">
<h4><span class="header-section-number">B.1.1.1</span> Power simulation for a t-test<a href="computer-practical-2.html#power-simulation-for-a-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We’ll start by taking a simulation approach to recreate the most ‘vanilla’ scenario, where we have a continuous outcome <span class="math inline">\(Y\)</span> and wish to conduct a <span class="math inline">\(t\)</span>-test on the outcome.</p>
<p>Recall that the sample size formula we found was Equation <a href="rct-plan.html#eq:sscont">(2.4)</a>, shown again below:</p>
<p><span class="math display">\[N = \frac{2\sigma^2\left(z_\beta + z_{\frac{\alpha}{2}}\right)^2}{\tau_M^2},\]</span>
where <span class="math inline">\(N\)</span> is the number of participants required in each trial arm, <span class="math inline">\(\sigma^2\)</span> is the variance of the outcome <span class="math inline">\(Y\)</span> in each group, and <span class="math inline">\(\tau_M\)</span> is the minimum detectable effect size (or minimum clinically important difference), the smallest difference between <span class="math inline">\(\mu_C\)</span> and <span class="math inline">\(\mu_T\)</span> (the treatment arm means) that we want to be able to detect with significance level <span class="math inline">\(\alpha\)</span> and power <span class="math inline">\(1-\beta\)</span>.</p>
<p>These variables give us all we need to simulate trial data. Essentially, the model we put forward is</p>
<p><span class="math display">\[
Y_i= \sim
\begin{cases}
N\left(\mu,\;\sigma^2\right)&amp;\;\text{ if participant }i\text{ is in group }C\\
N\left(\mu + \tau_M,\;\sigma^2\right)&amp;\;\text{ if participant }i\text{ is in group }T.
\end{cases}
\]</span></p>
<p>Therefore, to simulate data from a trial like this, we need to specify values for <span class="math inline">\(\mu,\;\tau_M\)</span> and <span class="math inline">\(\sigma^2\)</span>.</p>
<p>Then, the steps for each simulation will be</p>
<ol style="list-style-type: decimal">
<li>Simulate trial data</li>
<li>Conduct an un-paired, two-tailed <span class="math inline">\(t\)</span>-test on the data</li>
<li>Note whether <span class="math inline">\(H_0:\;\tau_M=0\)</span> is rejected</li>
</ol>
<p>Having done this for some number <span class="math inline">\(n_{sim}\)</span> of simulations, we return the proportion of simulations in which <span class="math inline">\(H_0\)</span> was rejected, and this is our power estimate.</p>
<p>If the power estimate is smaller than we would like, we increase the number of participants in our simulated trial data and try again. Conversely, we decrease the number of participants if the power estimate is larger than we need.</p>
<div class="exercise">
<p><span id="exr:ex1sim" class="exercise"><strong>Exercise B.1  </strong></span>By generating data for group <span class="math inline">\(C\)</span> and group <span class="math inline">\(T\)</span> according to the distributions above, conduct a power simulation for the trial scenario described in Example <a href="rct-plan.html#exm:sseg1">2.1</a>, with the aim of finding the number <span class="math inline">\(N\)</span> of participants required in each arm for a power of 0.9 (<span class="math inline">\(\beta=0.1\)</span>) and a confidence level of <span class="math inline">\(\alpha=0.05\)</span>. How consistent are your results? What issues does this raise around choosing a sample size?</p>
</div>
<details>
<summary>
Click to reveal solution
</summary>
<p>The sensible first thing to do is to write a function that does this for general <span class="math inline">\(n_{sim},\,N,\,\mu,\,\sigma^2\)</span> and <span class="math inline">\(\tau_M\)</span>. The very simplest way would be the following, where we generate <span class="math inline">\(N\)</span> participants per arm, and their data.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="computer-practical-2.html#cb199-1" tabindex="-1"></a>ttest_sim <span class="ot">=</span> <span class="cf">function</span>(</span>
<span id="cb199-2"><a href="computer-practical-2.html#cb199-2" tabindex="-1"></a>    nsim,  <span class="co"># the number of simulations to use</span></span>
<span id="cb199-3"><a href="computer-practical-2.html#cb199-3" tabindex="-1"></a>    N,     <span class="co"># number of participants per trial arm</span></span>
<span id="cb199-4"><a href="computer-practical-2.html#cb199-4" tabindex="-1"></a>    mu,    <span class="co"># mean outcome (for group C / under H0)</span></span>
<span id="cb199-5"><a href="computer-practical-2.html#cb199-5" tabindex="-1"></a>    tm,    <span class="co"># minimum detectable effect size</span></span>
<span id="cb199-6"><a href="computer-practical-2.html#cb199-6" tabindex="-1"></a>    sd     <span class="co"># sd of outcome</span></span>
<span id="cb199-7"><a href="computer-practical-2.html#cb199-7" tabindex="-1"></a>){</span>
<span id="cb199-8"><a href="computer-practical-2.html#cb199-8" tabindex="-1"></a>  H0_reject_vec <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, nsim) <span class="co"># to store 1 if H0 rejected, 0 if fail to reject H0</span></span>
<span id="cb199-9"><a href="computer-practical-2.html#cb199-9" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsim){</span>
<span id="cb199-10"><a href="computer-practical-2.html#cb199-10" tabindex="-1"></a>    out_groupC <span class="ot">=</span> <span class="fu">rnorm</span>(N, <span class="at">mean=</span>mu, <span class="at">sd=</span>sd)</span>
<span id="cb199-11"><a href="computer-practical-2.html#cb199-11" tabindex="-1"></a>    out_groupT <span class="ot">=</span> <span class="fu">rnorm</span>(N, <span class="at">mean=</span>mu <span class="sc">+</span> tm, <span class="at">sd=</span>sd)</span>
<span id="cb199-12"><a href="computer-practical-2.html#cb199-12" tabindex="-1"></a>    ttest <span class="ot">=</span> <span class="fu">t.test</span>(</span>
<span id="cb199-13"><a href="computer-practical-2.html#cb199-13" tabindex="-1"></a>      out_groupC, out_groupT, </span>
<span id="cb199-14"><a href="computer-practical-2.html#cb199-14" tabindex="-1"></a>      <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, </span>
<span id="cb199-15"><a href="computer-practical-2.html#cb199-15" tabindex="-1"></a>      <span class="at">var.equal =</span> T, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb199-16"><a href="computer-practical-2.html#cb199-16" tabindex="-1"></a>    H0_reject_vec[i] <span class="ot">=</span> <span class="fu">ifelse</span>(ttest<span class="sc">$</span>p.value<span class="sc">&lt;</span><span class="fl">0.05</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb199-17"><a href="computer-practical-2.html#cb199-17" tabindex="-1"></a>  }</span>
<span id="cb199-18"><a href="computer-practical-2.html#cb199-18" tabindex="-1"></a>  </span>
<span id="cb199-19"><a href="computer-practical-2.html#cb199-19" tabindex="-1"></a>  power.est <span class="ot">=</span> <span class="fu">mean</span>(H0_reject_vec)</span>
<span id="cb199-20"><a href="computer-practical-2.html#cb199-20" tabindex="-1"></a>  power.est</span>
<span id="cb199-21"><a href="computer-practical-2.html#cb199-21" tabindex="-1"></a>}</span></code></pre></div>
<p>For a sanity check, we can put in the number we got from the equation in Section <a href="rct-plan.html#rct-plan">2</a>. It is usual to need to specify a mean <span class="math inline">\(\mu\)</span>, but it doesn’t matter what it is (in this formulation at least!), so the number below is arbitrary.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="computer-practical-2.html#cb200-1" tabindex="-1"></a><span class="fu">ttest_sim</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">N=</span><span class="dv">113</span>, <span class="at">mu=</span><span class="dv">5</span>, <span class="at">tm=</span><span class="dv">3</span>, <span class="at">sd=</span><span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.78</code></pre>
<p>and this is close to what we expect from the formula approach.
To see how consistent this result is, we can see what happens over many sets of simulations</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="computer-practical-2.html#cb202-1" tabindex="-1"></a>sim_vec1 <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">100</span>)</span>
<span id="cb202-2"><a href="computer-practical-2.html#cb202-2" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb202-3"><a href="computer-practical-2.html#cb202-3" tabindex="-1"></a>  sim_vec1[i] <span class="ot">=</span> <span class="fu">ttest_sim</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">N=</span><span class="dv">113</span>, <span class="at">mu=</span><span class="dv">5</span>, <span class="at">tm=</span><span class="dv">3</span>, <span class="at">sd=</span><span class="dv">8</span>)</span>
<span id="cb202-4"><a href="computer-practical-2.html#cb202-4" tabindex="-1"></a>}</span>
<span id="cb202-5"><a href="computer-practical-2.html#cb202-5" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(sim_vec1)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-167-1.png" width="672" />
So although the mean power is around 0.8, as we expect, there is some variation.</p>
<p>To achieve <span class="math inline">\(1-\beta=0.9\)</span> we need to increase <span class="math inline">\(N\)</span>. It turns out that around 150 participants in each arm gives a mean power of around 0.9.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="computer-practical-2.html#cb203-1" tabindex="-1"></a>sim_vec2 <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">100</span>)</span>
<span id="cb203-2"><a href="computer-practical-2.html#cb203-2" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb203-3"><a href="computer-practical-2.html#cb203-3" tabindex="-1"></a>  sim_vec2[i] <span class="ot">=</span> <span class="fu">ttest_sim</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">N=</span><span class="dv">150</span>, <span class="at">mu=</span><span class="dv">5</span>, <span class="at">tm=</span><span class="dv">3</span>, <span class="at">sd=</span><span class="dv">8</span>)</span>
<span id="cb203-4"><a href="computer-practical-2.html#cb203-4" tabindex="-1"></a>}</span>
<span id="cb203-5"><a href="computer-practical-2.html#cb203-5" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(sim_vec2)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-168-1.png" width="672" /></p>
<p>It is reasonable however, to choose a number such that we are more than 50% confident of our study having the power we require. We may for example choose <span class="math inline">\(N\)</span> so that the estimated power is at least 0.9 in some high proportion (say 90%) of the simulations.</p>
</details>
<p>A useful feature of the simulation approach is that it’s much easier to investigate what happens if the real data deviate in some way from the assumptions we’ve made.</p>
<div class="exercise">
<p><span id="exr:sim-uneqsd" class="exercise"><strong>Exercise B.2  </strong></span>Adapt your code (or my code) from Exercise <a href="computer-practical-2.html#exr:ex1sim">B.1</a> to take into account the possibility of the outcome variances being different in the two groups. What is the effect on the estimated power if the outcome variance in group <span class="math inline">\(T\)</span> is 25% larger than the variance in group <span class="math inline">\(C\)</span>?</p>
</div>
<details>
<summary>
Click to reveal solution
</summary>
<p>The change we need to make is to include a variance parameter for each group, rather than a common one. Note that we aren’t changing the <code>t.test</code> function to use unequal variances, as it is common practice to keep assuming equal variances.</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="computer-practical-2.html#cb204-1" tabindex="-1"></a>ttest_sim2 <span class="ot">=</span> <span class="cf">function</span>(</span>
<span id="cb204-2"><a href="computer-practical-2.html#cb204-2" tabindex="-1"></a>    nsim,  <span class="co"># the number of simulations to use</span></span>
<span id="cb204-3"><a href="computer-practical-2.html#cb204-3" tabindex="-1"></a>    N,     <span class="co"># number of participants per trial arm</span></span>
<span id="cb204-4"><a href="computer-practical-2.html#cb204-4" tabindex="-1"></a>    mu,    <span class="co"># mean outcome (for group C / under H0)</span></span>
<span id="cb204-5"><a href="computer-practical-2.html#cb204-5" tabindex="-1"></a>    tm,    <span class="co"># minimum detectable effect size</span></span>
<span id="cb204-6"><a href="computer-practical-2.html#cb204-6" tabindex="-1"></a>    sdC,   <span class="co"># sd of outcome in group C</span></span>
<span id="cb204-7"><a href="computer-practical-2.html#cb204-7" tabindex="-1"></a>    sdT    <span class="co"># sd of outcome in group T</span></span>
<span id="cb204-8"><a href="computer-practical-2.html#cb204-8" tabindex="-1"></a>){</span>
<span id="cb204-9"><a href="computer-practical-2.html#cb204-9" tabindex="-1"></a>  H0_reject_vec <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, nsim) <span class="co"># to store 1 if H0 rejected, 0 if fail to reject H0</span></span>
<span id="cb204-10"><a href="computer-practical-2.html#cb204-10" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsim){</span>
<span id="cb204-11"><a href="computer-practical-2.html#cb204-11" tabindex="-1"></a>    out_groupC <span class="ot">=</span> <span class="fu">rnorm</span>(N, <span class="at">mean=</span>mu, <span class="at">sd=</span>sdC)</span>
<span id="cb204-12"><a href="computer-practical-2.html#cb204-12" tabindex="-1"></a>    out_groupT <span class="ot">=</span> <span class="fu">rnorm</span>(N, <span class="at">mean=</span>mu <span class="sc">+</span> tm, <span class="at">sd=</span>sdT)</span>
<span id="cb204-13"><a href="computer-practical-2.html#cb204-13" tabindex="-1"></a>    ttest <span class="ot">=</span> <span class="fu">t.test</span>(</span>
<span id="cb204-14"><a href="computer-practical-2.html#cb204-14" tabindex="-1"></a>      out_groupC, out_groupT, </span>
<span id="cb204-15"><a href="computer-practical-2.html#cb204-15" tabindex="-1"></a>      <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, </span>
<span id="cb204-16"><a href="computer-practical-2.html#cb204-16" tabindex="-1"></a>      <span class="at">var.equal =</span> T, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb204-17"><a href="computer-practical-2.html#cb204-17" tabindex="-1"></a>    H0_reject_vec[i] <span class="ot">=</span> <span class="fu">ifelse</span>(ttest<span class="sc">$</span>p.value<span class="sc">&lt;</span><span class="fl">0.05</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb204-18"><a href="computer-practical-2.html#cb204-18" tabindex="-1"></a>  }</span>
<span id="cb204-19"><a href="computer-practical-2.html#cb204-19" tabindex="-1"></a>  </span>
<span id="cb204-20"><a href="computer-practical-2.html#cb204-20" tabindex="-1"></a>  power.est <span class="ot">=</span> <span class="fu">mean</span>(H0_reject_vec)</span>
<span id="cb204-21"><a href="computer-practical-2.html#cb204-21" tabindex="-1"></a>  power.est</span>
<span id="cb204-22"><a href="computer-practical-2.html#cb204-22" tabindex="-1"></a>}</span></code></pre></div>
<p>If the variances are equal, this gives the same as before (approximately)</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="computer-practical-2.html#cb205-1" tabindex="-1"></a><span class="fu">ttest_sim2</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">N=</span><span class="dv">150</span>, <span class="at">mu=</span><span class="dv">5</span>, <span class="at">tm=</span><span class="dv">3</span>, <span class="at">sdC=</span><span class="dv">8</span>, <span class="at">sdT=</span><span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.89</code></pre>
<p>However, if we increase the outcome variance in group <span class="math inline">\(T\)</span> by 25%, things change:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="computer-practical-2.html#cb207-1" tabindex="-1"></a><span class="fu">ttest_sim2</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">N=</span><span class="dv">150</span>, <span class="at">mu=</span><span class="dv">5</span>, <span class="at">tm=</span><span class="dv">3</span>, <span class="at">sdC=</span><span class="dv">8</span>, <span class="at">sdT=</span><span class="dv">10</span>)</span></code></pre></div>
<pre><code>## [1] 0.74</code></pre>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="computer-practical-2.html#cb209-1" tabindex="-1"></a>sim_vec3 <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">100</span>)</span>
<span id="cb209-2"><a href="computer-practical-2.html#cb209-2" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb209-3"><a href="computer-practical-2.html#cb209-3" tabindex="-1"></a>  sim_vec3[i] <span class="ot">=</span> <span class="fu">ttest_sim2</span>(<span class="at">nsim=</span><span class="dv">1000</span>, <span class="at">N=</span><span class="dv">150</span>, <span class="at">mu=</span><span class="dv">5</span>, <span class="at">tm=</span><span class="dv">3</span>, <span class="at">sdC=</span><span class="dv">8</span>, <span class="at">sdT=</span><span class="dv">10</span>)</span>
<span id="cb209-4"><a href="computer-practical-2.html#cb209-4" tabindex="-1"></a>}</span>
<span id="cb209-5"><a href="computer-practical-2.html#cb209-5" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(sim_vec3)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:sim2n"></span>
<img src="CT4H_notes_files/figure-html/sim2n-1.png" alt="Power estimates for 100 sets of 100 simulations." width="672" />
<p class="caption">
Figure B.1: Power estimates for 100 sets of 100 simulations.
</p>
</div>
<p>By contrast, if the outcome variance is lower (this is much less likely) then the power will be higher than calculated:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="computer-practical-2.html#cb210-1" tabindex="-1"></a>sim_vec4 <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">100</span>)</span>
<span id="cb210-2"><a href="computer-practical-2.html#cb210-2" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb210-3"><a href="computer-practical-2.html#cb210-3" tabindex="-1"></a>  sim_vec4[i] <span class="ot">=</span> <span class="fu">ttest_sim2</span>(<span class="at">nsim=</span><span class="dv">1000</span>, <span class="at">N=</span><span class="dv">150</span>, <span class="at">mu=</span><span class="dv">5</span>, <span class="at">tm=</span><span class="dv">3</span>, <span class="at">sdC=</span><span class="dv">8</span>, <span class="at">sdT=</span><span class="dv">6</span>)</span>
<span id="cb210-4"><a href="computer-practical-2.html#cb210-4" tabindex="-1"></a>}</span>
<span id="cb210-5"><a href="computer-practical-2.html#cb210-5" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(sim_vec4)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-172-1.png" width="672" /></p>
</details>
<p>When using simulation in earnest, it is best to recreate as many features of the trial as we can, and this includes the allocation. If we were using a method that guaranteed [close to] exactly equal groups, then the above method is OK. However, this is not always the case. We will think more about this in the next section, but will implement it fairly simply now.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-76" class="exercise"><strong>Exercise B.3  </strong></span>Recreate the function from Exercise <a href="computer-practical-2.html#exr:sim-uneqsd">B.2</a>, where the two groups have different unequal variances. This time, simulate the data sequentially, using simple random sampling as the allocation method.</p>
<ul>
<li>What happens to the power distribution for the scenario we considered in that question?</li>
<li>What happens for a much smaller <span class="math inline">\(N\)</span>, say <span class="math inline">\(N=25\)</span>?</li>
</ul>
</div>
<details>
<summary>
Click for solutions
</summary>
<p>For this method, we work through all <span class="math inline">\(2N\)</span> participants sequentially, allocating them with equal probability to group <span class="math inline">\(C\)</span> or <span class="math inline">\(T\)</span>. For readability, in these solutions the simulation of one trial is written as its own function, which is then implemented <code>nsim</code> times.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="computer-practical-2.html#cb211-1" tabindex="-1"></a>one_trial_srs <span class="ot">=</span> <span class="cf">function</span>(</span>
<span id="cb211-2"><a href="computer-practical-2.html#cb211-2" tabindex="-1"></a>    N,     <span class="co"># number of participants per trial arm</span></span>
<span id="cb211-3"><a href="computer-practical-2.html#cb211-3" tabindex="-1"></a>    mu,    <span class="co"># mean outcome (for group C / under H0)</span></span>
<span id="cb211-4"><a href="computer-practical-2.html#cb211-4" tabindex="-1"></a>    tm,    <span class="co"># minimum detectable effect size</span></span>
<span id="cb211-5"><a href="computer-practical-2.html#cb211-5" tabindex="-1"></a>    sdC,   <span class="co"># sd of outcome in group C</span></span>
<span id="cb211-6"><a href="computer-practical-2.html#cb211-6" tabindex="-1"></a>    sdT    <span class="co"># sd of outcome in group T</span></span>
<span id="cb211-7"><a href="computer-practical-2.html#cb211-7" tabindex="-1"></a>){</span>
<span id="cb211-8"><a href="computer-practical-2.html#cb211-8" tabindex="-1"></a>  <span class="do">## Create empty vectors to contain output for groups C and T</span></span>
<span id="cb211-9"><a href="computer-practical-2.html#cb211-9" tabindex="-1"></a>  outC <span class="ot">=</span> <span class="fu">integer</span>()</span>
<span id="cb211-10"><a href="computer-practical-2.html#cb211-10" tabindex="-1"></a>  outT <span class="ot">=</span> <span class="fu">integer</span>()</span>
<span id="cb211-11"><a href="computer-practical-2.html#cb211-11" tabindex="-1"></a>  </span>
<span id="cb211-12"><a href="computer-practical-2.html#cb211-12" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>N)){</span>
<span id="cb211-13"><a href="computer-practical-2.html#cb211-13" tabindex="-1"></a>    <span class="co"># allocate using SRS</span></span>
<span id="cb211-14"><a href="computer-practical-2.html#cb211-14" tabindex="-1"></a>    arm <span class="ot">=</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&quot;C&quot;</span>, <span class="st">&quot;T&quot;</span>), <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb211-15"><a href="computer-practical-2.html#cb211-15" tabindex="-1"></a>    <span class="co"># generate outcome according to groups&#39; distributions</span></span>
<span id="cb211-16"><a href="computer-practical-2.html#cb211-16" tabindex="-1"></a>    <span class="cf">if</span> (arm <span class="sc">==</span> <span class="st">&quot;C&quot;</span>){</span>
<span id="cb211-17"><a href="computer-practical-2.html#cb211-17" tabindex="-1"></a>      outi <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean=</span>mu, <span class="at">sd=</span>sdC)</span>
<span id="cb211-18"><a href="computer-practical-2.html#cb211-18" tabindex="-1"></a>      outC <span class="ot">=</span> <span class="fu">c</span>(outC, outi)</span>
<span id="cb211-19"><a href="computer-practical-2.html#cb211-19" tabindex="-1"></a>    } <span class="cf">else</span> <span class="cf">if</span> (arm <span class="sc">==</span> <span class="st">&quot;T&quot;</span>){</span>
<span id="cb211-20"><a href="computer-practical-2.html#cb211-20" tabindex="-1"></a>      outi <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean=</span>mu<span class="sc">+</span>tm, <span class="at">sd=</span>sdT)</span>
<span id="cb211-21"><a href="computer-practical-2.html#cb211-21" tabindex="-1"></a>      outT <span class="ot">=</span> <span class="fu">c</span>(outT, outi)</span>
<span id="cb211-22"><a href="computer-practical-2.html#cb211-22" tabindex="-1"></a>    }</span>
<span id="cb211-23"><a href="computer-practical-2.html#cb211-23" tabindex="-1"></a>  }</span>
<span id="cb211-24"><a href="computer-practical-2.html#cb211-24" tabindex="-1"></a>  <span class="co"># conduct t-test for this trial</span></span>
<span id="cb211-25"><a href="computer-practical-2.html#cb211-25" tabindex="-1"></a>  <span class="fu">t.test</span>(<span class="at">x=</span>outC, <span class="at">y=</span>outT, </span>
<span id="cb211-26"><a href="computer-practical-2.html#cb211-26" tabindex="-1"></a>         <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">paired=</span>F, </span>
<span id="cb211-27"><a href="computer-practical-2.html#cb211-27" tabindex="-1"></a>         <span class="at">var.equal=</span>T, <span class="at">conf.level=</span><span class="fl">0.95</span>)</span>
<span id="cb211-28"><a href="computer-practical-2.html#cb211-28" tabindex="-1"></a>}</span>
<span id="cb211-29"><a href="computer-practical-2.html#cb211-29" tabindex="-1"></a></span>
<span id="cb211-30"><a href="computer-practical-2.html#cb211-30" tabindex="-1"></a>ttest_sim_srs <span class="ot">=</span> <span class="cf">function</span>(</span>
<span id="cb211-31"><a href="computer-practical-2.html#cb211-31" tabindex="-1"></a>    nsim,  <span class="co"># the number of simulations to use</span></span>
<span id="cb211-32"><a href="computer-practical-2.html#cb211-32" tabindex="-1"></a>    N,     <span class="co"># number of participants per trial arm</span></span>
<span id="cb211-33"><a href="computer-practical-2.html#cb211-33" tabindex="-1"></a>    mu,    <span class="co"># mean outcome (for group C / under H0)</span></span>
<span id="cb211-34"><a href="computer-practical-2.html#cb211-34" tabindex="-1"></a>    tm,    <span class="co"># minimum detectable effect size</span></span>
<span id="cb211-35"><a href="computer-practical-2.html#cb211-35" tabindex="-1"></a>    sdC,   <span class="co"># sd of outcome in group C</span></span>
<span id="cb211-36"><a href="computer-practical-2.html#cb211-36" tabindex="-1"></a>    sdT    <span class="co"># sd of outcome in group T</span></span>
<span id="cb211-37"><a href="computer-practical-2.html#cb211-37" tabindex="-1"></a>){</span>
<span id="cb211-38"><a href="computer-practical-2.html#cb211-38" tabindex="-1"></a>  H0_reject_vec <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, nsim) <span class="co"># to store 1 if H0 rejected, 0 if fail to reject H0</span></span>
<span id="cb211-39"><a href="computer-practical-2.html#cb211-39" tabindex="-1"></a>  </span>
<span id="cb211-40"><a href="computer-practical-2.html#cb211-40" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsim){</span>
<span id="cb211-41"><a href="computer-practical-2.html#cb211-41" tabindex="-1"></a>    trial_i <span class="ot">=</span> <span class="fu">one_trial_srs</span>(N, mu, tm, sdC, sdT)</span>
<span id="cb211-42"><a href="computer-practical-2.html#cb211-42" tabindex="-1"></a>    H0_reject_vec[i] <span class="ot">=</span> <span class="fu">ifelse</span>(trial_i<span class="sc">$</span>p.value<span class="sc">&lt;</span><span class="fl">0.05</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb211-43"><a href="computer-practical-2.html#cb211-43" tabindex="-1"></a>  }</span>
<span id="cb211-44"><a href="computer-practical-2.html#cb211-44" tabindex="-1"></a>  </span>
<span id="cb211-45"><a href="computer-practical-2.html#cb211-45" tabindex="-1"></a>  power.est <span class="ot">=</span> <span class="fu">mean</span>(H0_reject_vec)</span>
<span id="cb211-46"><a href="computer-practical-2.html#cb211-46" tabindex="-1"></a>  power.est</span>
<span id="cb211-47"><a href="computer-practical-2.html#cb211-47" tabindex="-1"></a>}</span>
<span id="cb211-48"><a href="computer-practical-2.html#cb211-48" tabindex="-1"></a></span>
<span id="cb211-49"><a href="computer-practical-2.html#cb211-49" tabindex="-1"></a><span class="fu">ttest_sim_srs</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">N=</span><span class="dv">150</span>, <span class="at">mu=</span><span class="dv">5</span>, <span class="at">tm=</span><span class="dv">3</span>, <span class="at">sdC=</span><span class="dv">8</span>, <span class="at">sdT=</span><span class="dv">10</span>)</span></code></pre></div>
<pre><code>## [1] 0.81</code></pre>
<p>To see the distribution for many simulations, we can do</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="computer-practical-2.html#cb213-1" tabindex="-1"></a>sim_vec5 <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">100</span>)</span>
<span id="cb213-2"><a href="computer-practical-2.html#cb213-2" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb213-3"><a href="computer-practical-2.html#cb213-3" tabindex="-1"></a>  sim_vec5[i] <span class="ot">=</span> <span class="fu">ttest_sim_srs</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">N=</span><span class="dv">150</span>, <span class="at">mu=</span><span class="dv">5</span>, <span class="at">tm=</span><span class="dv">3</span>, <span class="at">sdC=</span><span class="dv">8</span>, <span class="at">sdT=</span><span class="dv">10</span>)</span>
<span id="cb213-4"><a href="computer-practical-2.html#cb213-4" tabindex="-1"></a>}</span>
<span id="cb213-5"><a href="computer-practical-2.html#cb213-5" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(sim_vec5)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-174-1.png" width="672" />
and we see that the spread is much higher than when we had two exactly equal groups, as in Figure <a href="computer-practical-2.html#fig:sim2n">B.1</a>.</p>
<p>If <span class="math inline">\(N\)</span> is smaller, the variance in the power estimates will be higher, because the potential for imbalance will be greater.</p>
</details>
</div>
<div id="power-simulation-for-ancova" class="section level4 hasAnchor" number="11.1.1.2">
<h4><span class="header-section-number">B.1.1.2</span> Power simulation for ANCOVA<a href="computer-practical-2.html#power-simulation-for-ancova" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Thinking of a somewhat more complex model, we might want to perform a power simulation for an ANCOVA model.</p>
<p>We’ll write our data-generating model for the outcome <span class="math inline">\(X_i\)</span> as</p>
<p><span class="math display">\[
\begin{aligned}
x_i &amp; = \mu + \rho \left(b_i - \mu_B\right) + \epsilon_i &amp; \text{ in group C}\\
x_i &amp; = \mu + \tau + \rho \left(b_i - \mu_B\right) + \epsilon_i &amp; \text{ in group T}&amp;.
\end{aligned}
\]</span>
where <span class="math inline">\(\epsilon_i\sim N\left(0,\,\sigma^2_{\epsilon}\right)\)</span>. Now, we need to generate a value of the baseline measurement <span class="math inline">\(b_i\)</span> for each patient, and specify values for <span class="math inline">\(\mu\)</span> (the mean outcome in group C / under <span class="math inline">\(H_0\)</span>), <span class="math inline">\(\mu_B\)</span> (the mean baseline measurement), <span class="math inline">\(\tau_M\)</span> (the minimum detectable effect size, taking the place of <span class="math inline">\(\tau\)</span> in the above equation), <span class="math inline">\(\rho\)</span> (the correlation between baseline and outcome measurement) and <span class="math inline">\(\sigma^2_{\epsilon}\)</span>. Some of these are quantities that might be well-understood from the literature, but others are more speculative.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-77" class="exercise"><strong>Exercise B.4  </strong></span>Conduct a power simulation by simulating 100 participants in each group with the distributions above, where</p>
<ul>
<li><span class="math inline">\(b_i\sim N\left(\mu_B,\,5^2\right)\)</span> for all <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\epsilon_i\sim N\left(0,\,1^2\right)\)</span> for all <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\mu = 60\)</span></li>
<li><span class="math inline">\(\rho = 0.65\)</span></li>
<li><span class="math inline">\(\mu_B = 50\)</span></li>
<li><span class="math inline">\(\tau_M = 3\)</span></li>
</ul>
<p>For now, assume that the participants are allocated by simple random sampling.</p>
</div>
<details>
<summary>
Click for solutions
</summary>
<p>Now that we have a baseline variable to keep track of, we should create a data frame of participants as we generate them.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="computer-practical-2.html#cb214-1" tabindex="-1"></a>ancova_trial_srs <span class="ot">=</span> <span class="cf">function</span>(</span>
<span id="cb214-2"><a href="computer-practical-2.html#cb214-2" tabindex="-1"></a>    N,       <span class="co"># Number of participants per group</span></span>
<span id="cb214-3"><a href="computer-practical-2.html#cb214-3" tabindex="-1"></a>    mu_B,    <span class="co"># baseline mean</span></span>
<span id="cb214-4"><a href="computer-practical-2.html#cb214-4" tabindex="-1"></a>    mu,      <span class="co"># outcome mean (control group / H_0)</span></span>
<span id="cb214-5"><a href="computer-practical-2.html#cb214-5" tabindex="-1"></a>    rho,     <span class="co"># correlation between baseline and outcome</span></span>
<span id="cb214-6"><a href="computer-practical-2.html#cb214-6" tabindex="-1"></a>    tm,      <span class="co"># minimum detectable effect size</span></span>
<span id="cb214-7"><a href="computer-practical-2.html#cb214-7" tabindex="-1"></a>    sd_eps,  <span class="co"># SD of error</span></span>
<span id="cb214-8"><a href="computer-practical-2.html#cb214-8" tabindex="-1"></a>    sd_B     <span class="co"># SD of baseline measurement</span></span>
<span id="cb214-9"><a href="computer-practical-2.html#cb214-9" tabindex="-1"></a>){</span>
<span id="cb214-10"><a href="computer-practical-2.html#cb214-10" tabindex="-1"></a>  trial_mat <span class="ot">=</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">ncol=</span><span class="dv">3</span>, <span class="at">nrow=</span><span class="dv">2</span><span class="sc">*</span>N)</span>
<span id="cb214-11"><a href="computer-practical-2.html#cb214-11" tabindex="-1"></a>  trial_df <span class="ot">=</span> <span class="fu">data.frame</span>(trial_mat)</span>
<span id="cb214-12"><a href="computer-practical-2.html#cb214-12" tabindex="-1"></a>  <span class="fu">names</span>(trial_df) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;baseline&quot;</span>, <span class="st">&quot;arm&quot;</span>, <span class="st">&quot;outcome&quot;</span>)</span>
<span id="cb214-13"><a href="computer-practical-2.html#cb214-13" tabindex="-1"></a>  </span>
<span id="cb214-14"><a href="computer-practical-2.html#cb214-14" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>N)){</span>
<span id="cb214-15"><a href="computer-practical-2.html#cb214-15" tabindex="-1"></a>    bas_i <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean=</span>mu_B, <span class="at">sd=</span>sd_B)</span>
<span id="cb214-16"><a href="computer-practical-2.html#cb214-16" tabindex="-1"></a>    trial_df<span class="sc">$</span>baseline[i] <span class="ot">=</span> bas_i</span>
<span id="cb214-17"><a href="computer-practical-2.html#cb214-17" tabindex="-1"></a>    alloc_i <span class="ot">=</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&quot;C&quot;</span>, <span class="st">&quot;T&quot;</span>), <span class="dv">1</span>)</span>
<span id="cb214-18"><a href="computer-practical-2.html#cb214-18" tabindex="-1"></a>    trial_df<span class="sc">$</span>arm[i] <span class="ot">=</span> alloc_i</span>
<span id="cb214-19"><a href="computer-practical-2.html#cb214-19" tabindex="-1"></a>    eps_i <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span>sd_eps)</span>
<span id="cb214-20"><a href="computer-practical-2.html#cb214-20" tabindex="-1"></a>    <span class="cf">if</span>(alloc_i <span class="sc">==</span> <span class="st">&quot;C&quot;</span>){</span>
<span id="cb214-21"><a href="computer-practical-2.html#cb214-21" tabindex="-1"></a>      out_i <span class="ot">=</span> mu <span class="sc">+</span> rho<span class="sc">*</span>(bas_i <span class="sc">-</span> mu_B) <span class="sc">+</span> eps_i</span>
<span id="cb214-22"><a href="computer-practical-2.html#cb214-22" tabindex="-1"></a>    } <span class="cf">else</span> <span class="cf">if</span> (alloc_i <span class="sc">==</span> <span class="st">&quot;T&quot;</span>){</span>
<span id="cb214-23"><a href="computer-practical-2.html#cb214-23" tabindex="-1"></a>      out_i <span class="ot">=</span> mu <span class="sc">+</span> tm <span class="sc">+</span> rho<span class="sc">*</span>(bas_i <span class="sc">-</span> mu_B) <span class="sc">+</span> eps_i</span>
<span id="cb214-24"><a href="computer-practical-2.html#cb214-24" tabindex="-1"></a>    }</span>
<span id="cb214-25"><a href="computer-practical-2.html#cb214-25" tabindex="-1"></a>    trial_df<span class="sc">$</span>outcome[i] <span class="ot">=</span> out_i</span>
<span id="cb214-26"><a href="computer-practical-2.html#cb214-26" tabindex="-1"></a>  }</span>
<span id="cb214-27"><a href="computer-practical-2.html#cb214-27" tabindex="-1"></a>  model.fit <span class="ot">=</span> <span class="fu">lm</span>(outcome <span class="sc">~</span> baseline <span class="sc">+</span> arm, <span class="at">data=</span>trial_df)</span>
<span id="cb214-28"><a href="computer-practical-2.html#cb214-28" tabindex="-1"></a>  <span class="fu">summary</span>(model.fit)</span>
<span id="cb214-29"><a href="computer-practical-2.html#cb214-29" tabindex="-1"></a>}</span>
<span id="cb214-30"><a href="computer-practical-2.html#cb214-30" tabindex="-1"></a></span>
<span id="cb214-31"><a href="computer-practical-2.html#cb214-31" tabindex="-1"></a>ancova_sim_srs <span class="ot">=</span> <span class="cf">function</span>(</span>
<span id="cb214-32"><a href="computer-practical-2.html#cb214-32" tabindex="-1"></a>    nsim,  <span class="co"># the number of simulations to use</span></span>
<span id="cb214-33"><a href="computer-practical-2.html#cb214-33" tabindex="-1"></a>    N,       <span class="co"># Number of participants per group</span></span>
<span id="cb214-34"><a href="computer-practical-2.html#cb214-34" tabindex="-1"></a>    mu_B,    <span class="co"># baseline mean</span></span>
<span id="cb214-35"><a href="computer-practical-2.html#cb214-35" tabindex="-1"></a>    mu,      <span class="co"># outcome mean (control group / H_0)</span></span>
<span id="cb214-36"><a href="computer-practical-2.html#cb214-36" tabindex="-1"></a>    rho,     <span class="co"># correlation between baseline and outcome</span></span>
<span id="cb214-37"><a href="computer-practical-2.html#cb214-37" tabindex="-1"></a>    tm,      <span class="co"># minimum detectable effect size</span></span>
<span id="cb214-38"><a href="computer-practical-2.html#cb214-38" tabindex="-1"></a>    sd_eps,  <span class="co"># SD of error</span></span>
<span id="cb214-39"><a href="computer-practical-2.html#cb214-39" tabindex="-1"></a>    sd_B     <span class="co"># SD of baseline measurement</span></span>
<span id="cb214-40"><a href="computer-practical-2.html#cb214-40" tabindex="-1"></a>){</span>
<span id="cb214-41"><a href="computer-practical-2.html#cb214-41" tabindex="-1"></a>  H0_reject_vec <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, nsim) <span class="co"># to store 1 if H0 rejected, 0 if fail to reject H0</span></span>
<span id="cb214-42"><a href="computer-practical-2.html#cb214-42" tabindex="-1"></a>  </span>
<span id="cb214-43"><a href="computer-practical-2.html#cb214-43" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsim){</span>
<span id="cb214-44"><a href="computer-practical-2.html#cb214-44" tabindex="-1"></a>    trial_i <span class="ot">=</span> <span class="fu">ancova_trial_srs</span>(N, mu_B, mu, rho, tm, sd_eps, sd_B)</span>
<span id="cb214-45"><a href="computer-practical-2.html#cb214-45" tabindex="-1"></a>    H0_reject_vec[i] <span class="ot">=</span> <span class="fu">ifelse</span>(trial_i<span class="sc">$</span>coefficients[<span class="dv">3</span>,<span class="dv">4</span>]<span class="sc">&lt;</span><span class="fl">0.05</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb214-46"><a href="computer-practical-2.html#cb214-46" tabindex="-1"></a>  }</span>
<span id="cb214-47"><a href="computer-practical-2.html#cb214-47" tabindex="-1"></a>  </span>
<span id="cb214-48"><a href="computer-practical-2.html#cb214-48" tabindex="-1"></a>  power.est <span class="ot">=</span> <span class="fu">mean</span>(H0_reject_vec)</span>
<span id="cb214-49"><a href="computer-practical-2.html#cb214-49" tabindex="-1"></a>  power.est</span>
<span id="cb214-50"><a href="computer-practical-2.html#cb214-50" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="computer-practical-2.html#cb215-1" tabindex="-1"></a>sim_vec6 <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">100</span>)</span>
<span id="cb215-2"><a href="computer-practical-2.html#cb215-2" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb215-3"><a href="computer-practical-2.html#cb215-3" tabindex="-1"></a>  ancova_trial_i <span class="ot">=</span> <span class="fu">ancova_sim_srs</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">N=</span><span class="dv">150</span>, <span class="at">mu_B=</span><span class="dv">50</span>, <span class="at">mu=</span><span class="dv">60</span>, <span class="at">rho=</span><span class="fl">0.65</span>, <span class="at">tm=</span><span class="dv">2</span>, <span class="at">sd_eps=</span><span class="dv">1</span>, <span class="at">sd_B =</span> <span class="dv">5</span>)</span>
<span id="cb215-4"><a href="computer-practical-2.html#cb215-4" tabindex="-1"></a>  sim_vec6[i] <span class="ot">=</span> <span class="fu">ttest_sim_srs</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">N=</span><span class="dv">150</span>, <span class="at">mu=</span><span class="dv">5</span>, <span class="at">tm=</span><span class="dv">3</span>, <span class="at">sdC=</span><span class="dv">8</span>, <span class="at">sdT=</span><span class="dv">10</span>)</span>
<span id="cb215-5"><a href="computer-practical-2.html#cb215-5" tabindex="-1"></a>}</span>
<span id="cb215-6"><a href="computer-practical-2.html#cb215-6" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(sim_vec6)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-176-1.png" width="672" /></p>
</details>
<p>We could extend this in many ways to better understand the uncertainty around the power for a given sample size. For example:</p>
<ul>
<li>Trying different allocation methods</li>
<li>Incorporating uncertainty around quantities like <span class="math inline">\(\mu,\,\mu_B,\,\rho\)</span> etc.</li>
</ul>
<p>But we don’t have time in this practical!</p>
</div>
</div>
</div>
<div id="analysis-for-binary-and-survival-data" class="section level2 hasAnchor" number="11.2">
<h2><span class="header-section-number">B.2</span> Analysis for Binary and Survival data<a href="computer-practical-2.html#analysis-for-binary-and-survival-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="binary-data" class="section level3 hasAnchor" number="11.2.1">
<h3><span class="header-section-number">B.2.1</span> Binary data<a href="computer-practical-2.html#binary-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Possible dataset - change this to questions, obviously. There might be more interesting ones, check medical data file. Also, include some on model validation through holding data back - read about this a bit?</p>
<div class="example">
<p><span id="exm:unlabeled-div-78" class="example"><strong>Example B.1  </strong></span>The data in this example is from a trial in which a drug is being tested for whether it improves the conditions of a respiratory condition. For each patient, we have the following baseline covariates:</p>
<ul>
<li>sex</li>
<li>age</li>
<li>treatment centre (centre 1 or centre 2)</li>
<li>symptom status (poor = 0, good = 1).</li>
</ul>
<p>The outcome variable is whether the status of the patient’s symptoms are poor (0) or good (1) after four months of the trial. The first model we fit involves all covariates:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="computer-practical-2.html#cb216-1" tabindex="-1"></a>model1 <span class="ot">=</span> <span class="fu">glm</span>(status <span class="sc">~</span> centre <span class="sc">+</span> treatment <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> status0, </span>
<span id="cb216-2"><a href="computer-practical-2.html#cb216-2" tabindex="-1"></a>             <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span><span class="st">&#39;logit&#39;</span>), <span class="at">data=</span>resp_4)</span>
<span id="cb216-3"><a href="computer-practical-2.html#cb216-3" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = status ~ centre + treatment + sex + age + status0, 
##     family = binomial(link = &quot;logit&quot;), data = resp_4)
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)        -0.83921    0.67498  -1.243 0.213757    
## centre2             1.27397    0.48546   2.624 0.008684 ** 
## treatmenttreatment  1.08498    0.47415   2.288 0.022122 *  
## sexmale             0.33480    0.60171   0.556 0.577924    
## age                -0.02978    0.01805  -1.650 0.099035 .  
## status0good         1.72562    0.47024   3.670 0.000243 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 153.44  on 110  degrees of freedom
## Residual deviance: 119.34  on 105  degrees of freedom
## AIC: 131.34
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>And we can plot the separation plot.</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="computer-practical-2.html#cb218-1" tabindex="-1"></a>fit1 <span class="ot">=</span> <span class="fu">predict</span>(model1, resp_4, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb218-2"><a href="computer-practical-2.html#cb218-2" tabindex="-1"></a><span class="fu">separationplot</span>(fit1, (<span class="fu">as.numeric</span>(resp_4<span class="sc">$</span>status)<span class="sc">-</span><span class="dv">1</span>) )</span></code></pre></div>
<p>Having done this we can fit a second model with only those covariates that appear to be significantly active:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="computer-practical-2.html#cb219-1" tabindex="-1"></a>model2 <span class="ot">=</span> <span class="fu">glm</span>(status <span class="sc">~</span> centre <span class="sc">+</span> treatment <span class="sc">+</span>  status0, </span>
<span id="cb219-2"><a href="computer-practical-2.html#cb219-2" tabindex="-1"></a>             <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span><span class="st">&#39;logit&#39;</span>), <span class="at">data=</span>resp_4)</span>
<span id="cb219-3"><a href="computer-practical-2.html#cb219-3" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = status ~ centre + treatment + status0, family = binomial(link = &quot;logit&quot;), 
##     data = resp_4)
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)         -1.6430     0.4436  -3.704 0.000212 ***
## centre2              1.1006     0.4458   2.469 0.013554 *  
## treatmenttreatment   1.0237     0.4532   2.259 0.023891 *  
## status0good          1.7286     0.4601   3.757 0.000172 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 153.44  on 110  degrees of freedom
## Residual deviance: 122.17  on 107  degrees of freedom
## AIC: 130.17
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The separation plot shows that the model is OK (though certainly not brilliant).</p>
<p>First of all, we see that the treatment is significant, and that all other things being equal, being in the treatment group increases the log of the odds ratio by around 1.024. We can construst a 95% confidence interval for this using the estimate and standard error of the coefficient (shown in the R output above),</p>
<p><span class="math display">\[1.024 \pm 1.96 \times{0.453} = \left(0.136,\; 1.912\right).\]</span>
Taking the exponent, the 95% confidence interval for the effect of the treatment on the <strong>odds</strong> of ‘good’ symptom status at 4 months is
<span class="math display">\[\left(\exp(0.136),\; \exp(1.912)\right) = \left(1.145,\;6.768\right).\]</span></p>
<p>Using the coefficient estimates from <code>model2</code> above, we see</p>
<p><span class="math display">\[\log\frac{\pi}{1-\pi} = -1.643 + 1.101\left(\text{centre}=2\right) + 1.024\left(\text{treatment}=1\right) + 1.729\left(\text{baseline status}=1\right), \]</span>
where <span class="math inline">\(\pi\)</span> is the probability of the symptom status being ‘good’ (1) at four months.
The odds of the outcome being 1 can be estimated from this equation by taking the exponent. For example, for a patient at treatment centre 2, in the treatment group, with ‘good’ baseline status, the odds of a ‘good’ status at 4 months are approximately</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\pi}{1-\pi} &amp; =\exp\left[ -1.643 + 1.101 + 1.024 + 1.729\right] \\
&amp; = \exp\left(2.211\right)\\
&amp; = 9.125
\end{aligned}
\]</span>
which corresponds to a probability of a ‘good’ status at four months of 0.901.</p>
<p>By contrast, for a patient in the treatment group at treatment centre 1, who had ‘poor’ symptoms at baseline, the odds of a ‘good’ status at 4 months are approximately</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\pi}{1-\pi} &amp; =\exp\left[ -1.643 + 1.024 \right] \\
&amp; = \exp\left(-0.619\right) \\
&amp; = 0.538.
\end{aligned}
\]</span>
Rearranging this for probability we find <span class="math inline">\(\pi = 0.350\)</span>.</p>
<p>However, if that same participant had been in the control group instead, we would have</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\pi}{1-\pi}&amp; = \exp\left(-1.643\right)\\
&amp; = 0.193
\end{aligned}
\]</span>
and the estimated probability of having ‘good’ symptom status at four months would be 0.162.</p>
</div>
<p>Extend this by including SE - also some info about how this is found? And generating confidence intervals for these predicted probabilities?</p>
<pre><code>##    site risk             rx logodds odds prob
## 1  2_IU    1      0_placebo   -2.87 0.06 0.05
## 2  2_IU    2      0_placebo   -2.28 0.10 0.09
## 3  2_IU    3      0_placebo   -1.70 0.18 0.15
## 4  2_IU    4      0_placebo   -1.11 0.33 0.25
## 5  2_IU    5      0_placebo   -0.53 0.59 0.37
## 6  1_UM    1      0_placebo   -1.65 0.19 0.16
## 7  1_UM    2      0_placebo   -1.06 0.35 0.26
## 8  1_UM    3      0_placebo   -0.48 0.62 0.38
## 9  1_UM    4      0_placebo    0.11 1.11 0.53
## 10 1_UM    5      0_placebo    0.69 2.00 0.67
## 11 2_IU    1 1_indomethacin   -3.62 0.03 0.03
## 12 2_IU    2 1_indomethacin   -3.03 0.05 0.05
## 13 2_IU    3 1_indomethacin   -2.45 0.09 0.08
## 14 2_IU    4 1_indomethacin   -1.86 0.15 0.13
## 15 2_IU    5 1_indomethacin   -1.28 0.28 0.22
## 16 1_UM    1 1_indomethacin   -2.40 0.09 0.08
## 17 1_UM    2 1_indomethacin   -1.81 0.16 0.14
## 18 1_UM    3 1_indomethacin   -1.23 0.29 0.23
## 19 1_UM    4 1_indomethacin   -0.64 0.52 0.34
## 20 1_UM    5 1_indomethacin   -0.06 0.94 0.49</code></pre>
</div>
<div id="survival-data" class="section level3 hasAnchor" number="11.2.2">
<h3><span class="header-section-number">B.2.2</span> Survival data<a href="computer-practical-2.html#survival-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The packages we need for this section are <code>survival</code> and <code>ggfortify</code>, so install and load those now.</p>
<p>The first dataset we will use is <code>aml</code> - this dataset is from a trial investigating whether the standard course of chemotheraphy should be extended for some additional cycles (‘maintenance’) for patients with Acute Myelogenous Leukemia.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-79" class="exercise"><strong>Exercise B.5  </strong></span>Look at the help file for the <code>aml</code> dataset and make sure you understand what each variable is doing.
R might ask which <code>aml</code> dataset you want - in this case, choose the one from the <code>survival</code> package.</p>
</div>
<details>
<summary>
Click for solution
</summary>
<p>The data set <code>aml</code> has three columns</p>
<ul>
<li><code>time</code> - survival or censoring time for each patient. This is the last time at which that patient was recorded.</li>
<li><code>status</code> - censoring status. By convention, this is 1 if a death is observed (ie. for complete data) and 0 for censored data (ie. the time in the <code>time</code> column was the last time that patient was seen, and they were still alive)</li>
<li><code>x</code> - maintenance chemotherapy given? This is the treatment variable</li>
</ul>
</details>
<p>The first step is to combine the first two columns into a form we can use. We do this using the <code>Surv</code> function in the package <code>survival</code>, which creates a ‘survival object’ that we can then use in various other functions. This object contains the times and the information about which observations are censored.</p>
<p>To create a survival object from some dataset <code>dataframe</code> containing a time variable and a censoring status variable, the general form is</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="computer-practical-2.html#cb222-1" tabindex="-1"></a>surv_obj <span class="ot">=</span> <span class="fu">with</span>(<span class="at">data=</span><span class="sc">&lt;</span>dataframe<span class="sc">&gt;</span>, <span class="fu">Surv</span>(<span class="sc">&lt;</span>time variable<span class="sc">&gt;</span>, <span class="sc">&lt;</span>censoring status variable<span class="sc">&gt;</span>))</span></code></pre></div>
<p>or if you prefer,</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="computer-practical-2.html#cb223-1" tabindex="-1"></a>surv_obj <span class="ot">=</span> <span class="fu">Surv</span>(<span class="sc">&lt;</span>dataframe<span class="sc">$</span>time variable<span class="sc">&gt;</span>, <span class="sc">&lt;</span>dataframe<span class="sc">$</span>censoring status variable<span class="sc">&gt;</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-80" class="exercise"><strong>Exercise B.6  </strong></span>Use the <code>Surv</code> function now on the <code>aml</code> data. The output will contain some notation you probably haven’t seen before - can you work out what it means?</p>
</div>
<details>
<summary>
Click for solution
</summary>
<p>We create the survival object for <code>aml</code> by</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="computer-practical-2.html#cb224-1" tabindex="-1"></a>surv_aml <span class="ot">=</span> <span class="fu">with</span>(<span class="at">data=</span>aml, <span class="fu">Surv</span>(time,status))</span>
<span id="cb224-2"><a href="computer-practical-2.html#cb224-2" tabindex="-1"></a>surv_aml</span></code></pre></div>
<pre><code>##  [1]   9   13   13+  18   23   28+  31   34   45+  48  161+   5    5    8    8   12   16+  23   27   30   33   43   45</code></pre>
<p>This is a vector of the time values, in the same order as in <code>aml</code>. You’ll notice that some have a ‘+’ attached. This denotes the censored observations (the notation reflects the fact that the true time of death/the event will be greater than this).</p>
</details>
</div>
<div id="fitting-a-survival-curve" class="section level3 hasAnchor" number="11.2.3">
<h3><span class="header-section-number">B.2.3</span> Fitting a survival curve<a href="computer-practical-2.html#fitting-a-survival-curve" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The next thing we probably want to do is to estimate the survival function, plot the survival curve.
The first method we’ll use is the Kaplan-Meier estimator.</p>
<p>JUST USE THE COLON DATA!!!</p>
<div id="kaplan-meier" class="section level4 hasAnchor" number="11.2.3.1">
<h4><span class="header-section-number">B.2.3.1</span> Kaplan-Meier<a href="computer-practical-2.html#kaplan-meier" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To fit a Kaplan-Meier survival curve, we use the function <code>survfit</code>, which is specified using a formula, much like <code>lm</code> or <code>glm</code>. To fit a Kaplan-Meier estimate with a data frame split by treatment effect, the general form is</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="computer-practical-2.html#cb226-1" tabindex="-1"></a><span class="fu">survfit</span>(<span class="sc">&lt;</span>surv_obj<span class="sc">&gt;</span> <span class="er">~</span> <span class="er">&lt;</span>treatment var<span class="sc">&gt;</span>, <span class="at">data =</span> <span class="sc">&lt;</span>dataframe<span class="sc">&gt;</span>)</span></code></pre></div>
<p>We can then use <code>summary</code> to see the intermediary calculations at each step, and <code>plot</code> (for base plot) or <code>autoplot</code> (from <code>ggplot2</code> and <code>ggfortify</code>) to plot the curves.</p>
<div class="exercise">
<p><span id="exr:kmaml" class="exercise"><strong>Exercise B.7  </strong></span>Fit a Kaplan-Meier estimator to the <code>aml</code> data. View the table using <code>summary</code>. Plot the curves using <code>autoplot</code>.</p>
</div>
<details>
<summary>
Click for solution
</summary>
<p>To fit the Kaplan-Meier estimator we use</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="computer-practical-2.html#cb227-1" tabindex="-1"></a>km_aml <span class="ot">=</span> <span class="fu">survfit</span>(surv_aml <span class="sc">~</span> x, <span class="at">data=</span>aml)</span></code></pre></div>
<p>We can then look at the summary table and plot the data by</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="computer-practical-2.html#cb228-1" tabindex="-1"></a><span class="fu">summary</span>(km_aml)</span></code></pre></div>
<pre><code>## Call: survfit(formula = surv_aml ~ x, data = aml)
## 
##                 x=Maintained 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     9     11       1    0.909  0.0867       0.7541        1.000
##    13     10       1    0.818  0.1163       0.6192        1.000
##    18      8       1    0.716  0.1397       0.4884        1.000
##    23      7       1    0.614  0.1526       0.3769        0.999
##    31      5       1    0.491  0.1642       0.2549        0.946
##    34      4       1    0.368  0.1627       0.1549        0.875
##    48      2       1    0.184  0.1535       0.0359        0.944
## 
##                 x=Nonmaintained 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     5     12       2   0.8333  0.1076       0.6470        1.000
##     8     10       2   0.6667  0.1361       0.4468        0.995
##    12      8       1   0.5833  0.1423       0.3616        0.941
##    23      6       1   0.4861  0.1481       0.2675        0.883
##    27      5       1   0.3889  0.1470       0.1854        0.816
##    30      4       1   0.2917  0.1387       0.1148        0.741
##    33      3       1   0.1944  0.1219       0.0569        0.664
##    43      2       1   0.0972  0.0919       0.0153        0.620
##    45      1       1   0.0000     NaN           NA           NA</code></pre>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="computer-practical-2.html#cb230-1" tabindex="-1"></a><span class="fu">autoplot</span>(km_aml, <span class="at">conf.int=</span>F)</span></code></pre></div>
<img src="CT4H_notes_files/figure-html/unnamed-chunk-188-1.png" width="672" />
We can see from the table that the lower curve is the non-maintained arm - there is only one survivor of this group, and the data finish at <span class="math inline">\(t=45\)</span>.
</details>
<p>The function <code>autoplot</code> could also give us a 95% CI if we set <code>conf.int=T</code> (we didn’t go into how this is calculated in lectures) and we see that with the <code>aml</code> data the uncertainty is huge.</p>
</div>
</div>
<div id="comparing-survival-curves-likelihood-ratio-test" class="section level3 hasAnchor" number="11.2.4">
<h3><span class="header-section-number">B.2.4</span> Comparing survival curves: likelihood ratio test<a href="computer-practical-2.html#comparing-survival-curves-likelihood-ratio-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Having found the MLEs for the <code>aml</code> dataset assuming an exponential distribution, we can immediately perform a likelihood ratio test.</p>
<div id="fitting-an-exponential-distribution" class="section level4 hasAnchor" number="11.2.4.1">
<h4><span class="header-section-number">B.2.4.1</span> Fitting an exponential distribution<a href="computer-practical-2.html#fitting-an-exponential-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To fit an exponential distribution, we need to estimate <span class="math inline">\(\hat\lambda_C\)</span> and <span class="math inline">\(\hat\lambda_T\)</span>, using</p>
<p><span class="math display">\[\hat\lambda_X = \frac{m_X}{\sum\limits_{i=1}^{n_X} t_i} = \frac{m_X}{t^+_X}, \]</span>
where <span class="math inline">\(n_X\)</span> is the number of observations <span class="math inline">\(t_1,\ldots,t_{n_X}\)</span> in group <span class="math inline">\(X\)</span>, of which <span class="math inline">\(m_X\)</span> are censored.</p>
<div class="exercise">
<p><span id="exr:mlaml" class="exercise"><strong>Exercise B.8  </strong></span>Fit an exponential distribution for each treatment group to the <code>aml</code> data and plot the resulting estimated survival curves, along with the Kaplan Meier estimators from Exercise <a href="computer-practical-2.html#exr:kmaml">B.7</a> (for comparison).</p>
</div>
<details>
<summary>
Click for solution
</summary>
<p>To calculate <span class="math inline">\(\hat\lambda_C\)</span> and <span class="math inline">\(\hat\lambda_T\)</span> we need to find <span class="math inline">\(m_C,\;\,m_T\;,t^+_C\)</span> and <span class="math inline">\(t^+_T\)</span>.</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="computer-practical-2.html#cb231-1" tabindex="-1"></a>mC_aml <span class="ot">=</span> <span class="fu">sum</span>((aml<span class="sc">$</span>status<span class="sc">==</span><span class="dv">1</span>)<span class="sc">&amp;</span>(aml<span class="sc">$</span>x<span class="sc">==</span><span class="st">&quot;Nonmaintained&quot;</span>))</span>
<span id="cb231-2"><a href="computer-practical-2.html#cb231-2" tabindex="-1"></a>mT_aml <span class="ot">=</span> <span class="fu">sum</span>((aml<span class="sc">$</span>status<span class="sc">==</span><span class="dv">1</span>)<span class="sc">&amp;</span>(aml<span class="sc">$</span>x<span class="sc">==</span><span class="st">&quot;Maintained&quot;</span>))</span>
<span id="cb231-3"><a href="computer-practical-2.html#cb231-3" tabindex="-1"></a>tsum_aml_C <span class="ot">=</span> <span class="fu">sum</span>(aml<span class="sc">$</span>time[aml<span class="sc">$</span>x<span class="sc">==</span><span class="st">&quot;Nonmaintained&quot;</span>])</span>
<span id="cb231-4"><a href="computer-practical-2.html#cb231-4" tabindex="-1"></a>tsum_aml_T <span class="ot">=</span> <span class="fu">sum</span>(aml<span class="sc">$</span>time[aml<span class="sc">$</span>x<span class="sc">==</span><span class="st">&quot;Maintained&quot;</span>])</span>
<span id="cb231-5"><a href="computer-practical-2.html#cb231-5" tabindex="-1"></a>lamhat_aml_C <span class="ot">=</span> mC_aml <span class="sc">/</span> tsum_aml_C</span>
<span id="cb231-6"><a href="computer-practical-2.html#cb231-6" tabindex="-1"></a>lamhat_aml_T <span class="ot">=</span> mT_aml <span class="sc">/</span> tsum_aml_T</span></code></pre></div>
<p>We can then plot the Survival curves using <code>geom_function</code></p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="computer-practical-2.html#cb232-1" tabindex="-1"></a><span class="co"># Define survival function for exponential density</span></span>
<span id="cb232-2"><a href="computer-practical-2.html#cb232-2" tabindex="-1"></a></span>
<span id="cb232-3"><a href="computer-practical-2.html#cb232-3" tabindex="-1"></a>exp_st <span class="ot">=</span> <span class="cf">function</span>(t, lambda){<span class="fu">exp</span>(<span class="sc">-</span>lambda<span class="sc">*</span>t)}</span>
<span id="cb232-4"><a href="computer-practical-2.html#cb232-4" tabindex="-1"></a></span>
<span id="cb232-5"><a href="computer-practical-2.html#cb232-5" tabindex="-1"></a><span class="fu">autoplot</span>(km_aml, <span class="at">conf.int=</span>F) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">1</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb232-6"><a href="computer-practical-2.html#cb232-6" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>exp_st, <span class="at">args=</span><span class="fu">list</span>(<span class="at">lambda =</span> lamhat_aml_C), <span class="at">col=</span><span class="st">&quot;darkturquoise&quot;</span>) <span class="sc">+</span></span>
<span id="cb232-7"><a href="computer-practical-2.html#cb232-7" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>exp_st, <span class="at">args=</span><span class="fu">list</span>(<span class="at">lambda =</span> lamhat_aml_T), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-190-1.png" width="672" /></p>
</details>
</div>
</div>
<div id="comparing-survival-curves-1" class="section level3 hasAnchor" number="11.2.5">
<h3><span class="header-section-number">B.2.5</span> Comparing survival curves<a href="computer-practical-2.html#comparing-survival-curves-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Having found the MLEs for the <code>aml</code> dataset, assuming an exponential distribution, we can now immediately conduct a likelihood ratio test.</p>
<div id="likelihood-ratio-test" class="section level4 hasAnchor" number="11.2.5.1">
<h4><span class="header-section-number">B.2.5.1</span> Likelihood ratio test<a href="computer-practical-2.html#likelihood-ratio-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Recall that our test statistic (which we found in Section <a href="comparing-survival-curves.html#survlrtest">8.1</a>) is</p>
<p><span class="math display">\[ \lambda_{LR} = 2\left(m_C\log\left(\frac{m_C}{t^+_C}\right) + m_T\log\left(\frac{m_T}{t^+_T}\right) - m\log\left(\frac{m}{t^+}\right)\right),\]</span></p>
<p>which we then refer to a <span class="math inline">\(\chi^2_1\)</span> distribution.</p>
<div class="exercise">
<p><span id="exr:lrtestaml" class="exercise"><strong>Exercise B.9  </strong></span>Conduct a likelihood ratio test for the <code>aml</code> data, with the null hypothesis that the survival curves are the same for both treatment groups. Before you calculate the answer, think about what you expect to see.</p>
</div>
<details>
<summary>
Click for solution
</summary>
<p>We already have the <span class="math inline">\(m_X\)</span> and <span class="math inline">\(t^+_X\)</span> from Exercise <a href="computer-practical-2.html#exr:mlaml">B.8</a>, and we can easily find <span class="math inline">\(t^+\)</span> and <span class="math inline">\(m\)</span> from these.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="computer-practical-2.html#cb233-1" tabindex="-1"></a>m_aml <span class="ot">=</span> mT_aml <span class="sc">+</span> mC_aml</span>
<span id="cb233-2"><a href="computer-practical-2.html#cb233-2" tabindex="-1"></a>tsum_aml <span class="ot">=</span> tsum_aml_T <span class="sc">+</span> tsum_aml_C</span></code></pre></div>
<p>and we can use these to compute <span class="math inline">\(\lambda_{LR}\)</span>:</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="computer-practical-2.html#cb234-1" tabindex="-1"></a>LRstat_aml <span class="ot">=</span>  <span class="dv">2</span><span class="sc">*</span>(mC_aml<span class="sc">*</span><span class="fu">log</span>(mC_aml<span class="sc">/</span>tsum_aml_C) <span class="sc">+</span> mT_aml<span class="sc">*</span><span class="fu">log</span>(mT_aml<span class="sc">/</span>tsum_aml_T) <span class="sc">-</span> m_aml<span class="sc">*</span><span class="fu">log</span>(m_aml<span class="sc">/</span>tsum_aml))</span>
<span id="cb234-2"><a href="computer-practical-2.html#cb234-2" tabindex="-1"></a>LRstat_aml</span></code></pre></div>
<pre><code>## [1] 4.061349</code></pre>
<p>Finally, we refer this to <span class="math inline">\(\chi^2_1\)</span></p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="computer-practical-2.html#cb236-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(LRstat_aml, <span class="at">df=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.04387544</code></pre>
<p>We find that we have just enough evidence to reject <span class="math inline">\(H_0\)</span> at the 95% level.</p>
</details>
</div>
<div id="log-rank-test" class="section level4 hasAnchor" number="11.2.5.2">
<h4><span class="header-section-number">B.2.5.2</span> Log-rank test<a href="computer-practical-2.html#log-rank-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The log-rank test is most easily found using the function <code>survdiff</code>. This function has an argument <code>rho</code> that controls the type of test. If we set <code>rho=1</code> then it performs a log-rank test.</p>
<p>The general form is similar to <code>survfit</code>:</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="computer-practical-2.html#cb238-1" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="sc">&lt;</span>surv_obj<span class="sc">&gt;</span> <span class="er">~</span> <span class="er">&lt;</span>treatment variable<span class="sc">&gt;</span>, <span class="at">data=</span><span class="sc">&lt;</span>dataframe<span class="sc">&gt;</span>, <span class="at">rho=</span><span class="dv">0</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:logrankaml" class="exercise"><strong>Exercise B.10  </strong></span>Use <code>survdiff</code> to do a log rank test on the <code>aml</code> data. Do you expect the results to be similar to your results from Exercise <a href="computer-practical-2.html#exr:lrtestaml">B.9</a>?</p>
</div>
<details>
<summary>
Click for solution
</summary>
<p>To conduct a log rank test we use</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="computer-practical-2.html#cb239-1" tabindex="-1"></a><span class="fu">survdiff</span>(surv_aml<span class="sc">~</span>x, <span class="at">data=</span>aml, <span class="at">rho=</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## Call:
## survdiff(formula = surv_aml ~ x, data = aml, rho = 0)
## 
##                  N Observed Expected (O-E)^2/E (O-E)^2/V
## x=Maintained    11        7    10.69      1.27       3.4
## x=Nonmaintained 12       11     7.31      1.86       3.4
## 
##  Chisq= 3.4  on 1 degrees of freedom, p= 0.07</code></pre>
This is not that close to the result of the likelihood ratio test, probably reflecting the less-than-perfect fit of the exponential survival curve.
</details>
</div>
<div id="cox-regression-1" class="section level4 hasAnchor" number="11.2.5.3">
<h4><span class="header-section-number">B.2.5.3</span> Cox regression<a href="computer-practical-2.html#cox-regression-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Finally, we will fit the Cox regression model, so that we can include some baseline covariates. In the <code>aml</code> dataset there are no baseline</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="computer-practical-2.html#cb241-1" tabindex="-1"></a><span class="fu">coxph</span>(<span class="at">formula =</span> <span class="fu">Surv</span>(time, status)<span class="sc">~</span>x, <span class="at">data=</span>aml)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ x, data = aml)
## 
##                  coef exp(coef) se(coef)     z      p
## xNonmaintained 0.9155    2.4981   0.5119 1.788 0.0737
## 
## Likelihood ratio test=3.38  on 1 df, p=0.06581
## n= 23, number of events= 18</code></pre>
<div class="exercise">
<p><span id="exr:unlabeled-div-81" class="exercise"><strong>Exercise B.11  </strong></span>NOT:
bladder (too complicated with follow ups)
Veteran (in homework)
cgd - could restrict to enum=1?
colon - looks promising. Restrict to Obs and Lev+5FU</p>
<p>The dataset <code>colon</code>, also from the <code>survival</code> package, contains data from a trial of colon cancer patients, comparing three treatments: observation (<code>obs</code>), levamisole (<code>Lev</code>) and levamisole + 5-FU (<code>Lev+5FU</code>). To simplify things, we will restrict the data to those patients on <code>Obs</code> or <code>Lev+5FU</code>. The main report of this trial is <span class="citation">Moertel et al. (<a href="#ref-moertel1990levamisole">1990</a>)</span>.</p>
<p>For this data</p>
<ol style="list-style-type: decimal">
<li>Look at the help file and make sure you understand what the columns mean (note that there are three possible datasets - we’re using <code>bladder</code>, the simplest)</li>
<li>Fit Kaplan-Meier estimators to the survival curves for the two groups.</li>
</ol>
</div>
<details>
<summary>
Click for solution
</summary>
<p>From the help file we see that <code>rx</code> is the treatment group, <code>stop</code> is the time variable, <code>status</code> gives the censoring status.</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="computer-practical-2.html#cb243-1" tabindex="-1"></a><span class="fu">str</span>(colondf)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    1238 obs. of  16 variables:
##  $ id      : num  1 1 2 2 3 3 4 4 5 5 ...
##  $ study   : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ rx      : Factor w/ 2 levels &quot;Lev+5FU&quot;,&quot;Obs&quot;: 1 1 1 1 2 2 1 1 2 2 ...
##  $ sex     : num  1 1 1 1 0 0 0 0 1 1 ...
##  $ age     : num  43 43 63 63 71 71 66 66 69 69 ...
##  $ obstruct: num  0 0 0 0 0 0 1 1 0 0 ...
##  $ perfor  : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ adhere  : num  0 0 0 0 1 1 0 0 0 0 ...
##  $ nodes   : num  5 5 1 1 7 7 6 6 22 22 ...
##  $ status  : num  1 1 0 0 1 1 1 1 1 1 ...
##  $ differ  : num  2 2 2 2 2 2 2 2 2 2 ...
##  $ extent  : num  3 3 3 3 2 2 3 3 3 3 ...
##  $ surg    : num  0 0 0 0 0 0 1 1 1 1 ...
##  $ node4   : num  1 1 0 0 1 1 1 1 1 1 ...
##  $ time    : num  1521 968 3087 3087 963 ...
##  $ etype   : num  2 1 2 1 2 1 2 1 2 1 ...</code></pre>
<p>We can therefore fit (and plot) the Kaplan-Meier estimator split by treatment group.</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="computer-practical-2.html#cb245-1" tabindex="-1"></a>km_colon <span class="ot">=</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> rx, <span class="at">data=</span>colondf)</span>
<span id="cb245-2"><a href="computer-practical-2.html#cb245-2" tabindex="-1"></a><span class="fu">autoplot</span>(km_colon, <span class="at">conf.int=</span>F) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-199-1.png" width="672" /></p>
<p>Next we can find the MLE for each treatment group</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="computer-practical-2.html#cb246-1" tabindex="-1"></a>mC_colon <span class="ot">=</span> <span class="fu">sum</span>((colondf<span class="sc">$</span>status<span class="sc">==</span><span class="dv">1</span>)<span class="sc">&amp;</span>(colondf<span class="sc">$</span>rx<span class="sc">==</span><span class="st">&quot;Obs&quot;</span>))</span>
<span id="cb246-2"><a href="computer-practical-2.html#cb246-2" tabindex="-1"></a>mT_colon <span class="ot">=</span> <span class="fu">sum</span>((colondf<span class="sc">$</span>status<span class="sc">==</span><span class="dv">1</span>)<span class="sc">&amp;</span>(colondf<span class="sc">$</span>rx<span class="sc">==</span><span class="st">&quot;Lev+5FU&quot;</span>))</span>
<span id="cb246-3"><a href="computer-practical-2.html#cb246-3" tabindex="-1"></a>tsum_colon_C <span class="ot">=</span> <span class="fu">sum</span>(colondf<span class="sc">$</span>time[colondf<span class="sc">$</span>rx<span class="sc">==</span><span class="st">&quot;Obs&quot;</span>])</span>
<span id="cb246-4"><a href="computer-practical-2.html#cb246-4" tabindex="-1"></a>tsum_colon_T <span class="ot">=</span> <span class="fu">sum</span>(colondf<span class="sc">$</span>time[colondf<span class="sc">$</span>rx<span class="sc">==</span><span class="st">&quot;Lev+5FU&quot;</span>])</span>
<span id="cb246-5"><a href="computer-practical-2.html#cb246-5" tabindex="-1"></a>lamhat_colon_C <span class="ot">=</span> mC_colon <span class="sc">/</span> tsum_colon_C</span>
<span id="cb246-6"><a href="computer-practical-2.html#cb246-6" tabindex="-1"></a>lamhat_colon_T <span class="ot">=</span> mT_colon <span class="sc">/</span> tsum_colon_T</span></code></pre></div>
<p>We can then plot the Survival curves using <code>geom_function</code></p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="computer-practical-2.html#cb247-1" tabindex="-1"></a><span class="co"># Define survival function for exponential density</span></span>
<span id="cb247-2"><a href="computer-practical-2.html#cb247-2" tabindex="-1"></a></span>
<span id="cb247-3"><a href="computer-practical-2.html#cb247-3" tabindex="-1"></a><span class="fu">autoplot</span>(km_colon, <span class="at">conf.int=</span>F) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">1</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb247-4"><a href="computer-practical-2.html#cb247-4" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>exp_st, <span class="at">args=</span><span class="fu">list</span>(<span class="at">lambda =</span> lamhat_colon_C), <span class="at">col=</span><span class="st">&quot;darkturquoise&quot;</span>) <span class="sc">+</span></span>
<span id="cb247-5"><a href="computer-practical-2.html#cb247-5" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>exp_st, <span class="at">args=</span><span class="fu">list</span>(<span class="at">lambda =</span> lamhat_colon_T), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cp2poorfit"></span>
<img src="CT4H_notes_files/figure-html/cp2poorfit-1.png" alt="Survival curves for groups C and T in colon study, fitted assuming an exponential distribution. Kaplan-Meier estimates also shown." width="672" />
<p class="caption">
Figure B.2: Survival curves for groups C and T in colon study, fitted assuming an exponential distribution. Kaplan-Meier estimates also shown.
</p>
</div>
<p>We see that this fit is quite poor.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="computer-practical-2.html#cb248-1" tabindex="-1"></a>m_colon <span class="ot">=</span> mT_colon <span class="sc">+</span> mC_colon</span>
<span id="cb248-2"><a href="computer-practical-2.html#cb248-2" tabindex="-1"></a>tsum_colon <span class="ot">=</span> tsum_colon_T <span class="sc">+</span> tsum_colon_C</span></code></pre></div>
<p>and we can use these to compute <span class="math inline">\(\lambda_{LR}\)</span>:</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="computer-practical-2.html#cb249-1" tabindex="-1"></a>LRstat_colon <span class="ot">=</span>  <span class="dv">2</span><span class="sc">*</span>(mC_colon<span class="sc">*</span><span class="fu">log</span>(mC_colon<span class="sc">/</span>tsum_colon_C) <span class="sc">+</span> mT_colon<span class="sc">*</span><span class="fu">log</span>(mT_colon<span class="sc">/</span>tsum_colon_T) <span class="sc">-</span> m_colon<span class="sc">*</span><span class="fu">log</span>(m_colon<span class="sc">/</span>tsum_colon))</span>
<span id="cb249-2"><a href="computer-practical-2.html#cb249-2" tabindex="-1"></a>LRstat_colon</span></code></pre></div>
<pre><code>## [1] 35.0111</code></pre>
<p>Finally, we refer this to <span class="math inline">\(\chi^2_1\)</span></p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="computer-practical-2.html#cb251-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(LRstat_colon, <span class="at">df=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 3.278309e-09</code></pre>
<p>Highly significant, but because of the very poor fit in Figure <a href="computer-practical-2.html#fig:cp2poorfit">B.2</a> not especially trustworthy.</p>
<p>Next, we can perform a log-rank test:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="computer-practical-2.html#cb253-1" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(time, status)<span class="sc">~</span>rx, <span class="at">data=</span>colondf, <span class="at">rho=</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(time, status) ~ rx, data = colondf, rho = 0)
## 
##              N Observed Expected (O-E)^2/E (O-E)^2/V
## rx=Lev+5FU 608      242      306      13.5      28.2
## rx=Obs     630      345      281      14.7      28.2
## 
##  Chisq= 28.2  on 1 degrees of freedom, p= 1e-07</code></pre>
<p>We see that the test statistic, although still very significant, is much lower than for the likelihood ratio test.</p>
<p>Finally, we fit a Cox regression model. In the first instance we can do this with just the treatment group as a covariate:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="computer-practical-2.html#cb255-1" tabindex="-1"></a><span class="fu">coxph</span>(<span class="at">formula =</span> <span class="fu">Surv</span>(time, status)<span class="sc">~</span>rx, <span class="at">data=</span>colondf)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ rx, data = colondf)
## 
##          coef exp(coef) se(coef)     z        p
## rxObs 0.44213   1.55602  0.08394 5.267 1.38e-07
## 
## Likelihood ratio test=28.25  on 1 df, p=1.068e-07
## n= 1238, number of events= 587</code></pre>
<p>But we can also include other baseline covariates</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="computer-practical-2.html#cb257-1" tabindex="-1"></a><span class="fu">coxph</span>(<span class="at">formula =</span> <span class="fu">Surv</span>(time, status)<span class="sc">~</span>rx <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> obstruct <span class="sc">+</span> nodes, <span class="at">data=</span>colondf)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ rx + sex + age + obstruct + 
##     nodes, data = colondf)
## 
##               coef exp(coef)  se(coef)      z        p
## rxObs     0.470039  1.600056  0.085522  5.496 3.88e-08
## sex      -0.155126  0.856308  0.083835 -1.850   0.0643
## age      -0.002940  0.997064  0.003400 -0.865   0.3872
## obstruct  0.072027  1.074685  0.105813  0.681   0.4961
## nodes     0.104607  1.110274  0.008493 12.317  &lt; 2e-16
## 
## Likelihood ratio test=146  on 5 df, p=&lt; 2.2e-16
## n= 1214, number of events= 574 
##    (24 observations deleted due to missingness)</code></pre>
<p>and we see that as well as the treatment arm, the number of lymph nodes with detectable cancer (given by <code>nodes</code>) is highly significant, and <code>sex</code> is also fairly significant.</p>
<p>We can visualise this by further subsetting the Kaplan-Meier estimator</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="computer-practical-2.html#cb259-1" tabindex="-1"></a>km_colon_bl <span class="ot">=</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> rx <span class="sc">+</span> sex, <span class="at">data=</span>colondf)</span>
<span id="cb259-2"><a href="computer-practical-2.html#cb259-2" tabindex="-1"></a><span class="fu">autoplot</span>(km_colon_bl, <span class="at">conf.int=</span>F)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-207-1.png" width="672" />
<code>nodes</code> is a numeric output, so in order to get a visual impression of its effect on the survival curve we can bin it. For example, we can choose <span class="math inline">\(\texttt{nodes}\leq 4\)</span> and <span class="math inline">\(\texttt{nodes}&gt;4\)</span>.</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="computer-practical-2.html#cb260-1" tabindex="-1"></a>colondf<span class="sc">$</span>nodes4 <span class="ot">=</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(colondf), <span class="cf">function</span>(i){<span class="fu">ifelse</span>(colondf<span class="sc">$</span>nodes[i]<span class="sc">&gt;</span><span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">0</span>)})</span>
<span id="cb260-2"><a href="computer-practical-2.html#cb260-2" tabindex="-1"></a>km_colon_bl <span class="ot">=</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> rx <span class="sc">+</span> nodes4, <span class="at">data=</span>colondf)</span>
<span id="cb260-3"><a href="computer-practical-2.html#cb260-3" tabindex="-1"></a><span class="fu">autoplot</span>(km_colon_bl, <span class="at">conf.int=</span>F)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-208-1.png" width="672" /></p>
</details>
</div>
</div>
</div>
<div id="cp2sim2" class="section level2 hasAnchor" number="11.3">
<h2><span class="header-section-number">B.3</span> Sample size by simulation (part II)<a href="computer-practical-2.html#cp2sim2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We now combine the work we’ve done, to implement power simulation for a survival outcome trial.</p>
<table>
<thead>
<tr class="header">
<th align="center">time</th>
<th align="center">censor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">31.16</td>
<td align="center">TRUE</td>
</tr>
<tr class="even">
<td align="center">73.94</td>
<td align="center">TRUE</td>
</tr>
<tr class="odd">
<td align="center">71.90</td>
<td align="center">TRUE</td>
</tr>
<tr class="even">
<td align="center">100.00</td>
<td align="center">FALSE</td>
</tr>
<tr class="odd">
<td align="center">100.00</td>
<td align="center">FALSE</td>
</tr>
<tr class="even">
<td align="center">74.91</td>
<td align="center">TRUE</td>
</tr>
<tr class="odd">
<td align="center">37.79</td>
<td align="center">TRUE</td>
</tr>
<tr class="even">
<td align="center">72.28</td>
<td align="center">TRUE</td>
</tr>
<tr class="odd">
<td align="center">50.63</td>
<td align="center">TRUE</td>
</tr>
<tr class="even">
<td align="center">45.88</td>
<td align="center">TRUE</td>
</tr>
</tbody>
</table>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-arnold2011simulation" class="csl-entry">
Arnold, Benjamin F, Daniel R Hogan, John M Colford, and Alan E Hubbard. 2011. <span>“Simulation Methods to Estimate Design Power: An Overview for Applied Research.”</span> <em>BMC Medical Research Methodology</em> 11 (1): 1–10.
</div>
<div id="ref-moertel1990levamisole" class="csl-entry">
Moertel, Charles G, Thomas R Fleming, John S Macdonald, Daniel G Haller, John A Laurie, Phyllis J Goodman, James S Ungerleider, et al. 1990. <span>“Levamisole and Fluorouracil for Adjuvant Therapy of Resected Colon Carcinoma.”</span> <em>New England Journal of Medicine</em> 322 (6): 352–58.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="computer-practical-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["CT4H_notes.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"bookdown": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
