<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 Random effects for individuals | Clinical Trials 4H</title>
  <meta name="description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="10 Random effects for individuals | Clinical Trials 4H" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 Random effects for individuals | Clinical Trials 4H" />
  
  <meta name="twitter:description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  

<meta name="author" content="Rachel Oughton" />


<meta name="date" content="2024-03-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="cluster-rct.html"/>
<link rel="next" href="the-bayesian-approach.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Clinical Trials 4H!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#practical-details"><i class="fa fa-check"></i>Practical details</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#lectures"><i class="fa fa-check"></i>Lectures</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#computer-classes"><i class="fa fa-check"></i>Computer classes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#office-hour"><i class="fa fa-check"></i>Office Hour</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i>Assessment</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#books"><i class="fa fa-check"></i>Books</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-to-expect-from-this-module"><i class="fa fa-check"></i>What to expect from this module</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-i-expect-from-you"><i class="fa fa-check"></i>What I expect from you</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="rct-intro.html"><a href="rct-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction to Clinical Trials</a>
<ul>
<li class="chapter" data-level="1.1" data-path="rct-intro.html"><a href="rct-intro.html#causal-inference-and-clinical-trials"><i class="fa fa-check"></i><b>1.1</b> Causal inference and clinical trials</a></li>
<li class="chapter" data-level="1.2" data-path="rct-intro.html"><a href="rct-intro.html#the-structure-of-a-clinical-trial"><i class="fa fa-check"></i><b>1.2</b> The structure of a clinical trial</a>
<ul>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#the-population-of-eligible-patients"><i class="fa fa-check"></i>The population of eligible patients</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#entry-to-the-trial"><i class="fa fa-check"></i>Entry to the trial</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#allocation-to-groups"><i class="fa fa-check"></i>Allocation to groups</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#comparing-results"><i class="fa fa-check"></i>Comparing results</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#why-bother-with-a-control-group"><i class="fa fa-check"></i>Why bother with a control group?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="rct-intro.html"><a href="rct-intro.html#primout"><i class="fa fa-check"></i><b>1.3</b> The primary outcome</a></li>
<li class="chapter" data-level="1.4" data-path="rct-intro.html"><a href="rct-intro.html#ethical-issues"><i class="fa fa-check"></i><b>1.4</b> Ethical issues</a></li>
<li class="chapter" data-level="1.5" data-path="rct-intro.html"><a href="rct-intro.html#phases-of-clinical-trials"><i class="fa fa-check"></i><b>1.5</b> Phases of clinical trials</a>
<ul>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-zero"><i class="fa fa-check"></i>Phase zero</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-one"><i class="fa fa-check"></i>Phase one</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-two"><i class="fa fa-check"></i>Phase two</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-three"><i class="fa fa-check"></i>Phase three</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-four"><i class="fa fa-check"></i>Phase four</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Part I: Continuous outcome variables</b></span></li>
<li class="chapter" data-level="2" data-path="rct-plan.html"><a href="rct-plan.html"><i class="fa fa-check"></i><b>2</b> Sample size for a normally distributed primary outcome variable</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rct-plan.html"><a href="rct-plan.html#the-treatment-effect"><i class="fa fa-check"></i><b>2.1</b> The treatment effect</a></li>
<li class="chapter" data-level="2.2" data-path="rct-plan.html"><a href="rct-plan.html#reminder-hypothesis-tests-with-a-focus-on-rcts"><i class="fa fa-check"></i><b>2.2</b> Reminder: hypothesis tests (with a focus on RCTs)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="rct-plan.html"><a href="rct-plan.html#insignificant-results"><i class="fa fa-check"></i><b>2.2.1</b> Insignificant results</a></li>
<li class="chapter" data-level="2.2.2" data-path="rct-plan.html"><a href="rct-plan.html#one-tailed-or-two-tailed"><i class="fa fa-check"></i><b>2.2.2</b> One-tailed or two-tailed?</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="rct-plan.html"><a href="rct-plan.html#sec-measDcont"><i class="fa fa-check"></i><b>2.3</b> Constructing a measure of effect size</a></li>
<li class="chapter" data-level="2.4" data-path="rct-plan.html"><a href="rct-plan.html#sec-power"><i class="fa fa-check"></i><b>2.4</b> Power: If <span class="math inline">\(H_0\)</span> is false</a></li>
<li class="chapter" data-level="2.5" data-path="rct-plan.html"><a href="rct-plan.html#sec-ssformulacont"><i class="fa fa-check"></i><b>2.5</b> A sample size formula</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="alloc.html"><a href="alloc.html"><i class="fa fa-check"></i><b>3</b> Allocation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="alloc.html"><a href="alloc.html#bias"><i class="fa fa-check"></i><b>3.1</b> Bias</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="alloc.html"><a href="alloc.html#where-does-bias-come-from"><i class="fa fa-check"></i><b>3.1.1</b> Where does bias come from?</a></li>
<li class="chapter" data-level="3.1.2" data-path="alloc.html"><a href="alloc.html#implications-for-allocation"><i class="fa fa-check"></i><b>3.1.2</b> Implications for allocation</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="alloc.html"><a href="alloc.html#sec-allocation"><i class="fa fa-check"></i><b>3.2</b> Allocation methods</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="alloc.html"><a href="alloc.html#simple-random-allocation"><i class="fa fa-check"></i><b>3.2.1</b> Simple random allocation</a></li>
<li class="chapter" data-level="3.2.2" data-path="alloc.html"><a href="alloc.html#random-permuted-blocks"><i class="fa fa-check"></i><b>3.2.2</b> Random permuted blocks</a></li>
<li class="chapter" data-level="3.2.3" data-path="alloc.html"><a href="alloc.html#bcurn"><i class="fa fa-check"></i><b>3.2.3</b> Biased coin designs and urn schemes</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="alloc.html"><a href="alloc.html#incorporating-baseline-measurements"><i class="fa fa-check"></i><b>3.3</b> Incorporating baseline measurements</a></li>
<li class="chapter" data-level="3.4" data-path="alloc.html"><a href="alloc.html#stratified-sampling"><i class="fa fa-check"></i><b>3.4</b> Stratified sampling</a></li>
<li class="chapter" data-level="3.5" data-path="alloc.html"><a href="alloc.html#minimization"><i class="fa fa-check"></i><b>3.5</b> Minimization</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="alloc.html"><a href="alloc.html#minimization-algorithm"><i class="fa fa-check"></i><b>3.5.1</b> Minimization algorithm</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="alloc.html"><a href="alloc.html#problems-around-allocation"><i class="fa fa-check"></i><b>3.6</b> Problems around allocation</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rct-analysis.html"><a href="rct-analysis.html"><i class="fa fa-check"></i><b>4</b> Analyzing RCT data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="rct-analysis.html"><a href="rct-analysis.html#ttest"><i class="fa fa-check"></i><b>4.1</b> Confidence intervals and P-values</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="rct-analysis.html"><a href="rct-analysis.html#what-do-we-do-with-this-outcome"><i class="fa fa-check"></i><b>4.1.1</b> What do we do with this outcome?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="rct-analysis.html"><a href="rct-analysis.html#baseline"><i class="fa fa-check"></i><b>4.2</b> Using baseline values</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="rct-analysis.html"><a href="rct-analysis.html#a-dodgy-way-to-use-baseline-variables"><i class="fa fa-check"></i><b>4.2.1</b> A dodgy way to use baseline variables</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="rct-analysis.html"><a href="rct-analysis.html#analysis-of-covariance-ancova"><i class="fa fa-check"></i><b>4.3</b> Analysis of covariance (ANCOVA)</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="rct-analysis.html"><a href="rct-analysis.html#ancovatheory"><i class="fa fa-check"></i><b>4.3.1</b> The theory</a></li>
<li class="chapter" data-level="4.3.2" data-path="rct-analysis.html"><a href="rct-analysis.html#ancova-practice"><i class="fa fa-check"></i><b>4.3.2</b> The practice</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="rct-analysis.html"><a href="rct-analysis.html#some-follow-up-questions."><i class="fa fa-check"></i><b>4.4</b> Some follow-up questions….</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="rct-analysis.html"><a href="rct-analysis.html#didnt-we-say-that-x_t---x_c-was-an-unbiased-estimator-of-tau"><i class="fa fa-check"></i><b>4.4.1</b> Didn’t we say that <span class="math inline">\(X_T - X_C\)</span> was an unbiased estimator of <span class="math inline">\(\tau\)</span>?</a></li>
<li class="chapter" data-level="4.4.2" data-path="rct-analysis.html"><a href="rct-analysis.html#what-if-the-lines-shouldnt-be-parallel-the-unequal-slopes-model"><i class="fa fa-check"></i><b>4.4.2</b> What if the lines shouldn’t be parallel? The unequal slopes model</a></li>
<li class="chapter" data-level="4.4.3" data-path="rct-analysis.html"><a href="rct-analysis.html#can-we-include-any-other-baseline-covariates"><i class="fa fa-check"></i><b>4.4.3</b> Can we include any other baseline covariates?</a></li>
<li class="chapter" data-level="" data-path="rct-analysis.html"><a href="rct-analysis.html#an-important-caution"><i class="fa fa-check"></i>An important caution!</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Part II: Binary outcome variable</b></span></li>
<li class="chapter" data-level="5" data-path="ss-bin.html"><a href="ss-bin.html"><i class="fa fa-check"></i><b>5</b> Sample size for a binary variable</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ss-bin.html"><a href="ss-bin.html#delta-method"><i class="fa fa-check"></i><b>5.1</b> The Delta Method</a></li>
<li class="chapter" data-level="5.2" data-path="ss-bin.html"><a href="ss-bin.html#a-sample-size-formula"><i class="fa fa-check"></i><b>5.2</b> A sample size formula</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="binary-analysis.html"><a href="binary-analysis.html"><i class="fa fa-check"></i><b>6</b> Analysis for binary outcomes</a>
<ul>
<li class="chapter" data-level="6.1" data-path="binary-analysis.html"><a href="binary-analysis.html#point-estimates-and-hypothesis-tests"><i class="fa fa-check"></i><b>6.1</b> Point estimates and Hypothesis tests</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="binary-analysis.html"><a href="binary-analysis.html#an-alternative-approach-chi-squared"><i class="fa fa-check"></i><b>6.1.1</b> An alternative approach: chi-squared</a></li>
<li class="chapter" data-level="6.1.2" data-path="binary-analysis.html"><a href="binary-analysis.html#likelihood-a-more-rigorous-way"><i class="fa fa-check"></i><b>6.1.2</b> Likelihood: A more rigorous way</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="binary-analysis.html"><a href="binary-analysis.html#measures-of-difference-for-binary-data"><i class="fa fa-check"></i><b>6.2</b> Measures of difference for binary data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="binary-analysis.html"><a href="binary-analysis.html#ard-and-nnt"><i class="fa fa-check"></i><b>6.2.1</b> Absolute risk difference and Number Needed to Treat</a></li>
<li class="chapter" data-level="6.2.2" data-path="binary-analysis.html"><a href="binary-analysis.html#risk-ratio-rr-and-odds-ratio-or"><i class="fa fa-check"></i><b>6.2.2</b> Risk Ratio (RR) and Odds ratio (OR)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="binary-analysis.html"><a href="binary-analysis.html#logreg"><i class="fa fa-check"></i><b>6.3</b> Accounting for baseline observations: logistic regression</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="binary-analysis.html"><a href="binary-analysis.html#what-does-this-model-tell-us"><i class="fa fa-check"></i><b>6.3.1</b> What does this model tell us?</a></li>
<li class="chapter" data-level="6.3.2" data-path="binary-analysis.html"><a href="binary-analysis.html#fitting-a-logistic-regression-model"><i class="fa fa-check"></i><b>6.3.2</b> Fitting a logistic regression model</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="binary-analysis.html"><a href="binary-analysis.html#diaglogreg"><i class="fa fa-check"></i><b>6.4</b> Diagnostics for logistic regression</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="binary-analysis.html"><a href="binary-analysis.html#discrimination"><i class="fa fa-check"></i><b>6.4.1</b> Discrimination</a></li>
<li class="chapter" data-level="6.4.2" data-path="binary-analysis.html"><a href="binary-analysis.html#calibration"><i class="fa fa-check"></i><b>6.4.2</b> Calibration</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Part III: Survival data</b></span></li>
<li class="chapter" data-level="7" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html"><i class="fa fa-check"></i><b>7</b> Working with time-to-event data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#censored-times"><i class="fa fa-check"></i><b>7.1</b> Censored times</a></li>
<li class="chapter" data-level="7.2" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#survhaz"><i class="fa fa-check"></i><b>7.2</b> The Survival Curve and the Hazard function</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#the-kaplan-meier-estimator"><i class="fa fa-check"></i><b>7.2.1</b> The Kaplan-Meier estimator</a></li>
<li class="chapter" data-level="7.2.2" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#a-parametric-approach"><i class="fa fa-check"></i><b>7.2.2</b> A parametric approach</a></li>
<li class="chapter" data-level="7.2.3" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#weibull"><i class="fa fa-check"></i><b>7.2.3</b> The Weibull distribution</a></li>
<li class="chapter" data-level="" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#aside-sample-size-calculations-for-time-to-event-data"><i class="fa fa-check"></i>Aside: Sample size calculations for time-to-event data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html"><i class="fa fa-check"></i><b>8</b> Comparing survival curves</a>
<ul>
<li class="chapter" data-level="8.1" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#survlrtest"><i class="fa fa-check"></i><b>8.1</b> Parametric: likelihood ratio test</a></li>
<li class="chapter" data-level="8.2" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#non-parametric-the-log-rank-test"><i class="fa fa-check"></i><b>8.2</b> Non-parametric: the log-rank test</a></li>
<li class="chapter" data-level="8.3" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#semi-parametric-the-proportional-hazards-model"><i class="fa fa-check"></i><b>8.3</b> Semi-parametric: the proportional hazards model</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#general-proportional-hazards-model"><i class="fa fa-check"></i><b>8.3.1</b> General proportional hazards model</a></li>
<li class="chapter" data-level="8.3.2" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#coxreg"><i class="fa fa-check"></i><b>8.3.2</b> Cox regression</a></li>
<li class="chapter" data-level="" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#how-can-we-tell-if-a-proportional-hazards-model-is-appropriate"><i class="fa fa-check"></i>How can we tell if a proportional hazards model is appropriate?</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Part III: Further designs</b></span></li>
<li class="chapter" data-level="9" data-path="cluster-rct.html"><a href="cluster-rct.html"><i class="fa fa-check"></i><b>9</b> Cluster randomised trials</a>
<ul>
<li class="chapter" data-level="9.1" data-path="cluster-rct.html"><a href="cluster-rct.html#what-is-a-cluster-rct"><i class="fa fa-check"></i><b>9.1</b> What is a cluster RCT?</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="cluster-rct.html"><a href="cluster-rct.html#intracluster-correlation"><i class="fa fa-check"></i><b>9.1.1</b> Intracluster correlation</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="cluster-rct.html"><a href="cluster-rct.html#sample-size"><i class="fa fa-check"></i><b>9.2</b> Sample size</a></li>
<li class="chapter" data-level="9.3" data-path="cluster-rct.html"><a href="cluster-rct.html#allocation"><i class="fa fa-check"></i><b>9.3</b> Allocation</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="cluster-rct.html"><a href="cluster-rct.html#allocating-everyone-at-once"><i class="fa fa-check"></i><b>9.3.1</b> Allocating everyone at once</a></li>
<li class="chapter" data-level="9.3.2" data-path="cluster-rct.html"><a href="cluster-rct.html#covariate-constrained-randomization"><i class="fa fa-check"></i><b>9.3.2</b> Covariate constrained randomization</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="cluster-rct.html"><a href="cluster-rct.html#analysing-a-cluster-rct"><i class="fa fa-check"></i><b>9.4</b> Analysing a cluster RCT</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="cluster-rct.html"><a href="cluster-rct.html#at-the-cluster-level"><i class="fa fa-check"></i><b>9.4.1</b> At the cluster level</a></li>
<li class="chapter" data-level="9.4.2" data-path="cluster-rct.html"><a href="cluster-rct.html#at-the-individual-level-mixed-effects-models"><i class="fa fa-check"></i><b>9.4.2</b> At the individual level: mixed effects models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html"><i class="fa fa-check"></i><b>10</b> Random effects for individuals</a>
<ul>
<li class="chapter" data-level="10.1" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#crossover-trials"><i class="fa fa-check"></i><b>10.1</b> Crossover trials</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#the-abba-design"><i class="fa fa-check"></i><b>10.1.1</b> The AB/BA design</a></li>
<li class="chapter" data-level="10.1.2" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#analysis-of-the-abba-design"><i class="fa fa-check"></i><b>10.1.2</b> Analysis of the AB/BA design</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#longitudinal-data-repeated-measurements"><i class="fa fa-check"></i><b>10.2</b> Longitudinal data / repeated measurements</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#fitting-a-model"><i class="fa fa-check"></i><b>10.2.1</b> Fitting a model</a></li>
<li class="chapter" data-level="10.2.2" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#the-empty-model"><i class="fa fa-check"></i><b>10.2.2</b> The empty model</a></li>
<li class="chapter" data-level="" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html"><i class="fa fa-check"></i><b>11</b> The Bayesian Approach</a></li>
<li class="appendix"><span><b>Computer practicals</b></span></li>
<li class="chapter" data-level="A" data-path="computer-practical-1.html"><a href="computer-practical-1.html"><i class="fa fa-check"></i><b>A</b> Computer Practical 1</a>
<ul>
<li class="chapter" data-level="" data-path="computer-practical-1.html"><a href="computer-practical-1.html#health-warning"><i class="fa fa-check"></i>Health warning!</a>
<ul>
<li class="chapter" data-level="" data-path="computer-practical-1.html"><a href="computer-practical-1.html#preliminaries"><i class="fa fa-check"></i>Preliminaries</a></li>
<li class="chapter" data-level="" data-path="computer-practical-1.html"><a href="computer-practical-1.html#r-practicalities"><i class="fa fa-check"></i>R practicalities</a></li>
</ul></li>
<li class="chapter" data-level="A.1" data-path="computer-practical-1.html"><a href="computer-practical-1.html#cp1allocation"><i class="fa fa-check"></i><b>A.1</b> Allocation</a>
<ul>
<li class="chapter" data-level="A.1.1" data-path="computer-practical-1.html"><a href="computer-practical-1.html#licorice-gargle-dataset"><i class="fa fa-check"></i><b>A.1.1</b> Licorice gargle dataset</a></li>
<li class="chapter" data-level="A.1.2" data-path="computer-practical-1.html"><a href="computer-practical-1.html#allocmethods"><i class="fa fa-check"></i><b>A.1.2</b> Allocation methods</a></li>
<li class="chapter" data-level="A.1.3" data-path="computer-practical-1.html"><a href="computer-practical-1.html#stratifying-the-dataset"><i class="fa fa-check"></i><b>A.1.3</b> Stratifying the dataset</a></li>
<li class="chapter" data-level="A.1.4" data-path="computer-practical-1.html"><a href="computer-practical-1.html#minimisation"><i class="fa fa-check"></i><b>A.1.4</b> Minimisation</a></li>
<li class="chapter" data-level="A.1.5" data-path="computer-practical-1.html"><a href="computer-practical-1.html#a-simulation-experiment"><i class="fa fa-check"></i><b>A.1.5</b> A simulation experiment!</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="computer-practical-1.html"><a href="computer-practical-1.html#cp1analysis"><i class="fa fa-check"></i><b>A.2</b> Analysis</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="computer-practical-1.html"><a href="computer-practical-1.html#polyps-data"><i class="fa fa-check"></i><b>A.2.1</b> Polyps data</a></li>
<li class="chapter" data-level="A.2.2" data-path="computer-practical-1.html"><a href="computer-practical-1.html#treatment-for-maternal-periodontal-disease"><i class="fa fa-check"></i><b>A.2.2</b> Treatment for maternal periodontal disease</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Clinical Trials 4H</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="random-effects-for-individuals" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">10</span> Random effects for individuals<a href="random-effects-for-individuals.html#random-effects-for-individuals" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In the last lecture we introduced the mixed effects model as a way to combine fixed effects (the kind we’re used to, like sex, disease status etc.) and random effects. For cluster randomized trials this was useful because we could account for the intracluster correlation, where participants within the same school / GP surgery / other cluster are likely to be more similar to one another than to participants within another group.</p>
<p>In this lecture, we’ll think about a couple of examples where the individual is the random effect.</p>
<div id="crossover-trials" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Crossover trials<a href="random-effects-for-individuals.html#crossover-trials" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the trials we’ve thought about so far, each patient has been subject to one, and only one, treatment. Often this is necessary, because the end goal is something relatively final, like a disease being cured, or the circumstance is a one-off, like medication to prevent complications of surgery. By doing things this way, we lose the opportunity to make direct comparisons; we assume that all participants are randomly drawn from some population, and make efforts to ensure the trial is balanced in terms of their characteristics, but we can’t truly compare like-for-like.</p>
<p>Crossover trials, also known as AB or AB/BA trials, involve giving each participant both treatments in sequence. These are generally used in contexts where the goal is ongoing management of a condition, for example asthma or diabetes. If we give each participant each of the different treatments in sequence, then we can make a more precise comparison, since we are comparing the outcomes under the different treatments <em>on the same patient</em>. You can find more detail of this type of trial in <span class="citation">Armitage and Hills (<a href="#ref-armitage1982two">1982</a>)</span>.</p>
<div id="the-abba-design" class="section level3 hasAnchor" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> The AB/BA design<a href="random-effects-for-individuals.html#the-abba-design" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we gave all patients treatment A first (say for one month) and then treatment B (for the next), then we would be inviting bias and ambiguity into the trial</p>
<ul>
<li>It may be that whichever treatment comes second appears to perform better, for example as patients get used to measurements being taken (it is common for the first few blood pressure measurements in a series to be higher)</li>
<li>If there is some external trend or pattern, this will manifest itself as an effect of the change in treatments.</li>
</ul>
<p>Therefore in a crossover trial with two treatments there are two groups, who receive the treatments in different orders:</p>
<table>
<thead>
<tr class="header">
<th align="left">Group</th>
<th align="left">Period 1</th>
<th align="left">Period 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>Group 1</strong></td>
<td align="left">A</td>
<td align="left">B</td>
</tr>
<tr class="even">
<td align="left"><strong>Group 2</strong></td>
<td align="left">B</td>
<td align="left">A</td>
</tr>
</tbody>
</table>
<p>Therefore if there is a temporal effect it won’t be ascribed to either of the treatments.</p>
</div>
<div id="analysis-of-the-abba-design" class="section level3 hasAnchor" number="10.1.2">
<h3><span class="header-section-number">10.1.2</span> Analysis of the AB/BA design<a href="random-effects-for-individuals.html#analysis-of-the-abba-design" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are a few things our analysis needs to account for:</p>
<ul>
<li>Measurements for the same participant need to be treated as such, in some way</li>
<li>The possibility of systematic differences between treatment periods needs to be allowed for</li>
</ul>
<p>In the model we describe, we assume there are <span class="math inline">\(n_1\)</span> participants in group 1, and <span class="math inline">\(n_2\)</span> in group 2. We will also assume that the outcome is normally distributed. In the treatment of ongoing conditions, this is generally the case.</p>
<p>We will start by thinking about the outcome for particular individuals. We’ll assume that one outcome measurement is taken per patient per trial period. So the outcome for participant <span class="math inline">\(i\)</span> <span class="math inline">\((i = 1,\ldots,n_1)\)</span> from group 1 is modelled by</p>
<p><span class="math display">\[\begin{align*}
x_{i1} &amp; = \mu + \pi_1 + \tau_A + \xi_i + \epsilon_{i1} \text{ in trial period 1}\\
x_{i2} &amp; = \mu + \pi_2 + \tau_B + \xi_i + \epsilon_{i2} \text{ in trial period 2.}
\end{align*}\]</span></p>
<p>In this model</p>
<ul>
<li><span class="math inline">\(\pi_j\;\;(j=1,2)\)</span> is the systematic effect of period <span class="math inline">\(j\)</span></li>
<li><span class="math inline">\(\tau_A,\,\tau_B\)</span> are the systematic effects of treatments A and B</li>
<li><span class="math inline">\(\mu\)</span> is a general mean</li>
<li><span class="math inline">\(\xi_i\)</span> represents the tendency for the outcome of participant <span class="math inline">\(i\)</span> to be generally higher or lower than the mean</li>
<li><span class="math inline">\(\epsilon_{i1},\,\epsilon_{i2}\)</span> are independent <span class="math inline">\(N\left(0,\,\sigma_{\epsilon}^2\right)\)</span> error terms.</li>
</ul>
<p>Notice that the first three bullet points describe fixed effects, and the fourth <span class="math inline">\((\xi_i)\)</span> is a random effect. We can assume that <span class="math inline">\(\xi_i \sim N\left(0,\,\sigma_B^2\right)\)</span>. Notice that <span class="math inline">\(\xi_i\)</span> appears in the outcome model for participant <span class="math inline">\(i\)</span> for both trial periods.</p>
<p>We can us the same logic to model the outcome for participant <span class="math inline">\(i\)</span> <span class="math inline">\(\left(i=n_1+1,\,\ldots,\,n_1+n_2\right)\)</span> in group 2</p>
<p><span class="math display">\[\begin{align*}
x_{i1} &amp; = \mu + \pi_1 + \tau_B + \xi_i + \epsilon_{i1} \text{ in trial period 1}\\
x_{i2} &amp; = \mu + \pi_2 + \tau_A + \xi_i + \epsilon_{i2} \text{ in trial period 2.}
\end{align*}\]</span></p>
<p>Because we have been able to treat each participant with both treatments (A and B), we have effectively bundled all the participant specific covariates, along with individual variation we can’t really account for, into <span class="math inline">\(\xi_i\)</span>.</p>
<p>We can remove <span class="math inline">\(\xi_i\)</span> from from the analysis by finding the differences for each patient</p>
<p><span class="math display">\[\begin{align*}
d_i &amp; = x_{i1} - x_{i2} = \pi + \tau + \eta_i&amp; \text{ for } i=1,\,\ldots,\,n_1\\
d_i &amp; = x_{i1} - x_{i2} = \pi - \tau + \eta_i&amp; \text{ for } i=n_1+1,\,\ldots,\,n_1+n_2,
\end{align*}\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(\pi=\pi_1 - \pi_2\)</span> measures the difference between treatment periods</li>
<li><span class="math inline">\(\tau = \tau_A - \tau_B\)</span> is the treatment effect we are interested in</li>
<li><span class="math inline">\(\eta_i = \epsilon_{i1} - \epsilon_{i2}\)</span> is another random error, with mean 0 and variance <span class="math inline">\(\sigma^2=2\sigma^2_{\epsilon}\)</span></li>
</ul>
<p>We can take expected values of the differences, and find</p>
<p><span class="math display">\[\begin{align*}
\operatorname{E}\left(d\right) &amp; = \pi+\tau &amp; \text{ in group 1}\\
\operatorname{E}\left(d\right) &amp; = \pi-\tau &amp; \text{ in group 2}
\end{align*}\]</span></p>
<p>If there is no treatment effect, ie. <span class="math inline">\(\tau=0\)</span>, then we expect the means to be approximately equal.</p>
<p>This means we can test the null hypothesis that <span class="math inline">\(\tau=0\)</span> with a two-sample <span class="math inline">\(t\)</span>-test, to compare the two sets of within patient differences. Note, this is not a paired t-test: we are comparing the differences for the <span class="math inline">\(n_1\)</span> participants in group 1 with the differences for the <span class="math inline">\(n_2\)</span> participants in group 2.</p>
<p>An estimate of the treatment effect can be found using
<span class="math display">\[\frac{1}{2}\left(\bar{d}_1 - \bar{d}_2\right),\]</span>
where <span class="math inline">\(\bar{d}_k\)</span> is the mean difference in group <span class="math inline">\(k\)</span>. We can therefore find a confidence interval by halving the limits of the usual confidence interval for the difference in two means.</p>
<p>Another important point to note is that since we have eliminated the individual participant random effect <span class="math inline">\(\xi_i\)</span> from the analysis, the precision of the result depends only on <span class="math inline">\(\sigma^2_{\epsilon}\)</span>, and not on the between-individual variance <span class="math inline">\(\sigma^2_B\)</span>. This is especially good news in a scenario in which the measurement varies much more between individuals than within individuals. Intuitively this makes sense: it is best to use a patient as his or her own control.</p>
<div class="example">
<p><span id="exm:unlabeled-div-49" class="example"><strong>Example 10.1  </strong></span>For children with nocturnal enuresis (bed-wetting) a drug is available to potentially alleviate the problem, and in this trial the drug is to be compared with a placebo, and the treatment period is two weeks. Children in group A are given the drug first, followed by the placebo. Children in group B are given the placebo first, followed by the drug. The primary outcome variable is the number of dry nights out of the 14 night of each treatment period. The data are shown in Table <a href="random-effects-for-individuals.html#tab:enuresisdata">10.1</a>.</p>
<table class="kable_wrapper">
<caption>
<span id="tab:enuresisdata">Table 10.1: </span>Data for group A (left) and group B (right)
</caption>
<tbody>
<tr>
<td>
<table>
<thead>
<tr class="header">
<th align="right">Period1</th>
<th align="right">Period2</th>
<th align="right">Diff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">8</td>
<td align="right">5</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="right">10</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="right">0</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="right">9</td>
<td align="right">7</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">6</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="right">5</td>
<td align="right">-2</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="right">12</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">2</td>
<td align="right">8</td>
</tr>
<tr class="odd">
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">5</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">13</td>
<td align="right">13</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="right">10</td>
<td align="right">-2</td>
</tr>
<tr class="even">
<td align="right">7</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">0</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">6</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</td>
<td>
<table>
<thead>
<tr class="header">
<th align="right">Period1</th>
<th align="right">Period2</th>
<th align="right">Diff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">12</td>
<td align="right">11</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">8</td>
<td align="right">-2</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="right">9</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="right">9</td>
<td align="right">-1</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">8</td>
<td align="right">-4</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="right">14</td>
<td align="right">-6</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">4</td>
<td align="right">-2</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="right">13</td>
<td align="right">-5</td>
</tr>
<tr class="even">
<td align="right">9</td>
<td align="right">7</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">10</td>
<td align="right">-3</td>
</tr>
<tr class="even">
<td align="right">7</td>
<td align="right">6</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<p>We can use this information to find the mean difference for each group</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="random-effects-for-individuals.html#cb94-1" tabindex="-1"></a><span class="fu">mean</span>(dfA<span class="sc">$</span>Diff)</span></code></pre></div>
<pre><code>## [1] 2.823529</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="random-effects-for-individuals.html#cb96-1" tabindex="-1"></a><span class="fu">mean</span>(dfB<span class="sc">$</span>Diff)</span></code></pre></div>
<pre><code>## [1] -1.25</code></pre>
<p>Immediately we can see that these back up the notion that the drug is effective (remember the difference for group A is drug minus placebo, the difference for group B is placebo minus drug), and that the number of dry nights tends to be more while taking the drug.</p>
<p>To test the hypothesis more carefully we use a t-test.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="random-effects-for-individuals.html#cb98-1" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x=</span>dfA<span class="sc">$</span>Diff, <span class="at">y=</span>dfB<span class="sc">$</span>Diff, <span class="at">paired=</span>F, <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">var.equal=</span>T)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  dfA$Diff and dfB$Diff
## t = 3.2925, df = 27, p-value = 0.002773
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  1.535005 6.612054
## sample estimates:
## mean of x mean of y 
##  2.823529 -1.250000</code></pre>
<p>We see that this backs up the hypothesis that the drug reduces nocturnal enuresis.</p>
<p>We could analyse the same dataset without taking into account the crossover design of the trial, simply by performing a t-test of all measurements on the drug against all measurement on the placebo</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="random-effects-for-individuals.html#cb100-1" tabindex="-1"></a>drug_meas <span class="ot">=</span> <span class="fu">c</span>(dfA<span class="sc">$</span>Period1,dfB<span class="sc">$</span>Period2)      <span class="co"># Measurements taken while on drug</span></span>
<span id="cb100-2"><a href="random-effects-for-individuals.html#cb100-2" tabindex="-1"></a>placebo_meas <span class="ot">=</span> <span class="fu">c</span>(dfA<span class="sc">$</span>Period2, dfB<span class="sc">$</span>Period1)  <span class="co"># Measurements taken while on placebo</span></span>
<span id="cb100-3"><a href="random-effects-for-individuals.html#cb100-3" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb100-4"><a href="random-effects-for-individuals.html#cb100-4" tabindex="-1"></a>  <span class="at">x=</span>drug_meas, <span class="at">y=</span>placebo_meas, </span>
<span id="cb100-5"><a href="random-effects-for-individuals.html#cb100-5" tabindex="-1"></a>  <span class="at">paired=</span>F, <span class="at">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="at">var.equal=</span>T)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  drug_meas and placebo_meas
## t = 2.253, df = 56, p-value = 0.0282
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.2408072 4.1040204
## sample estimates:
## mean of x mean of y 
##  8.448276  6.275862</code></pre>
<p>We see that although the outcome is still significant at the <span class="math inline">\(\alpha=0.05\)</span> level, the p-value is much larger, because the individual effects have not been taken into account.</p>
</div>
</div>
</div>
<div id="longitudinal-data-repeated-measurements" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Longitudinal data / repeated measurements<a href="random-effects-for-individuals.html#longitudinal-data-repeated-measurements" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The second situation we will consider is where there are repeated measurements of the same participant: this is often called <strong>longitudinal data</strong>. So far we have considered only a baseline and final measurement of the outcome variable, but in practice it is common to measure the outcome at several points throughout the trial duration.</p>
<p>Clinicians may want to understand not just how the outcome is behaving at the end of the trial, but how it evolves over time. They may also want to understand the variation in the measurement over time; for example, it is reasonable to expect that a particular patient’s blood presssure or respiratory function won’t be exactly the same every day, even under the same treatment and general conditions.</p>
<p>In general we’ll say that we have two treatment groups, C (control) and T (treatment), containing <span class="math inline">\(n_C\)</span> and <span class="math inline">\(n_T\)</span> participants respectively. The <span class="math inline">\(i^{\text{th}}\)</span> participant in group <span class="math inline">\(X\)</span> is observed <span class="math inline">\(k_{Xi}\)</span> times through the course of the trial. Generally (and we’ll certainly assume here) the measurements are planned to be at the same times.</p>
<div class="example">
<p><span id="exm:epilepsy1" class="example"><strong>Example 10.2  </strong></span>The first data set we’ll introduce is <code>epilepsy</code>, from the package <code>HSAUR3</code>. This trial (detailed in <span class="citation">Thall and Vail (<a href="#ref-thall1990some">1990</a>)</span>) investigates the effect of an anti-epileptic drug called Progabide compared to a placebo (both groups were also receiving chemotherapy). For each patient, the number of seizures was recorded over four contiguous two-week periods.</p>
<p>To visualise the data, we plot a <strong>spaghetti plot</strong>, as shown in Figure <a href="random-effects-for-individuals.html#fig:epispag">10.1</a>. Each line represents a participant, and shows their seizure rate over time.</p>
<div class="figure"><span style="display:block;" id="fig:epispag"></span>
<img src="CT4H_notes_files/figure-html/epispag-1.png" alt="A spaghetti plot of the epilepsy data." width="672" />
<p class="caption">
Figure 10.1: A spaghetti plot of the epilepsy data.
</p>
</div>
<p>We can also plot the mean seizure rate at each time within each group as in Figure <a href="random-effects-for-individuals.html#fig:epimeans">10.2</a></p>
<div class="figure"><span style="display:block;" id="fig:epimeans"></span>
<img src="CT4H_notes_files/figure-html/epimeans-1.png" alt="Mean seizure rate for each treatment group over time." width="672" />
<p class="caption">
Figure 10.2: Mean seizure rate for each treatment group over time.
</p>
</div>
<p>To make visualisation somewhat clearer, can do a standardised spaghetti plot. In this plot, the observations are standardised within each time point. So, if <span class="math inline">\(x_{it}\)</span> is the outcome for participant <span class="math inline">\(i\)</span> and time <span class="math inline">\(t\)</span>, the standardised spaghetti plot would show</p>
<p><span class="math display">\[\frac{x_{it} - \bar{x}_t}{s_t} \]</span></p>
<p>where <span class="math inline">\(\bar{x}_t,\,s_t\)</span> are the sample mean and SD at time <span class="math inline">\(t\)</span>.</p>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-75-1.png" width="672" /></p>
</div>
<div id="fitting-a-model" class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Fitting a model<a href="random-effects-for-individuals.html#fitting-a-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In longitudinal data the measurements are ‘clustered’ within each participant, in a semi-similar way to the participants being clustered within settings in Chapter <a href="cluster-rct.html#cluster-rct">9</a>. Each participant will have certain characteristics that don’t change through the duration of the trial, for example their age (at start), sex, disease history etc. Some of these characteristics we will record as part of the dataset, but this will not fully explain the correlation within measurements of the same participant.</p>
<p>We can also assume that, given the values of these covariates, the outcome of each participant has a slight (or mabye more than slight) propensity to be consistently either higher or lower than (or perhaps to be in line with) the mean. Therefore there will be a random effect associated with each participant. Because we are interested in how things evolve with time, we will also include time in the model.</p>
<p>The questions we want to answer are:</p>
<ul>
<li>What is the effect of the covariates (including treatment group) on the outcome?</li>
<li>What is the effect of time on the outcome?</li>
<li>Does the relationship between outcome and time vary for different groups of individuals?</li>
</ul>
</div>
<div id="the-empty-model" class="section level3 hasAnchor" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> The empty model<a href="random-effects-for-individuals.html#the-empty-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The very simplest mixed effects model we can fit is</p>
<p><span class="math display" id="eq:lmer0">\[\begin{equation}
Y_{ij} = \beta_0 + u_{i} + \epsilon_{ij}.
\tag{10.1}
\end{equation}\]</span></p>
<p>In this model, <span class="math inline">\(Y_{ij}\)</span> is the outcome for the <span class="math inline">\(i^{th}\)</span> participant at time <span class="math inline">\(j\)</span>, <span class="math inline">\(\beta_0\)</span> is a fixed effect representing the overall mean of the <span class="math inline">\(Y_{ij}\)</span>, <span class="math inline">\(u_i\)</span> is the adjustment for the mean for participant <span class="math inline">\(i\)</span> and <span class="math inline">\(\epsilon_{ij}\)</span> is the residual. In this model we assume:</p>
<p><span class="math display">\[\begin{align*}
u_{i} &amp; \sim N\left(0,\,\sigma^2_{u}\right)\\
\epsilon_{ij}&amp; \sim N\left(0,\,\sigma^2\right)\\
u_i&amp;\perp \epsilon_{ij}.
\end{align*}\]</span></p>
<p>This model is actually a one-way analysis of variance (ANOVA) model.</p>
<div class="example">
<p><span id="exm:unlabeled-div-50" class="example"><strong>Example 10.3  </strong></span>We can fit the empty model for the <code>epilepsy</code> data via</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="random-effects-for-individuals.html#cb102-1" tabindex="-1"></a>epi_0 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(seizure.rate <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject), <span class="at">data =</span> epilepsy)</span>
<span id="cb102-2"><a href="random-effects-for-individuals.html#cb102-2" tabindex="-1"></a><span class="fu">summary</span>(epi_0)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: seizure.rate ~ 1 + (1 | subject)
##    Data: epilepsy
## 
## REML criterion at convergence: 1651.1
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.8126 -0.3264 -0.0797  0.1725  7.3634 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  subject  (Intercept) 121.75   11.03   
##  Residual              32.49    5.70   
## Number of obs: 236, groups:  subject, 59
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)    8.263      1.484   5.569</code></pre>
<p>The estimated average <code>seizure.rate</code> is shown in the <code>Fixed effects</code> section, and is 8.263. The estimated variance of the individual random effect term (<span class="math inline">\(u_i\)</span> above) is 121.75, and the estimated residual variance is 32.49. These are both given in the <code>Random effects</code> section of the summary. We can use these values to estimate the ICC, which is now the correlation between repeated measures of the same individual:</p>
<p><span class="math display">\[\rho_{ICC} = \frac{s^2_B}{s^2_B + s^2_W} = \frac{121.75}{121.75+32.49} = 0.789.\]</span></p>
<p>This very high value of the ICC supports our choice of fitting a mixed effects model, rather than including only fixed effects.</p>
</div>
<p>Building up the model from this empty model basically involves including more fixed effects and random effects. Since we are concerned with longitudinal data, the obvious first thing to include is time. We can start by including a linear effect of time, so that the model in Equation <a href="random-effects-for-individuals.html#eq:lmer0">(10.1)</a> becomes</p>
<p><span class="math display" id="eq:lmer1">\[\begin{equation}
Y_{ij} = \beta_0 + \gamma t_j + u_{i} + \epsilon_{ij}.
\tag{10.2}
\end{equation}\]</span></p>
<p>So that the coefficient <span class="math inline">\(\gamma\)</span> describes the change in outcome with time.</p>
<p>We might go on to extend the model in Equation <a href="random-effects-for-individuals.html#eq:lmer1">(10.2)</a> by including some baseline covariates <span class="math inline">\(\mathbf{b}_{i}\)</span> for participant <span class="math inline">\(i\)</span> (these would be considered to be the same throughout the trial for participant <span class="math inline">\(i\)</span>). Then our model becomes</p>
<p><span class="math display" id="eq:lmer2">\[\begin{equation}
Y_{ij} = \beta_0 + \gamma t_j + \mathbf{b}_i^T\boldsymbol\beta + u_{i} + \epsilon_{ij}.
\tag{10.3}
\end{equation}\]</span></p>
<p>In Equation <a href="random-effects-for-individuals.html#eq:lmer2">(10.3)</a>, the <span class="math inline">\(\mathbf{b}_i\)</span> are being included as fixed effects, in much the same way we’re used to with linear models, and the corresponding vector of coefficients is <span class="math inline">\(\boldsymbol\beta\)</span>.</p>
<p>We will explore these models by fitting them to our <code>epilepsy</code> data.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="random-effects-for-individuals.html#cb104-1" tabindex="-1"></a><span class="do">## Including just time</span></span>
<span id="cb104-2"><a href="random-effects-for-individuals.html#cb104-2" tabindex="-1"></a>epilepsy<span class="sc">$</span>period <span class="ot">=</span> <span class="fu">as.numeric</span>(epilepsy<span class="sc">$</span>period)</span>
<span id="cb104-3"><a href="random-effects-for-individuals.html#cb104-3" tabindex="-1"></a>epi_1 <span class="ot">=</span> <span class="fu">lmer</span>(seizure.rate <span class="sc">~</span> period <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>subject), <span class="at">data=</span>epilepsy)</span>
<span id="cb104-4"><a href="random-effects-for-individuals.html#cb104-4" tabindex="-1"></a></span>
<span id="cb104-5"><a href="random-effects-for-individuals.html#cb104-5" tabindex="-1"></a><span class="do">## Including more baseline covariates</span></span>
<span id="cb104-6"><a href="random-effects-for-individuals.html#cb104-6" tabindex="-1"></a>epi_2 <span class="ot">=</span> <span class="fu">lmer</span>(seizure.rate <span class="sc">~</span> base <span class="sc">+</span> age <span class="sc">+</span> treatment <span class="sc">+</span> period <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>subject), <span class="at">data=</span>epilepsy)</span>
<span id="cb104-7"><a href="random-effects-for-individuals.html#cb104-7" tabindex="-1"></a></span>
<span id="cb104-8"><a href="random-effects-for-individuals.html#cb104-8" tabindex="-1"></a>pm1 <span class="ot">=</span> <span class="fu">plot_model</span>(epi_1)</span>
<span id="cb104-9"><a href="random-effects-for-individuals.html#cb104-9" tabindex="-1"></a>pm2 <span class="ot">=</span> <span class="fu">plot_model</span>(epi_2)</span>
<span id="cb104-10"><a href="random-effects-for-individuals.html#cb104-10" tabindex="-1"></a><span class="fu">grid.arrange</span>(pm1, pm2, <span class="at">nrow=</span><span class="dv">1</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-77"></span>
<img src="CT4H_notes_files/figure-html/unnamed-chunk-77-1.png" alt="Confidence intervals for fixed effects for the two fitted models." width="672" />
<p class="caption">
Figure 10.3: Confidence intervals for fixed effects for the two fitted models.
</p>
</div>
<p>In this example it appears that neither time nor the treatment have a significant effect on the seizure rate.</p>
<p>The final extension we’ll look at is if we think that different participants might change at different rates, all other things being equal. We can introduce a random effect <span class="math inline">\(\eta_i\)</span> to allow the coefficient of time to vary between participants</p>
<p><span class="math display" id="eq:lmer3">\[\begin{equation}
Y_{ij} = \beta_0 + \left(\gamma + \eta_i\right) t_j + \mathbf{b}_i^T\boldsymbol\beta + u_{i} + \epsilon_{ij}.
\tag{10.4}.
\end{equation}\]</span></p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="random-effects-for-individuals.html#cb105-1" tabindex="-1"></a><span class="do">## Including just time</span></span>
<span id="cb105-2"><a href="random-effects-for-individuals.html#cb105-2" tabindex="-1"></a><span class="do">## Including more baseline covariates</span></span>
<span id="cb105-3"><a href="random-effects-for-individuals.html#cb105-3" tabindex="-1"></a>epi_3 <span class="ot">=</span> <span class="fu">lmer</span>(seizure.rate <span class="sc">~</span> base <span class="sc">+</span> age <span class="sc">+</span> treatment <span class="sc">+</span> period <span class="sc">+</span> (period<span class="sc">|</span>subject), <span class="at">data=</span>epilepsy)</span>
<span id="cb105-4"><a href="random-effects-for-individuals.html#cb105-4" tabindex="-1"></a><span class="fu">summary</span>(epi_3)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: seizure.rate ~ base + age + treatment + period + (period | subject)
##    Data: epilepsy
## 
## REML criterion at convergence: 1581.8
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.8224 -0.3265 -0.0224  0.2306  8.0745 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  subject  (Intercept) 49.0650  7.0046        
##           period       0.2588  0.5088   -1.00
##  Residual             31.8399  5.6427        
## Number of obs: 236, groups:  subject, 59
## 
## Fixed effects:
##                    Estimate Std. Error t value
## (Intercept)        -5.25307    4.45463  -1.179
## base                0.34338    0.03128  10.976
## age                 0.15667    0.13409   1.168
## treatmentProgabide -0.82339    1.64777  -0.500
## period             -0.48475    0.33514  -1.446
## 
## Correlation of Fixed Effects:
##             (Intr) base   age    trtmnP
## base        -0.381                     
## age         -0.914  0.188              
## trtmntPrgbd -0.280  0.004  0.099       
## period      -0.221  0.000  0.000  0.000
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="random-effects-for-individuals.html#cb107-1" tabindex="-1"></a>pm1 <span class="ot">=</span> <span class="fu">plot_model</span>(epi_2)</span>
<span id="cb107-2"><a href="random-effects-for-individuals.html#cb107-2" tabindex="-1"></a>pm2 <span class="ot">=</span> <span class="fu">plot_model</span>(epi_3)</span>
<span id="cb107-3"><a href="random-effects-for-individuals.html#cb107-3" tabindex="-1"></a><span class="fu">grid.arrange</span>(pm1, pm2, <span class="at">nrow=</span><span class="dv">1</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-78"></span>
<img src="CT4H_notes_files/figure-html/unnamed-chunk-78-1.png" alt="Confidence intervals for model with same gradient for all participants (left) and for varying gradient (right)." width="672" />
<p class="caption">
Figure 10.4: Confidence intervals for model with same gradient for all participants (left) and for varying gradient (right).
</p>
</div>
<p>We see from the small variance for the random effect <code>period</code> that the gradients don’t vary very much at all, and indeed the coefficients of the fixed effects are very similar to those for a fixed gradient.</p>
</div>
<div id="summary" class="section level3 unnumbered hasAnchor">
<h3>Summary<a href="random-effects-for-individuals.html#summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In these two lectures we’ve seen that random effects can be a useful way to take care of correlation between outputs for clusters of measurements.</p>
<p>This clustering can be because participants are from some natural group (eg. a school, a family, a hospital) or it can be because repeated measurements are taken of the same participant. In either case, we’d expect the measurements within one cluster to be more highly correlated than those from different clusters.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-armitage1982two" class="csl-entry">
Armitage, Peter, and Michael Hills. 1982. <span>“The Two-Period Crossover Trial.”</span> <em>Journal of the Royal Statistical Society: Series D (The Statistician)</em> 31 (2): 119–31.
</div>
<div id="ref-thall1990some" class="csl-entry">
Thall, Peter F, and Stephen C Vail. 1990. <span>“Some Covariance Models for Longitudinal Count Data with Overdispersion.”</span> <em>Biometrics</em>, 657–71.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="cluster-rct.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="the-bayesian-approach.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["CT4H_notes.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"bookdown": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
