<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Analyzing RCT data | Clinical Trials 4H</title>
  <meta name="description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Analyzing RCT data | Clinical Trials 4H" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Analyzing RCT data | Clinical Trials 4H" />
  
  <meta name="twitter:description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  

<meta name="author" content="Rachel Oughton" />


<meta name="date" content="2023-11-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="the-intervention.html"/>
<link rel="next" href="cluster-rct.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#lectures"><i class="fa fa-check"></i>Lectures</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#computer-classes"><i class="fa fa-check"></i>Computer classes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i>Assessment</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#books"><i class="fa fa-check"></i>Books</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="rct-intro.html"><a href="rct-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction to Clinical Trials</a>
<ul>
<li class="chapter" data-level="1.1" data-path="rct-intro.html"><a href="rct-intro.html#a-brief-history-of-rcts"><i class="fa fa-check"></i><b>1.1</b> A brief history of RCTs</a></li>
<li class="chapter" data-level="1.2" data-path="rct-intro.html"><a href="rct-intro.html#the-structure-of-a-clinical-trial"><i class="fa fa-check"></i><b>1.2</b> The structure of a clinical trial</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="rct-intro.html"><a href="rct-intro.html#primout"><i class="fa fa-check"></i><b>1.2.1</b> The primary outcome</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rct-plan.html"><a href="rct-plan.html"><i class="fa fa-check"></i><b>2</b> Designing and planning a randomised controlled trial (RCT)</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rct-plan.html"><a href="rct-plan.html#ss-norm"><i class="fa fa-check"></i><b>2.1</b> Sample size for a normally distributed primary outcome variable</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="rct-plan.html"><a href="rct-plan.html#the-treatment-effect"><i class="fa fa-check"></i><b>2.1.1</b> The treatment effect</a></li>
<li class="chapter" data-level="2.1.2" data-path="rct-plan.html"><a href="rct-plan.html#reminder-hypothesis-tests-with-a-focus-on-rcts"><i class="fa fa-check"></i><b>2.1.2</b> Reminder: hypothesis tests (with a focus on RCTs)</a></li>
<li class="chapter" data-level="2.1.3" data-path="rct-plan.html"><a href="rct-plan.html#sec-measDcont"><i class="fa fa-check"></i><b>2.1.3</b> Constructing a measure of effect size</a></li>
<li class="chapter" data-level="2.1.4" data-path="rct-plan.html"><a href="rct-plan.html#sec-power"><i class="fa fa-check"></i><b>2.1.4</b> Power: If <span class="math inline">\(H_0\)</span> is false</a></li>
<li class="chapter" data-level="2.1.5" data-path="rct-plan.html"><a href="rct-plan.html#sec-ssformulacont"><i class="fa fa-check"></i><b>2.1.5</b> A sample size formula</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="rct-plan.html"><a href="rct-plan.html#ss-bin"><i class="fa fa-check"></i><b>2.2</b> Sample size for a binary variable</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="rct-plan.html"><a href="rct-plan.html#the-delta-method"><i class="fa fa-check"></i><b>2.2.1</b> The Delta Method</a></li>
<li class="chapter" data-level="2.2.2" data-path="rct-plan.html"><a href="rct-plan.html#a-sample-size-formula"><i class="fa fa-check"></i><b>2.2.2</b> A sample size formula</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="rct-plan.html"><a href="rct-plan.html#sample-size-by-simulation"><i class="fa fa-check"></i><b>2.3</b> Sample size by simulation</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="rct-plan.html"><a href="rct-plan.html#the-simulation-method"><i class="fa fa-check"></i><b>2.3.1</b> The simulation method</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bias.html"><a href="bias.html"><i class="fa fa-check"></i><b>3</b> Bias</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bias.html"><a href="bias.html#where-does-bias-come-from"><i class="fa fa-check"></i><b>3.1</b> Where does bias come from?</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="bias.html"><a href="bias.html#selection-bias"><i class="fa fa-check"></i><b>3.1.1</b> Selection bias</a></li>
<li class="chapter" data-level="3.1.2" data-path="bias.html"><a href="bias.html#allocation-bias"><i class="fa fa-check"></i><b>3.1.2</b> Allocation bias</a></li>
<li class="chapter" data-level="3.1.3" data-path="bias.html"><a href="bias.html#assessment-bias"><i class="fa fa-check"></i><b>3.1.3</b> Assessment bias</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="sec-allocation.html"><a href="sec-allocation.html"><i class="fa fa-check"></i><b>4</b> Allocation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="sec-allocation.html"><a href="sec-allocation.html#allocation-methods"><i class="fa fa-check"></i><b>4.1</b> Allocation methods</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="sec-allocation.html"><a href="sec-allocation.html#simple-random-allocation"><i class="fa fa-check"></i><b>4.1.1</b> Simple random allocation</a></li>
<li class="chapter" data-level="4.1.2" data-path="sec-allocation.html"><a href="sec-allocation.html#random-permuted-blocks"><i class="fa fa-check"></i><b>4.1.2</b> Random permuted blocks</a></li>
<li class="chapter" data-level="4.1.3" data-path="sec-allocation.html"><a href="sec-allocation.html#biased-coin-designs-and-urn-schemes"><i class="fa fa-check"></i><b>4.1.3</b> Biased coin designs and urn schemes</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="sec-allocation.html"><a href="sec-allocation.html#problems-with-allocation"><i class="fa fa-check"></i><b>4.2</b> Problems with allocation</a></li>
<li class="chapter" data-level="4.3" data-path="sec-allocation.html"><a href="sec-allocation.html#stratified-sampling"><i class="fa fa-check"></i><b>4.3</b> Stratified sampling</a></li>
<li class="chapter" data-level="4.4" data-path="sec-allocation.html"><a href="sec-allocation.html#minimization"><i class="fa fa-check"></i><b>4.4</b> Minimization</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="sec-allocation.html"><a href="sec-allocation.html#minimization-algorithm"><i class="fa fa-check"></i><b>4.4.1</b> Minimization algorithm</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="sec-allocation.html"><a href="sec-allocation.html#some-simulated-examples"><i class="fa fa-check"></i><b>4.5</b> Some simulated examples</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="sec-allocation.html"><a href="sec-allocation.html#simple-random-allocation-1"><i class="fa fa-check"></i><b>4.5.1</b> Simple random allocation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="the-intervention.html"><a href="the-intervention.html"><i class="fa fa-check"></i><b>5</b> The intervention</a></li>
<li class="chapter" data-level="6" data-path="rct-analysis.html"><a href="rct-analysis.html"><i class="fa fa-check"></i><b>6</b> Analyzing RCT data</a>
<ul>
<li class="chapter" data-level="6.1" data-path="rct-analysis.html"><a href="rct-analysis.html#confidence-intervals-and-p-values"><i class="fa fa-check"></i><b>6.1</b> Confidence intervals and P-values</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="rct-analysis.html"><a href="rct-analysis.html#bonferroni-correction"><i class="fa fa-check"></i><b>6.1.1</b> Bonferroni correction</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="rct-analysis.html"><a href="rct-analysis.html#baseline"><i class="fa fa-check"></i><b>6.2</b> Using baseline values</a></li>
<li class="chapter" data-level="6.3" data-path="rct-analysis.html"><a href="rct-analysis.html#analysis-of-covariance-ancova"><i class="fa fa-check"></i><b>6.3</b> Analysis of covariance (ANCOVA)</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="rct-analysis.html"><a href="rct-analysis.html#the-theory"><i class="fa fa-check"></i><b>6.3.1</b> The theory</a></li>
<li class="chapter" data-level="6.3.2" data-path="rct-analysis.html"><a href="rct-analysis.html#the-practice"><i class="fa fa-check"></i><b>6.3.2</b> The practice</a></li>
<li class="chapter" data-level="6.3.3" data-path="rct-analysis.html"><a href="rct-analysis.html#a-few-cautions"><i class="fa fa-check"></i><b>6.3.3</b> A few cautions</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="rct-analysis.html"><a href="rct-analysis.html#binary-data"><i class="fa fa-check"></i><b>6.4</b> Binary data</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="rct-analysis.html"><a href="rct-analysis.html#confidence-intervals-for-binary-data"><i class="fa fa-check"></i><b>6.4.1</b> Confidence intervals for binary data</a></li>
<li class="chapter" data-level="6.4.2" data-path="rct-analysis.html"><a href="rct-analysis.html#using-baseline-measurements"><i class="fa fa-check"></i><b>6.4.2</b> Using baseline measurements</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="rct-analysis.html"><a href="rct-analysis.html#categorical-data"><i class="fa fa-check"></i><b>6.5</b> Categorical data?</a></li>
<li class="chapter" data-level="6.6" data-path="rct-analysis.html"><a href="rct-analysis.html#survival-data"><i class="fa fa-check"></i><b>6.6</b> Survival data</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="cluster-rct.html"><a href="cluster-rct.html"><i class="fa fa-check"></i><b>7</b> Cluster randomised controlled trials</a>
<ul>
<li class="chapter" data-level="7.1" data-path="cluster-rct.html"><a href="cluster-rct.html#what-is-a-cluster-rct"><i class="fa fa-check"></i><b>7.1</b> What is a cluster RCT?</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="cluster-rct.html"><a href="cluster-rct.html#intracluster-correlation"><i class="fa fa-check"></i><b>7.1.1</b> Intracluster correlation</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="cluster-rct.html"><a href="cluster-rct.html#designing-a-cluster-rct"><i class="fa fa-check"></i><b>7.2</b> Designing a cluster RCT</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="cluster-rct.html"><a href="cluster-rct.html#sample-size"><i class="fa fa-check"></i><b>7.2.1</b> Sample size</a></li>
<li class="chapter" data-level="7.2.2" data-path="cluster-rct.html"><a href="cluster-rct.html#allocation"><i class="fa fa-check"></i><b>7.2.2</b> Allocation</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="cluster-rct.html"><a href="cluster-rct.html#allocating-everyone-at-once"><i class="fa fa-check"></i><b>7.3</b> Allocating everyone at once</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="cluster-rct.html"><a href="cluster-rct.html#restricted-randomization"><i class="fa fa-check"></i><b>7.3.1</b> Restricted randomization</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="cluster-rct.html"><a href="cluster-rct.html#analysing-a-cluster-rct"><i class="fa fa-check"></i><b>7.4</b> Analysing a cluster RCT</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="cluster-rct.html"><a href="cluster-rct.html#at-the-cluster-level"><i class="fa fa-check"></i><b>7.4.1</b> At the cluster level</a></li>
<li class="chapter" data-level="7.4.2" data-path="cluster-rct.html"><a href="cluster-rct.html#at-the-individual-level"><i class="fa fa-check"></i><b>7.4.2</b> At the individual level</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="rcts---a-bayesian-approach.html"><a href="rcts---a-bayesian-approach.html"><i class="fa fa-check"></i><b>8</b> RCTs - a Bayesian approach</a>
<ul>
<li class="chapter" data-level="8.1" data-path="rcts---a-bayesian-approach.html"><a href="rcts---a-bayesian-approach.html#bayesian-hierarchical-models"><i class="fa fa-check"></i><b>8.1</b> Bayesian hierarchical models</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Clinical Trials 4H</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="rct-analysis" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">6</span> Analyzing RCT data<a href="rct-analysis.html#rct-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>We’re now in the post-trial stage. The trial has been run, and we have lots of data to analyze to try to assess what effect the treatment or intervention has had. In general we will use the notation <span class="math inline">\(\tau\)</span> to denote the treatment effect.</p>
<p>We’ll first focus on the scenario where the trial outcome is measured on a continuous scale, and then we’ll go on to look at other types of data.</p>
<div class="example">
<p><span id="exm:unlabeled-div-12" class="example"><strong>Example 6.1  </strong></span>To illustrate the theory and methods, we’ll use an example dataset from <span class="citation">Hommel et al. (<a href="#ref-hommel1986effect">1986</a>)</span> (this example is also used by <span class="citation">Matthews (<a href="#ref-matthews2006introduction">2006</a>)</span>). The data involves a trial of 16 diabetes patients, and focusses on a drug (Captopril) that may reduce blood pressure. This is important, since for those with diabetes, high blood pressure can exacerbate kidney disease (specifically diabetic nephropathy, a complication of diabetes). To participate in the trial, people had to be insulin-dependent and already affected by diabetic nephropathy. In the trial, systolic blood pressure was measured before participants were allocated to each trial arm, and then measured again after one week on treatment. A placebo was given to the control group, so that all participants were blinded.</p>
<p>The baseline and outcome blood pressure measurements are shown below, in mmHg. We see that nine participants were assigned to the treatment arm (Captopril) and the remaining seven to the placebo group. <span class="citation">Hommel et al. (<a href="#ref-hommel1986effect">1986</a>)</span> say that the patients were ‘randomly allocated’ to their group.</p>
<table>
<caption>
<span id="tab:captoprildata">Table 6.1: </span>Data for the Captopril trial from <span class="citation">Hommel et al. (<a href="#ref-hommel1986effect">1986</a>)</span>.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Patient (ID)
</th>
<th style="text-align:right;">
Baseline (B)
</th>
<th style="text-align:right;">
Outcome at 1 week (X)
</th>
<th style="text-align:left;">
Trial Arm
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
147
</td>
<td style="text-align:right;">
137
</td>
<td style="text-align:left;">
Captopril
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
120
</td>
<td style="text-align:left;">
Captopril
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
158
</td>
<td style="text-align:right;">
141
</td>
<td style="text-align:left;">
Captopril
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
164
</td>
<td style="text-align:right;">
137
</td>
<td style="text-align:left;">
Captopril
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
134
</td>
<td style="text-align:right;">
140
</td>
<td style="text-align:left;">
Captopril
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
155
</td>
<td style="text-align:right;">
144
</td>
<td style="text-align:left;">
Captopril
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
151
</td>
<td style="text-align:right;">
134
</td>
<td style="text-align:left;">
Captopril
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
141
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:left;">
Captopril
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
153
</td>
<td style="text-align:right;">
142
</td>
<td style="text-align:left;">
Captopril
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
133
</td>
<td style="text-align:right;">
139
</td>
<td style="text-align:left;">
Placebo
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
134
</td>
<td style="text-align:left;">
Placebo
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
152
</td>
<td style="text-align:right;">
136
</td>
<td style="text-align:left;">
Placebo
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
161
</td>
<td style="text-align:right;">
151
</td>
<td style="text-align:left;">
Placebo
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
154
</td>
<td style="text-align:right;">
147
</td>
<td style="text-align:left;">
Placebo
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
141
</td>
<td style="text-align:right;">
137
</td>
<td style="text-align:left;">
Placebo
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
156
</td>
<td style="text-align:right;">
149
</td>
<td style="text-align:left;">
Placebo
</td>
</tr>
</tbody>
</table>
<p>This is very small dataset, and so in that respect it is quite unusual, but its structure is similar to many other trials.</p>
</div>
<p>We will build up from the simplest type of analysis to some more complicated / sophisticated approaches.</p>
<div id="confidence-intervals-and-p-values" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Confidence intervals and P-values<a href="rct-analysis.html#confidence-intervals-and-p-values" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Because the randomization process should produce groups that are comparable, we should in principle be able to compare the primary outcome (often referred to as <span class="math inline">\(X\)</span>) between the groups.</p>
<div class="example">
<p><span id="exm:unlabeled-div-13" class="example"><strong>Example 6.2  </strong></span>Summary statistics of the outcome for each group are shown below.</p>
<table>
<caption>
<span id="tab:unnamed-chunk-12">Table 6.2: </span>Summary statistics for each group.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Sample Size
</th>
<th style="text-align:right;">
Mean (mmHg)
</th>
<th style="text-align:right;">
SD (mmHg)
</th>
<th style="text-align:right;">
SE of mean (mmHg)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
135.33
</td>
<td style="text-align:right;">
8.43
</td>
<td style="text-align:right;">
2.81
</td>
</tr>
<tr>
<td style="text-align:left;">
Placebo
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
141.86
</td>
<td style="text-align:right;">
6.94
</td>
<td style="text-align:right;">
2.62
</td>
</tr>
</tbody>
</table>
<p>We see that the difference in mean outcome (systolic blood pressure) between the two groups is <span class="math inline">\(141.86 - 135.33 = 6.53 \text{mmHg}\)</span>. Clearly overall there has been some reduction in systolic blood pressure for those in the Captopril arm, but how statistically sound is this as evidence? It could be that really (for the hypothetical population) there is no reduction, and we have just been ‘lucky’.</p>
<p>The variances within the two groups are fairly close, so we can use the pooled estimate of standard deviation:</p>
<p><span class="math display">\[
  s_p = \sqrt{\frac{\sum\limits_{i=1}^N\left(n_i-1\right)s_i^2}{\sum\limits_{i-1}^N\left(n_i-1\right)}}.
\]</span></p>
<p>In our case</p>
<p><span class="math display">\[
  \begin{aligned}
s_p&amp;= \sqrt{\frac{8\times{8.43^2} + 6 \times{6.94^2}}{8+6}}\\
&amp; = 7.82\text{ mmHg.}
\end{aligned}
\]</span>
This enables us to do an independent two-sample <span class="math inline">\(t\)</span>-test, and we can find the <span class="math inline">\(t\)</span> statistic</p>
<p><span class="math display">\[
  \begin{aligned}
t &amp; = \frac{\bar{X_1} - \bar{X_2}}{s_p\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}\\
&amp; = \frac{6.53}{7.82\sqrt{\frac{1}{9} + \frac{1}{7}}} \\
&amp; = 1.65.
\end{aligned}
\]</span>
Note that here we are taking the placebo group to be group 1, and the Captopril group to be group 2.</p>
<p>Under the null hypothesis that the mean systolic blood pressure at the end of the week of treatment/placebo is the same in both groups, this value should have a <span class="math inline">\(t\)</span> distribution with 14 degrees of freedom (<span class="math inline">\(n_i-1\)</span> for each group).</p>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The dashed line is at <span class="math inline">\(t=1.65\)</span>, and the red shaded areas show anywhere ‘at least as extreme’. We can find the area (ie. the probability of anything at least as extreme as our found value) in R by</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="rct-analysis.html#cb1-1" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(<span class="fl">1.65</span>, <span class="at">df=</span><span class="dv">14</span>))</span></code></pre></div>
<pre><code>## [1] 0.1211902</code></pre>
<p>This is the value we know as ‘the P value’. We see that in this case our results are not statistically significant (at the 0.10 level), under this model.</p>
</div>
<div id="what-do-we-do-with-this-outcome" class="section level4 hasAnchor" number="6.1.0.1">
<h4><span class="header-section-number">6.1.0.1</span> What do we do with this outcome?<a href="rct-analysis.html#what-do-we-do-with-this-outcome" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The outcome of this Captopril study is in some ways the worst case scenario. The difference in means is large enough to be compelling, but our dataset is too small for it to be statistically significant, and so we can’t confidently conclude that Captopril has any effect on blood pressure. However, we also can’t say that there is no effect. This is exactly the sort of scenario we hoped to avoid when planning our study.</p>
<p>One way to reframe the question is to consider the range of treatment effects that are compatible with our trial data. That is, we find the set</p>
<p><span class="math display">\[\left\lbrace \tau \mid \frac{\lvert \bar{x}_1 - \bar{x}_2 - \tau \rvert}{s\sqrt{n_1^{-1} + n_2^{-1}}} \leq t_{n_1+n_2-2;\,0.975} \right\rbrace, \]</span>
which contains all possible values of treatment effect <span class="math inline">\(\tau\)</span> that are compatible with our data. That is, suppose the true treatment effect is <span class="math inline">\(\tau^*\)</span>, and we test the hypothesis that <span class="math inline">\(\tau = \tau^*\)</span>. For all values of <span class="math inline">\(\tau^*\)</span> inside this range, our data are not sufficiently unlikely to reject the hypothesis at the 0.05 level. However, for all values of <span class="math inline">\(\tau^*\)</span> outside this range, our data are sufficiently unlikely to reject that hypothesis. We can rearrange this to give a 95% confidence interval for <span class="math inline">\(\tau\)</span>,</p>
<p><span class="math display">\[\left\lbrace \tau \mid \bar{x}_1 - \bar{x}_2 - t_{n_1+n_2-2;\,0.975}\,s\sqrt{n_1^{-1} + n_2^{-1}} \leq \tau \leq \bar{x}_1 - \bar{x}_2 + t_{n_1+n_2-2;\,0.975}\,s\sqrt{n_1^{-1} + n_2^{-1}}  \right\rbrace \]</span></p>
<div class="example">
<p><span id="exm:unlabeled-div-14" class="example"><strong>Example 6.3  </strong></span>Continuing our example, we have</p>
<p><span class="math display">\[\left\lbrace \tau \mid \frac{\lvert 6.53 - \tau \rvert}{7.82\sqrt{\frac{1}{7} + \frac{1}{9}}} \leq t_{14;0.975} = 2.145 \right\rbrace \]</span></p>
<p>Here, <span class="math inline">\(t_{14;0.975} = 2.145\)</span> is the <span class="math inline">\(t\)</span>-value for a significance level of <span class="math inline">\(0.05\)</span>, so if we were working to a different significance level we would change this.</p>
<p>Rearranging as above, this works out to be the interval</p>
<p><span class="math display">\[
-1.92 \leq  \tau \leq 14.98.
\]</span></p>
<p>Notice that zero is in this interval, consistent with the fact that we failed to reject the null hypothesis.</p>
</div>
<p>Some things to note</p>
<ul>
<li>We can compute this confidence interval whether or not we failed to reject the null hypothesis that <span class="math inline">\(\tau=0\)</span>, and for significance levels other than 0.05.</li>
<li>In most cases, reporting the confidence interval is much more informative than simply reporting the <span class="math inline">\(P\)</span>-value. In our Captopril example, we found that a negative treatment effect (ie. Captopril reducing blood pressure less than the placebo) of more than 2 mmHg was very unlikely, whereas a positive effective (Captopril reducing blood pressure) of up to 15 mmHg was plausible. If Captopril were inexpensive and had very limited side effects (sadly neither of which is true) it may still be an attractive drug.</li>
<li>These confidence intervals are exactly the same as you have learned before, but we emphasise them because they are very informative in randomised controlled trials (but not so often used!).</li>
</ul>
<p>At the post trial stage, when we have data, the confidence interval is the most useful link to the concept of <em>power</em>, which we thought about at the planning stage. Remember that the power function is defined as</p>
<p><span class="math display">\[\psi \left(\tau\right) = P\left(\text{Reject }H_0\mid \tau\neq 0\right),\]</span> that is, the probability that we successfully reject <span class="math inline">\(H_0\)</span> (that <span class="math inline">\(\tau=0\)</span>) given that there is a non-zero treatment effect <span class="math inline">\(\tau\neq 0\)</span>. This was calculated in terms of the theoretical model of the trial, and in terms of some minimum detectable effect size <span class="math inline">\(\tau_M\)</span> that we wanted to be able to correctly detect with probability <span class="math inline">\(1-\beta\)</span> (the power). Sometimes people attempt to re-calculate the power after the trial, to detect whether the trial was underpowered. However, now we have actual data. If we failed to reject <span class="math inline">\(H_0\)</span> and <span class="math inline">\(\tau_M\)</span> is in the confidence interval for <span class="math inline">\(\tau\)</span>, then that is a good indication that our trial was indeed underpowered.</p>
</div>
<div id="bonferroni-correction" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Bonferroni correction<a href="rct-analysis.html#bonferroni-correction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>(and possibly other types of adjustment? - where to put this?!)</p>
</div>
</div>
<div id="baseline" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Using baseline values<a href="rct-analysis.html#baseline" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In our example above, our primary outcome variable <span class="math inline">\(X\)</span> was the systolic blood pressure of each participant at the end of the intervention period. However, we see in Table <a href="rct-analysis.html#tab:captoprildata">6.1</a> that we also have <em>baseline</em> measurements: measurements of systolic blood pressure for each patient from before the intervention period. Baseline measurements are useful primarily for two reasons:</p>
<ol style="list-style-type: decimal">
<li>They can be used to assess the balance of the design.</li>
<li>They can be used in the analysis.</li>
</ol>
<p>We will demonstrate these by returning to our Captopril example.</p>
<div class="example">
<p><span id="exm:unlabeled-div-15" class="example"><strong>Example 6.4  </strong></span>Firstly, we use the baseline systolic blood pressure to assess balance. The placebo group has a mean of 146.6 mmHg and an SD of 12.3 mmHg, whereas the Captopril group has mean 148.0 mmHg, SD 11.4 mmHg. While these aren’t identical, they are sufficiently similar to think they wouldn’t affect our analysis.</p>
<p>Secondly, since we are interested in whether the use of Captopril has reduced blood pressure for each individual, and these individuals had different baseline values, it makes sense to compare not just the outcome but the difference from baseline to outcome for each individual. We can see individual data in Table <a href="rct-analysis.html#tab:captoprildiff">6.3</a> and summary statistics in Table <a href="rct-analysis.html#tab:captoprildiffsumm">6.4</a>.</p>
<table>
<caption>
<span id="tab:captoprildiff">Table 6.3: </span>Data for the Captopril trial from <span class="citation">Hommel et al. (<a href="#ref-hommel1986effect">1986</a>)</span>, with differences shown.
</caption>
<thead>
<tr>
<th style="text-align:right;">
Patient (ID)
</th>
<th style="text-align:right;">
Baseline (B)
</th>
<th style="text-align:right;">
Outcome at 1 week (X)
</th>
<th style="text-align:left;">
Trial Arm
</th>
<th style="text-align:right;">
Difference
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
147
</td>
<td style="text-align:right;">
137
</td>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
-10
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
120
</td>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
-9
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
158
</td>
<td style="text-align:right;">
141
</td>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
-17
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
164
</td>
<td style="text-align:right;">
137
</td>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
-27
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
134
</td>
<td style="text-align:right;">
140
</td>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
155
</td>
<td style="text-align:right;">
144
</td>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
-11
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
151
</td>
<td style="text-align:right;">
134
</td>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
-17
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
141
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
-18
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
153
</td>
<td style="text-align:right;">
142
</td>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
-11
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
133
</td>
<td style="text-align:right;">
139
</td>
<td style="text-align:left;">
Placebo
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
134
</td>
<td style="text-align:left;">
Placebo
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
152
</td>
<td style="text-align:right;">
136
</td>
<td style="text-align:left;">
Placebo
</td>
<td style="text-align:right;">
-16
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
161
</td>
<td style="text-align:right;">
151
</td>
<td style="text-align:left;">
Placebo
</td>
<td style="text-align:right;">
-10
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
154
</td>
<td style="text-align:right;">
147
</td>
<td style="text-align:left;">
Placebo
</td>
<td style="text-align:right;">
-7
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
141
</td>
<td style="text-align:right;">
137
</td>
<td style="text-align:left;">
Placebo
</td>
<td style="text-align:right;">
-4
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
156
</td>
<td style="text-align:right;">
149
</td>
<td style="text-align:left;">
Placebo
</td>
<td style="text-align:right;">
-7
</td>
</tr>
</tbody>
</table>
<table>
<caption>
<span id="tab:captoprildiffsumm">Table 6.4: </span>Summary statistics for each group.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Sample Size
</th>
<th style="text-align:right;">
Mean (mmHg)
</th>
<th style="text-align:right;">
SD (mmHg)
</th>
<th style="text-align:right;">
SE of mean (mmHg)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Captopril
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
-12.67
</td>
<td style="text-align:right;">
8.99
</td>
<td style="text-align:right;">
3.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Placebo
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
-4.71
</td>
<td style="text-align:right;">
7.91
</td>
<td style="text-align:right;">
2.99
</td>
</tr>
</tbody>
</table>
<p>Now we can perform our test as before, in which case we find</p>
<p><span class="math display">\[ t = \frac{-4.71 - (-12.67)}{8.54\sqrt{\frac{1}{7}+\frac{1}{9}}} = 1.850 \]</span>
where 8.54 is the pooled standard deviation (as before). Under the null distribution of no difference, this has a <span class="math inline">\(t\)</span>-distribution with 14 degrees of freedom, and so we have a <span class="math inline">\(P\)</span>-value of 0.086. Our 0.95 confidence interval is</p>
<p><span class="math display">\[ -4.71 - (-12.67) \pm t_{14;\,0.975}\times 8.54\sqrt{\frac{1}{7}+\frac{1}{9}} = \left[-1.3,\,17.2\right].\]</span>
We see that taking into account the baseline values in this way has slightly reduced the <span class="math inline">\(P\)</span>-value and shifted the confidence interval slightly higher. Though at the <span class="math inline">\(\alpha = 0.05\)</span> level we still don’t have significance.</p>
</div>
<p>We will now look into why the confidence interval and <span class="math inline">\(P\)</span>-value changed in this way, before going on to another way of taking into account the baseline value.</p>
<p>Let’s label the baseline measurement for each group <span class="math inline">\(B_1\)</span> and <span class="math inline">\(B_2\)</span>, and the outcome measurements <span class="math inline">\(X_1,\,X_2\)</span>, where we will take group 1 to be the placebo group and group 2 to be the treatment group. Because all participants have been randomised from the same population, we have</p>
<p><span class="math display">\[\operatorname{E}\left(B_1\right) = \operatorname{E}\left(B_2\right) = \mu_B.\]</span>
Assuming some treatment effect <span class="math inline">\(\tau\)</span> (which could still be zero) we have</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{E}\left(X_1\right) &amp; = \mu\\
\operatorname{E}\left(X_2\right) &amp; = \mu + \tau.
\end{aligned}
\]</span>
Usually we will assume that</p>
<p><span class="math display">\[\operatorname{Var}\left(X_1\right) = \operatorname{Var}\left(X_2\right) = \operatorname{Var}\left(B_1\right) = \operatorname{Var}\left(B_2\right) = \sigma^2,\]</span>
and this is generally fairly reasonable in practice.</p>
<p>Notice that for the two analyses we have performed so far (comparing outcomes and comparing differences) we have</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{E}\left(X_2\right) - \operatorname{E}\left(X_1\right) &amp; = \left(\mu + \tau\right) - \mu = \tau\\
\operatorname{E}\left(X_2 - B_2\right) - \operatorname{E}\left(X_1 - B_1\right) &amp; = \left(\mu - \mu_B + \tau\right) - \left(\mu - \mu_B\right) = \tau,
\end{aligned}
\]</span>
that is, both are unbiased estimators of <span class="math inline">\(\tau\)</span>.</p>
<p>However, whereas the first is based on data with variance <span class="math inline">\(\sigma^2\)</span>, the second has</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{Var}\left(X_2-B_2\right) &amp; = \operatorname{Var}\left(X_2\right) + \operatorname{Var}\left(B_2\right) - 2\operatorname{cov}\left(X_2,B_2\right)\\
&amp; = \sigma^2 + \sigma^2 - 2\rho\sigma^2 \\
&amp; = 2\sigma^2\left(1-\rho\right),
\end{aligned}
\]</span>
where <span class="math inline">\(\rho\)</span> is the true correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(B\)</span>, and is assumed to be the same in either group. Therefore, if <span class="math inline">\(\frac{1}{2}&lt;\rho\leq 1\)</span> there will be a smaller variance when comparing differences. However, if <span class="math inline">\(0\leq\rho&lt;\frac{1}{2}\)</span>, the variance will be smaller when comparing outcome variables.</p>
<p>Intuitively, this seems reasonable: if the correlation between baseline and outcome measurements is very strong, then we can remove some of the variability between participants by taking into account their baseline measurement. However, if the correlation is weak, then by including the baseline in the analysis we are essentially just introducing noise.</p>
<p>For our Captopril example, the sample correlation between baseline and outcome is 0.63 in the Captopril group and 0.80 in the Placebo group. This fits with the <span class="math inline">\(P\)</span>-value having reduced slightly.</p>
</div>
<div id="analysis-of-covariance-ancova" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Analysis of covariance (ANCOVA)<a href="rct-analysis.html#analysis-of-covariance-ancova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the previous section we based our analysis on the baseline values being statistically identical draws from the underlying distribution, and therefore having the same expectation and variance.</p>
<p>However, although this is theoretically true, in real life trials there will be some imbalance in the baseline measurements for the different treatment arms. We can see this in our Captopril example, in Figure <a href="rct-analysis.html#fig:hommel">6.1</a>.</p>
<div class="figure"><span style="display:block;" id="fig:hommel"></span>
<img src="CT4H_notes_files/figure-html/hommel-1.png" alt="Data from the Captopril trial @hommel1986effect." width="672" />
<p class="caption">
Figure 6.1: Data from the Captopril trial <span class="citation">Hommel et al. (<a href="#ref-hommel1986effect">1986</a>)</span>.
</p>
</div>
<p>The baseline measurements are not identical in each group. Indeed, we saw earlier that the means differ by 1.4 mmHg. Although this isn’t a clinically significant difference, or a large enough difference to make us doubt the randomisation procedure, it is still a difference.</p>
<p>If there is some correlation between the baseline and outcome measurements, then if the baseline measurements differ, one would expect the outcome measurements to differ, even if there is no treatment effect (ie. if <span class="math inline">\(\tau=0\)</span>). Indeed, how do we decide how much of the difference in outcome is down to the treatment itself, and how much is simply the difference arising from different samples?</p>
<p>This issue arises in many trials, particularly where there is a strong correlation between baseline and outcome measurements.</p>
<div id="the-theory" class="section level3 hasAnchor" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> The theory<a href="rct-analysis.html#the-theory" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose the outcome for a clinical trial is <span class="math inline">\(X\)</span> and the baseline is <span class="math inline">\(B\)</span>. <span class="math inline">\(X\)</span> has mean <span class="math inline">\(\mu\)</span> in the control group (C) and mean <span class="math inline">\(\mu+\tau\)</span> in the test group (T), and as usual our aim is to determine the extent of <span class="math inline">\(\tau\)</span>, the treatment effect. We suppose also that <span class="math inline">\(X\)</span> has variance <span class="math inline">\(\sigma^2\)</span> in both groups.</p>
<p>The same quantity is measured at the start of the trial, and this is the baseline <span class="math inline">\(B\)</span>, which we can assume to have true mean <span class="math inline">\(\mu_B\)</span> in both groups (because of randomisation) and variance <span class="math inline">\(\sigma^2\)</span>. We also assume that the true correlation between <span class="math inline">\(B\)</span> and <span class="math inline">\(X\)</span> is <span class="math inline">\(\rho\)</span> in each group. Finally, we assume that both treatment groups are of size <span class="math inline">\(N\)</span>.</p>
<p>We therefore have <span class="math inline">\(2N\)</span> patients, and so we observe baseline measurements <span class="math inline">\(b_1,\,b_2,\ldots,b_{2N}\)</span>. Given these values, we have</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{E}\left(X_i\mid{b_i}\right) &amp;= \mu + \rho\left(b_i - \mu_B\right)\text{ in the control group}\\
\operatorname{E}\left(X_i\mid{b_i}\right) &amp;= \mu +\tau + \rho\left(b_i - \mu_B\right)\text{ in the test group.}
\end{aligned}
\]</span></p>
<p>From this, we find that</p>
<p><span class="math display" id="eq:diffexp">\[\begin{equation}
\operatorname{E}\left(\bar{X}_T - \bar{X}_C\mid{\bar{b}_T,\,\bar{b}_C}\right) = \tau + \rho\left(\bar{b}_T - \bar{b}_C\right).
\tag{6.1}
\end{equation}\]</span>
That is, if there is a difference in the baseline mean between the control and test groups, then the difference in outcome means is not an unbiased estimator of the treatment effect <span class="math inline">\(\tau\)</span>. Assuming <span class="math inline">\(\rho&gt;0\)</span> (which is almost always the case) then if <span class="math inline">\(\bar{b}_T&gt;\bar{b}_C\)</span> the difference in outcome means overestimates <span class="math inline">\(\tau\)</span>. Conversely, if <span class="math inline">\(\bar{b}_T&lt;\bar{b}_C\)</span>, the difference in outcome means underestimates <span class="math inline">\(\tau\)</span>. The only situation in which the difference in outcome means is an unbiased estimator is when <span class="math inline">\(\rho=0\)</span>, however this is not common in practice.</p>
<p>Comparing the difference between outcome and baseline, as we did in <a href="rct-analysis.html#baseline">6.2</a>, does not solve this problem, since we have</p>
<p><span class="math display">\[\operatorname{E}\left[\left(\bar{X}_T - \bar{b}_T\right) - \left(\bar{X}_C - \bar{b}_C\right)\mid{\bar{b}_T,\,\bar{b}_C}\right] = \tau + \left(\rho-1\right)\left(\bar{b}_T - \bar{b}_C\right),\]</span>
which is similarly unbiased (unless <span class="math inline">\(\rho=1\)</span>, which is never the case).</p>
<p>Notice, however, that if we use as our estimator</p>
<p><span class="math display">\[\left(\bar{X}_T - \bar{X}_C\right) - \rho \left(\bar{b}_T - \bar{b}_C\right)\]</span> then, following from Equation <a href="rct-analysis.html#eq:diffexp">(6.1)</a> we have</p>
<p><span class="math display">\[\operatorname{E}\left[\left(\bar{X}_T - \bar{X}_C\right) - \rho \left(\bar{b}_T - \bar{b}_C\right)\mid{\bar{b}_T,\,\bar{b}_C}\right] = \tau + \rho\left(\bar{b}_T - \bar{b}_C\right)- \rho\left(\bar{b}_T - \bar{b}_C\right) = \tau. \]</span></p>
</div>
<div id="the-practice" class="section level3 hasAnchor" number="6.3.2">
<h3><span class="header-section-number">6.3.2</span> The practice<a href="rct-analysis.html#the-practice" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the previous section we established an unbiased estimate of the treatment effect that takes into account the baseline measurements. However, we can’t use it as a model, because there are a few practical barriers:</p>
<ul>
<li>Our estimate for <span class="math inline">\(\tau\)</span> relies on the correlation <span class="math inline">\(\lambda\)</span>, which is unknown</li>
<li>In real life, the groups are unlikely to have equal size and variance, so ideally we’d lose these constraints</li>
</ul>
<p>We can solve both of these by fitting the following statistical model to the observed outcomes <span class="math inline">\(x_i\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
x_i &amp; = \mu + \gamma b_i + \epsilon_i &amp; \text{ in group C}\\
x_i &amp; = \mu + \tau + \gamma b_i + \epsilon_i &amp; \text{ in group T}&amp;.
\end{aligned}
\]</span>
Here, the <span class="math inline">\(\epsilon_i\)</span> are independent errors with distribution <span class="math inline">\(N\left(0,\,\sigma^2\right)\)</span>, the <span class="math inline">\(b_i\)</span> are the baseline measurements for <span class="math inline">\(i=1,\ldots,N_T+N_C\)</span>, for groups <span class="math inline">\(T\)</span> and <span class="math inline">\(C\)</span> with sizes <span class="math inline">\(N_T\)</span> and <span class="math inline">\(N_C\)</span> respectively. Sometimes this is written instead in the form</p>
<p><span class="math display">\[ x_i = \mu + \tau G_i+ \gamma b_i + \epsilon_i \]</span>
where <span class="math inline">\(G_i\)</span> is 1 if participant <span class="math inline">\(i\)</span> is in group <span class="math inline">\(T\)</span> and 0 if they’re in group <span class="math inline">\(C\)</span>.</p>
<p>We now have four parameters to estimate: <span class="math inline">\(\mu,\,\tau,\,\gamma\)</span> and <span class="math inline">\(\sigma^2\)</span>. For the first three we can use least squares (as you have probably seen for linear regression). Our aim is to minimise the sum of squares</p>
<p><span class="math display">\[S\left(\mu,\, \tau,\,\gamma\right) = \sum\limits_{i\text{ in }T} \left(x_i - \mu - \tau - \gamma b_i\right)^2 + \sum\limits_{i\text{ in }C} \left(x_i - \mu - \gamma b_i\right)^2.\]</span></p>
<p>This leads to estimates <span class="math inline">\(\hat{\mu},\, \hat{\tau}\)</span> and <span class="math inline">\(\hat{\gamma}\)</span>. We won’t worry about how this sum is minimised, since we’ll always be using pre-written R functions. We can use the estimates <span class="math inline">\(\hat{\mu},\, \hat{\tau}\)</span> and <span class="math inline">\(\hat{\gamma}\)</span> to estimate <span class="math inline">\(\sigma^2\)</span>, using</p>
<p><span class="math display">\[\hat{\sigma}^2 = \frac{S\left(\hat{\mu},\hat{\tau}, \hat{\gamma}\right)}{N_T + N_C -3}.\]</span>
The general form for this is</p>
<p><span class="math display">\[ \hat{\sigma}^2 = \frac{SSE}{n-p},\]</span>
where <span class="math inline">\(SSE\)</span> is the residual sum of squares, <span class="math inline">\(n\)</span> is the number of data points and <span class="math inline">\(p\)</span> the number of parameters (apart from <span class="math inline">\(\sigma^2\)</span>) being estimated. If you want to know why that is, you can find out <a href="https://pages.stern.nyu.edu/~wgreene/MathStat/GreeneChapter4.pdf">here</a> (look particularly at page 62), but we will just take it as given!</p>
<p>The technique described above is a well-established statistical method known as <strong>ANCOVA</strong> (short for the <strong>An</strong>alysis of <strong>Cova</strong>riance), which can be implemented in R and many other statistical software packages.</p>
<div class="example">
<p><span id="exm:unlabeled-div-16" class="example"><strong>Example 6.5  </strong></span>Let’s now implement ANCOVA on our Captopril data in R.</p>
<p>We can also use the ‘aov’ function to fit the ANCOVA model, now including the baseline (our covariate) in the model formula</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="rct-analysis.html#cb3-1" tabindex="-1"></a>model_ancova_capt <span class="ot">=</span> <span class="fu">anova_test</span>(<span class="at">data=</span>df_hommel, <span class="at">formula =</span> outcome <span class="sc">~</span> arm <span class="sc">+</span> baseline)</span>
<span id="cb3-2"><a href="rct-analysis.html#cb3-2" tabindex="-1"></a>model_ancova_capt</span></code></pre></div>
<pre><code>## ANOVA Table (type II tests)
## 
##     Effect DFn DFd      F     p p&lt;.05   ges
## 1      arm   1  13  5.866 0.031     * 0.311
## 2 baseline   1  13 11.878 0.004     * 0.477</code></pre>
</div>
</div>
<div id="a-few-cautions" class="section level3 hasAnchor" number="6.3.3">
<h3><span class="header-section-number">6.3.3</span> A few cautions<a href="rct-analysis.html#a-few-cautions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are some assumptions we’re making here, and so we need to be careful when fitting an ANCOVA model.</p>
<ul>
<li>We’re assuming that the residual variance is the same for both groups</li>
<li>We’re assuming that the coefficient of the baseline is the same for both groups: only the intercept is changing.</li>
</ul>
<p>We can’t check the first until after</p>
<div class="example">
<p><span id="exm:unlabeled-div-17" class="example"><strong>Example 6.6  </strong></span>Before fitting our ANCOVA model we should first have checked that there’s no significant relationship between the covariate (in this case the baseline) and the treatment group, which we can do using ANOVA:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="rct-analysis.html#cb5-1" tabindex="-1"></a>model_aov_capt <span class="ot">=</span> <span class="fu">aov</span>(baseline <span class="sc">~</span> arm, <span class="at">data =</span> df_hommel)</span>
<span id="cb5-2"><a href="rct-analysis.html#cb5-2" tabindex="-1"></a><span class="fu">summary</span>(model_capt)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## arm          1  167.6   167.6   2.738   0.12
## Residuals   14  856.9    61.2</code></pre>
<p>If the experiment has been properly designed then there shouldn’t be, but this is not always the case, and indeed depending on how we do the randomisation we could be unlucky. If baseline measurements are available before allocation, this can be checked before the trial is run.</p>
</div>
</div>
</div>
<div id="binary-data" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Binary data<a href="rct-analysis.html#binary-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="confidence-intervals-for-binary-data" class="section level3 hasAnchor" number="6.4.1">
<h3><span class="header-section-number">6.4.1</span> Confidence intervals for binary data<a href="rct-analysis.html#confidence-intervals-for-binary-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div id="using-baseline-measurements" class="section level3 hasAnchor" number="6.4.2">
<h3><span class="header-section-number">6.4.2</span> Using baseline measurements<a href="rct-analysis.html#using-baseline-measurements" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
</div>
<div id="categorical-data" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Categorical data?<a href="rct-analysis.html#categorical-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Could mention Fisher’s exact test, as demonstrated in the indo_rct data in the medicaldata package.</p>
</div>
<div id="survival-data" class="section level2 hasAnchor" number="6.6">
<h2><span class="header-section-number">6.6</span> Survival data<a href="rct-analysis.html#survival-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-hommel1986effect" class="csl-entry">
Hommel, EHEBMJ, Hans-Henrik Parving, Elisabeth Mathiesen, Berit Edsberg, M Damkjaer Nielsen, and Jørn Giese. 1986. <span>“Effect of Captopril on Kidney Function in Insulin-Dependent Diabetic Patients with Nephropathy.”</span> <em>Br Med J (Clin Res Ed)</em> 293 (6545): 467–70.
</div>
<div id="ref-matthews2006introduction" class="csl-entry">
Matthews, John NS. 2006. <em>Introduction to Randomized Controlled Clinical Trials</em>. CRC Press.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="the-intervention.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cluster-rct.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
