<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Time-to-event data and Survival Analysis | Clinical Trials 4H</title>
  <meta name="description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Time-to-event data and Survival Analysis | Clinical Trials 4H" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Time-to-event data and Survival Analysis | Clinical Trials 4H" />
  
  <meta name="twitter:description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  

<meta name="author" content="Rachel Oughton" />


<meta name="date" content="2024-01-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="binary-outcome-variable.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Clinical Trials 4H!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#practical-details"><i class="fa fa-check"></i>Practical details</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#lectures"><i class="fa fa-check"></i>Lectures</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#computer-classes"><i class="fa fa-check"></i>Computer classes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i>Assessment</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#books"><i class="fa fa-check"></i>Books</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-to-expect-from-this-module"><i class="fa fa-check"></i>What to expect from this module</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-i-expect-from-you"><i class="fa fa-check"></i>What I expect from you</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="rct-intro.html"><a href="rct-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction to Clinical Trials</a>
<ul>
<li class="chapter" data-level="1.1" data-path="rct-intro.html"><a href="rct-intro.html#causal-inference-and-clinical-trials"><i class="fa fa-check"></i><b>1.1</b> Causal inference and clinical trials</a></li>
<li class="chapter" data-level="1.2" data-path="rct-intro.html"><a href="rct-intro.html#the-structure-of-a-clinical-trial"><i class="fa fa-check"></i><b>1.2</b> The structure of a clinical trial</a>
<ul>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#the-population-of-eligible-patients"><i class="fa fa-check"></i>The population of eligible patients</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#entry-to-the-trial"><i class="fa fa-check"></i>Entry to the trial</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#allocation-to-groups"><i class="fa fa-check"></i>Allocation to groups</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#comparing-results"><i class="fa fa-check"></i>Comparing results</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#why-bother-with-a-control-group"><i class="fa fa-check"></i>Why bother with a control group?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="rct-intro.html"><a href="rct-intro.html#primout"><i class="fa fa-check"></i><b>1.3</b> The primary outcome</a></li>
<li class="chapter" data-level="1.4" data-path="rct-intro.html"><a href="rct-intro.html#ethical-issues"><i class="fa fa-check"></i><b>1.4</b> Ethical issues</a></li>
<li class="chapter" data-level="1.5" data-path="rct-intro.html"><a href="rct-intro.html#phases-of-clinical-trials"><i class="fa fa-check"></i><b>1.5</b> Phases of clinical trials</a>
<ul>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-zero"><i class="fa fa-check"></i>Phase zero</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-one"><i class="fa fa-check"></i>Phase one</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-two"><i class="fa fa-check"></i>Phase two</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-three"><i class="fa fa-check"></i>Phase three</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-four"><i class="fa fa-check"></i>Phase four</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Part I: Continuous outcome variables</b></span></li>
<li class="chapter" data-level="2" data-path="rct-plan.html"><a href="rct-plan.html"><i class="fa fa-check"></i><b>2</b> Sample size for a normally distributed primary outcome variable</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rct-plan.html"><a href="rct-plan.html#the-treatment-effect"><i class="fa fa-check"></i><b>2.1</b> The treatment effect</a></li>
<li class="chapter" data-level="2.2" data-path="rct-plan.html"><a href="rct-plan.html#reminder-hypothesis-tests-with-a-focus-on-rcts"><i class="fa fa-check"></i><b>2.2</b> Reminder: hypothesis tests (with a focus on RCTs)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="rct-plan.html"><a href="rct-plan.html#insignificant-results"><i class="fa fa-check"></i><b>2.2.1</b> Insignificant results</a></li>
<li class="chapter" data-level="2.2.2" data-path="rct-plan.html"><a href="rct-plan.html#one-tailed-or-two-tailed"><i class="fa fa-check"></i><b>2.2.2</b> One-tailed or two-tailed?</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="rct-plan.html"><a href="rct-plan.html#sec-measDcont"><i class="fa fa-check"></i><b>2.3</b> Constructing a measure of effect size</a></li>
<li class="chapter" data-level="2.4" data-path="rct-plan.html"><a href="rct-plan.html#sec-power"><i class="fa fa-check"></i><b>2.4</b> Power: If <span class="math inline">\(H_0\)</span> is false</a></li>
<li class="chapter" data-level="2.5" data-path="rct-plan.html"><a href="rct-plan.html#sec-ssformulacont"><i class="fa fa-check"></i><b>2.5</b> A sample size formula</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="allocation.html"><a href="allocation.html"><i class="fa fa-check"></i><b>3</b> Allocation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="allocation.html"><a href="allocation.html#bias"><i class="fa fa-check"></i><b>3.1</b> Bias</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="allocation.html"><a href="allocation.html#where-does-bias-come-from"><i class="fa fa-check"></i><b>3.1.1</b> Where does bias come from?</a></li>
<li class="chapter" data-level="3.1.2" data-path="allocation.html"><a href="allocation.html#implications-for-allocation"><i class="fa fa-check"></i><b>3.1.2</b> Implications for allocation</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="allocation.html"><a href="allocation.html#sec-allocation"><i class="fa fa-check"></i><b>3.2</b> Allocation methods</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="allocation.html"><a href="allocation.html#simple-random-allocation"><i class="fa fa-check"></i><b>3.2.1</b> Simple random allocation</a></li>
<li class="chapter" data-level="3.2.2" data-path="allocation.html"><a href="allocation.html#random-permuted-blocks"><i class="fa fa-check"></i><b>3.2.2</b> Random permuted blocks</a></li>
<li class="chapter" data-level="3.2.3" data-path="allocation.html"><a href="allocation.html#biased-coin-designs-and-urn-schemes"><i class="fa fa-check"></i><b>3.2.3</b> Biased coin designs and urn schemes</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="allocation.html"><a href="allocation.html#incorporating-baseline-measurements"><i class="fa fa-check"></i><b>3.3</b> Incorporating baseline measurements</a></li>
<li class="chapter" data-level="3.4" data-path="allocation.html"><a href="allocation.html#stratified-sampling"><i class="fa fa-check"></i><b>3.4</b> Stratified sampling</a></li>
<li class="chapter" data-level="3.5" data-path="allocation.html"><a href="allocation.html#minimization"><i class="fa fa-check"></i><b>3.5</b> Minimization</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="allocation.html"><a href="allocation.html#minimization-algorithm"><i class="fa fa-check"></i><b>3.5.1</b> Minimization algorithm</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="allocation.html"><a href="allocation.html#problems-with-allocation"><i class="fa fa-check"></i><b>3.6</b> Problems with allocation</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rct-analysis.html"><a href="rct-analysis.html"><i class="fa fa-check"></i><b>4</b> Analyzing RCT data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="rct-analysis.html"><a href="rct-analysis.html#ttest"><i class="fa fa-check"></i><b>4.1</b> Confidence intervals and P-values</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="rct-analysis.html"><a href="rct-analysis.html#what-do-we-do-with-this-outcome"><i class="fa fa-check"></i><b>4.1.1</b> What do we do with this outcome?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="rct-analysis.html"><a href="rct-analysis.html#baseline"><i class="fa fa-check"></i><b>4.2</b> Using baseline values</a></li>
<li class="chapter" data-level="4.3" data-path="rct-analysis.html"><a href="rct-analysis.html#analysis-of-covariance-ancova"><i class="fa fa-check"></i><b>4.3</b> Analysis of covariance (ANCOVA)</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="rct-analysis.html"><a href="rct-analysis.html#ancovatheory"><i class="fa fa-check"></i><b>4.3.1</b> The theory</a></li>
<li class="chapter" data-level="4.3.2" data-path="rct-analysis.html"><a href="rct-analysis.html#the-practice"><i class="fa fa-check"></i><b>4.3.2</b> The practice</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="rct-analysis.html"><a href="rct-analysis.html#some-follow-up-questions."><i class="fa fa-check"></i><b>4.4</b> Some follow-up questions….</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="rct-analysis.html"><a href="rct-analysis.html#didnt-we-say-that-x_t---x_c-was-an-unbiased-estimator-of-tau"><i class="fa fa-check"></i><b>4.4.1</b> Didn’t we say that <span class="math inline">\(X_T - X_C\)</span> was an unbiased estimator of <span class="math inline">\(\tau\)</span>?</a></li>
<li class="chapter" data-level="4.4.2" data-path="rct-analysis.html"><a href="rct-analysis.html#what-if-the-lines-shouldnt-be-parallel-the-unequal-slopes-model"><i class="fa fa-check"></i><b>4.4.2</b> What if the lines shouldn’t be parallel? The unequal slopes model</a></li>
<li class="chapter" data-level="4.4.3" data-path="rct-analysis.html"><a href="rct-analysis.html#can-we-include-any-other-baseline-covariates"><i class="fa fa-check"></i><b>4.4.3</b> Can we include any other baseline covariates?</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="rct-analysis.html"><a href="rct-analysis.html#some-general-principles-of-analysis"><i class="fa fa-check"></i><b>4.5</b> Some general principles of Analysis</a></li>
</ul></li>
<li class="part"><span><b>II Part II: Other sorts of outcome variables</b></span></li>
<li class="chapter" data-level="5" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html"><i class="fa fa-check"></i><b>5</b> Binary outcome variable</a>
<ul>
<li class="chapter" data-level="5.1" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#ss-bin"><i class="fa fa-check"></i><b>5.1</b> Sample size for a binary variable</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#the-delta-method"><i class="fa fa-check"></i><b>5.1.1</b> The Delta Method</a></li>
<li class="chapter" data-level="5.1.2" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#a-sample-size-formula"><i class="fa fa-check"></i><b>5.1.2</b> A sample size formula</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#point-estimates-and-hypothesis-tests"><i class="fa fa-check"></i><b>5.2</b> Point estimates and Hypothesis tests</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#an-alternative-approach-chi-squared"><i class="fa fa-check"></i><b>5.2.1</b> An alternative approach: chi-squared</a></li>
<li class="chapter" data-level="5.2.2" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#likelihood-a-more-rigorous-way"><i class="fa fa-check"></i><b>5.2.2</b> Likelihood: A more rigorous way</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#measures-of-difference-for-binary-data"><i class="fa fa-check"></i><b>5.3</b> Measures of difference for binary data</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#ard-and-nnt"><i class="fa fa-check"></i><b>5.3.1</b> Absolute risk difference and Number Needed to Treat</a></li>
<li class="chapter" data-level="5.3.2" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#risk-ratio-rr-and-odds-ratio-or"><i class="fa fa-check"></i><b>5.3.2</b> Risk Ratio (RR) and Odds ratio (OR)</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#accounting-for-baseline-observations-logistic-regression"><i class="fa fa-check"></i><b>5.4</b> Accounting for baseline observations: logistic regression</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="binary-outcome-variable.html"><a href="binary-outcome-variable.html#what-does-this-model-tell-us"><i class="fa fa-check"></i><b>5.4.1</b> What does this model tell us?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="time-to-event-data-and-survival-analysis.html"><a href="time-to-event-data-and-survival-analysis.html"><i class="fa fa-check"></i><b>6</b> Time-to-event data and Survival Analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="time-to-event-data-and-survival-analysis.html"><a href="time-to-event-data-and-survival-analysis.html#censored-times"><i class="fa fa-check"></i><b>6.1</b> Censored times</a></li>
<li class="chapter" data-level="6.2" data-path="time-to-event-data-and-survival-analysis.html"><a href="time-to-event-data-and-survival-analysis.html#the-survival-curve-and-the-hazard-function"><i class="fa fa-check"></i><b>6.2</b> The Survival Curve and the Hazard function</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="time-to-event-data-and-survival-analysis.html"><a href="time-to-event-data-and-survival-analysis.html#the-kaplan-meier-estimator"><i class="fa fa-check"></i><b>6.2.1</b> The Kaplan-Meier estimator</a></li>
<li class="chapter" data-level="6.2.2" data-path="time-to-event-data-and-survival-analysis.html"><a href="time-to-event-data-and-survival-analysis.html#a-parametric-approach"><i class="fa fa-check"></i><b>6.2.2</b> A parametric approach</a></li>
<li class="chapter" data-level="6.2.3" data-path="time-to-event-data-and-survival-analysis.html"><a href="time-to-event-data-and-survival-analysis.html#sample-size-calculations-for-time-to-event-data"><i class="fa fa-check"></i><b>6.2.3</b> Sample size calculations for time-to-event data</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="time-to-event-data-and-survival-analysis.html"><a href="time-to-event-data-and-survival-analysis.html#comparing-survival-curves"><i class="fa fa-check"></i><b>6.3</b> Comparing survival curves</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="time-to-event-data-and-survival-analysis.html"><a href="time-to-event-data-and-survival-analysis.html#non-parametric-the-log-rank-test"><i class="fa fa-check"></i><b>6.3.1</b> Non-parametric: the log-rank test</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Clinical Trials 4H</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="time-to-event-data-and-survival-analysis" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">6</span> Time-to-event data and Survival Analysis<a href="time-to-event-data-and-survival-analysis.html#time-to-event-data-and-survival-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>A data type that is commonly found in clinical trials is <strong>time to event data</strong>. This type of data deals with the amount of time that elapses before a particular event happens. Unlike continuous and binary random variables, this is a fairly recent branch of statistics, which developed rapidly during the many cancer related clinical trials of the 1960s and 1970s. In these cases, the event in question was very often death, and so this branch of statistics came to be known as <strong>survival analysis</strong>. However, the event can be many other things, and indeed can be a positive outcome (for example being cured of some condition). As well as the books already mentioned, this chapter makes use of <span class="citation">Collett (<a href="#ref-collett_surv">2003</a>)</span>.</p>
<p>Usually, survival data is given in terms of time, but it can also be the number of times something happens (for example, the number of clinic appointments attended) before the event in question occurs.</p>
<p>Survival data is trickier to handle than the data types we have seen so far, for two main reasons. Firstly (and simply) survival data is very often skewed, so even though it is (usually) continuous, we can’t just treat it as normally distributed. Secondly (and more complicatedly, if that’s a word) with time-to-event data we don’t usually observe the full dataset.</p>
<div id="censored-times" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Censored times<a href="time-to-event-data-and-survival-analysis.html#censored-times" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If a trial monitors a sample of participants for some length of time, many will experience the event before the trial is finished. However, for some of the sample we likely won’t observe the event. This could be because it doesn’t happen within the lifetime of the trial, or it could be because the participant exits the trial prematurely for some reason (eg. withdrawal). For these participants, we do know that they had not experienced the event up to some time <span class="math inline">\(t\)</span>, but we don’t know what happened next. All we know is that their time-to-event or <strong>survival time</strong> is greater than that time <span class="math inline">\(t\)</span>. These partial observations are known as <strong>censored</strong> times.</p>
<div class="figure"><span style="display:block;" id="fig:censor"></span>
<img src="CT4H_notes_files/figure-html/censor-1.png" alt="An example of some censored data." width="672" />
<p class="caption">
Figure 6.1: An example of some censored data.
</p>
</div>
<p>If we were to treat censored times as observations, ie. as though the event had happened at time <span class="math inline">\(t\)</span>, we would bias the results of the trial very seriously. The survival times reported would be systematically shorter than the true ones. For example, in the dataset shown in Figure <a href="time-to-event-data-and-survival-analysis.html#fig:censor">6.1</a>, we would estimate the survival probability at time 10 as 0.2, since only two of the 10 participants were still in the trial after time 10.</p>
<p>If we were to remove the censored times, and only analyse the data in which the event was observed during the linespan of the trial, we would be losing data and therefore valuable information. This approach may well also lead to bias, for example if some subset of patients died quite soon into the trial, but the remainder lived a long time (past the end of the trial). If our analysis ignores the survivors, we are likely to underestimate the general survival time. In the dataset in Figure <a href="time-to-event-data-and-survival-analysis.html#fig:censor">6.1</a> there are five participants (3,6,7,8,10) whom we are no longer able to observe at time 10, but of whom none had experienced the event by the point at which they were censored.</p>
<p>So we know that we need to somehow include these censored times in our analysis. How we do so will depend on our approach.</p>
</div>
<div id="the-survival-curve-and-the-hazard-function" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> The Survival Curve and the Hazard function<a href="time-to-event-data-and-survival-analysis.html#the-survival-curve-and-the-hazard-function" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The field of survival analysis is relatively unusual in statistics, in that it isn’t treated predominantly parametrically. For most continuous data, it is overwhelmingly common to work with the normal distribution and its friends (eg. the student’s t distribution). Similarly binary data is dominated by the binomial distribution. Inference is therefore often focussed on the parameters <span class="math inline">\(\mu,\;\sigma\)</span> or <span class="math inline">\(p\)</span>, as an adequate summary of the truth given whatever parameteric assumption has been made.</p>
<p>However, in survival analysis, it is often the case that we focus on the whole shape of the data; there isn’t an accepted dominating probability distribution. So that we can deal with time-to-event data, we need to introduce some key ways of working with such data.</p>
<p>The survival time (or time-to-event) <span class="math inline">\(t\)</span> for a particular individual can be thought of as the value of a random variable <span class="math inline">\(T\)</span>, which can take any non-negative value. We can think in terms of a probability distribution over the range of <span class="math inline">\(T\)</span>. If <span class="math inline">\(T\)</span> has a probability distribution with underlying <em>probability density function</em> <span class="math inline">\(f\left(t\right)\)</span>, then the <em>cumulative distribution function</em> is given by</p>
<p><span class="math display">\[F\left(t\right) = P\left(T&lt;t\right) = \int\limits_0^t f\left(u\right)du, \]</span>
and this gives us the probability that the survival time is less than <span class="math inline">\(t\)</span>.</p>
<div class="definition">
<p><span id="def:unlabeled-div-33" class="definition"><strong>Definition 6.1  </strong></span>The <strong>survival function</strong>, <span class="math inline">\(\operatorname{S}\left(t\right)\)</span>, is the probability that some individual (in our context a participant) survives longer than time <span class="math inline">\(t\)</span>. Therefore <span class="math inline">\(\operatorname{S}\left(t\right) = 1 - F(t)\)</span>.
Conventionally we plot <span class="math inline">\(\operatorname{S}\left(t\right)\)</span> against <span class="math inline">\(t\)</span> and this gives us a <strong>survival curve</strong>.</p>
</div>
<p>We can immediately say two things about the survival curve:</p>
<ol style="list-style-type: decimal">
<li>Since all participants must be alive (or equivalent) at the start of the trial, <span class="math inline">\(\operatorname{S}\left(0\right)=1\)</span>.</li>
<li>Since it’s impossible to survive past <span class="math inline">\(t_2&gt;t_1\)</span> but not past time <span class="math inline">\(t_1\)</span>, <span class="math inline">\(\operatorname{S}\left(t\right)\)</span> we must have <span class="math inline">\(\frac{d\operatorname{S}}{dt}\leq{0}\)</span>, ie. <span class="math inline">\(\operatorname{S}\left(t\right)\)</span> is non-increasing.</li>
</ol>
<p>Figure <a href="time-to-event-data-and-survival-analysis.html#fig:egsurvival">6.2</a> shows two survival curves, comparing different therapies. We see that the hormonal therapy reduces the survival time slightly compared to no hormonal therapy.</p>
<div class="figure"><span style="display:block;" id="fig:egsurvival"></span>
<img src="images/survival_eg.png" alt="An example of two survival curves, taken from @syriopoulou2022standardised."  />
<p class="caption">
Figure 6.2: An example of two survival curves, taken from <span class="citation">Syriopoulou et al. (<a href="#ref-syriopoulou2022standardised">2022</a>)</span>.
</p>
</div>
<p>The Survival function is fairly intuitive, but the <strong>Hazard function</strong> <span class="math inline">\(h(t)\)</span> is less so.</p>
<div class="definition">
<p><span id="def:unlabeled-div-34" class="definition"><strong>Definition 6.2  </strong></span>The <strong>Hazard function</strong> <span class="math inline">\(h(t)\)</span> is the probability that an individual who has survived up to time <span class="math inline">\(t\)</span> fails just after time <span class="math inline">\(t\)</span>; in other words, the instantaneous failure probability at time <span class="math inline">\(t\)</span>.</p>
</div>
<p>If we use <span class="math inline">\(T\)</span> to denote the random variable of survival time (or time-to-event) then <span class="math inline">\(\operatorname{S}\left(t\right)\)</span> and <span class="math inline">\(h(t)\)</span> are defined by</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{S}\left(t\right)&amp;= \operatorname{Pr}\left(T&gt;t\right)\\
h\left(t\right) &amp; = \lim\limits_{s\rightarrow{0+}}\frac{\operatorname{Pr}\left(t&lt;T&lt;t+s\mid{T&gt;t}\right)}{s}.
\end{aligned}
\]</span>
Using the definition of conditional probability, we can rewrite <span class="math inline">\(h(t)\)</span> as</p>
<p><span class="math display">\[
\begin{aligned}
h\left(t\right) &amp; = \lim\limits_{s\rightarrow{0+}}\frac{\operatorname{Pr}\left(t&lt;T&lt;t+s\mid{T&gt;t}\right)}{s} \\
&amp; = \lim\limits_{s\rightarrow{0+}}\left[\frac{1}{\operatorname{Pr}\left(T&gt;t\right)}\cdot\frac{\operatorname{Pr}\left(\left(t&lt;T&lt;t+s\right)\cap\left(T&gt;t\right)\right)}{s}\right] \\
&amp; = \lim\limits_{s\rightarrow{0+}}\left[\frac{1}{\operatorname{Pr}\left(T&gt;t\right)}\cdot\frac{\operatorname{Pr}\left(t&lt;T&lt;t+s\right)}{s}\right]\\
&amp; = \frac{f\left(t\right)}{\operatorname{S}\left(t\right)},
\end{aligned}
\]</span>
where <span class="math inline">\(f\left(\cdot\right)\)</span> is the probability density of <span class="math inline">\(T\)</span>. The hazard function can take any positive value (unlike the survival function), and for this reason <span class="math inline">\(\log\left(h\left(t\right)\right)\)</span> often used to transform it to the real line. The hazard function can also be called the ‘hazard rate’, the ‘instantaneous death rate’, the ‘intensity rate’ or the ‘force of mortality’.</p>
<p>As we hinted before, there are fundamentally two ways to deal with survival data, and in particular to estimate the survival function and hazard function: we can go about things either parametrically or non-parametrically. Unusually for statistics in generally, the non-parametric paradigm is prevalent in survival analysis. We will consider some methods from both paradigms.</p>
<div id="the-kaplan-meier-estimator" class="section level3 hasAnchor" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> The Kaplan-Meier estimator<a href="time-to-event-data-and-survival-analysis.html#the-kaplan-meier-estimator" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <strong>Kaplan-Meier estimator</strong> is a non-parametric estimate of <span class="math inline">\(\operatorname{S}\left(t\right)\)</span>. The idea behind it is to divide the interval <span class="math inline">\(\left[0,\;t\right]\)</span> into many short consecutive intervals,</p>
<p><span class="math display">\[\left[0,\,t\right] = \bigcup\limits_{k=0}^K \left[s_k,\,s_{k+1}\right],\]</span>
where <span class="math inline">\(s_k&lt;s_{k+1}\;\forall{k}\)</span>, <span class="math inline">\(s_0=0\)</span> and <span class="math inline">\(s_{K+1}=t\)</span>. We then estimate the probability of surviving past some time <span class="math inline">\(t\)</span> by multiplying together the probabilities of surviving the successive intervals up to time <span class="math inline">\(t\)</span>. No distributional assumptions are made, and the probability of surviving interval <span class="math inline">\(\left[s_k,\,s_{k+1}\right]\)</span> is estimated by <span class="math inline">\(1-Q\)</span>, where</p>
<p><span class="math display">\[Q = \frac{\text{Number who die in that interval}}{\text{Number at risk of death in that interval}}.\]</span>
More precisely, let’s say that deaths are observed at times <span class="math inline">\(t_1&lt;t_2&lt;\ldots &lt; t_n\)</span>, and that the number of deaths at time <span class="math inline">\(t_i\)</span> is <span class="math inline">\(d_i\)</span> out of a possible <span class="math inline">\(n_i\)</span>. Then for some time <span class="math inline">\(t\in\left[t_J,\,t_{J+1}\right)\)</span>, the Kaplan-Meier estimate of <span class="math inline">\(\operatorname{S}\left(t\right)\)</span> is</p>
<p><span class="math display">\[\hat{\operatorname{S}}\left(t\right) = \prod\limits_{j=0}^J \frac{\left(n_j - d_j\right)}{n_j}.\]</span></p>
<p>Notice that the number of people at risk at time <span class="math inline">\(t_{j+1}\)</span>, <span class="math inline">\(n_{j+1}\)</span>, will be the number of people at risk at time <span class="math inline">\(t_j\)</span> (which was <span class="math inline">\(n_j\)</span>), minus any who died at time <span class="math inline">\(t_j\)</span> (which we write as <span class="math inline">\(d_j\)</span>) and any who were censored in the interval <span class="math inline">\(\left[t_j,\,t_{j+1}\right)\)</span>. In this way, the Kaplan-Meier estimator incorporates information from individuals with censored survival times up to the point they were censored.</p>
<div class="example">
<p><span id="exm:surveg1" class="example"><strong>Example 6.1  </strong></span><span class="citation">Edmonson et al. (<a href="#ref-edmonson1979prognosis">1979</a>)</span> conducted a trial on patients with advanced ovarian cancer, comparing cyclophosphamide with a mixture of cyclophosphamide and adriamycin. Patients were monitored, and their time of death was recorded, or a censoring time if they were alive at their last observation.</p>
<table>
<caption><span id="tab:unnamed-chunk-48">Table 6.1: </span>Ovarian cancer data. $ exttt{FU_time}$ gives the survival or censoring time, and FU status the type: 0 for a censored observation, 1 for death.</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">FU_time</th>
<th align="right">FU_status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="right">59</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="right">115</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="right">156</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">22</td>
<td align="right">268</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">23</td>
<td align="right">329</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">24</td>
<td align="right">353</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">25</td>
<td align="right">365</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">26</td>
<td align="right">377</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">4</td>
<td align="right">421</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">5</td>
<td align="right">431</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">6</td>
<td align="right">448</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">7</td>
<td align="right">464</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">8</td>
<td align="right">475</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">9</td>
<td align="right">477</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">10</td>
<td align="right">563</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">11</td>
<td align="right">638</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">12</td>
<td align="right">744</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">13</td>
<td align="right">769</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">14</td>
<td align="right">770</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">15</td>
<td align="right">803</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">16</td>
<td align="right">855</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">17</td>
<td align="right">1040</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">18</td>
<td align="right">1106</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">19</td>
<td align="right">1129</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">20</td>
<td align="right">1206</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">21</td>
<td align="right">1227</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>We see that there are 26 individuals, and we have the time of death for 12 of them. The remaining 14 observations are censored.
We can use this data to calculate the Kaplan-Meier estimator of the survival curve, as shown in the table below. The columns are (from left to right): time <span class="math inline">\(t_j\)</span>; number at risk <span class="math inline">\(n_j\)</span>; number of events/deaths <span class="math inline">\(d_j\)</span>; number of censorings in <span class="math inline">\(\left[t_{j-1},\,t_j\right)\)</span>; estimate of survival curve.</p>
<table>
<caption><span id="tab:unnamed-chunk-49">Table 6.2: </span>Kaplan-Meier estimator calculations for ovarian cancer dataset.</caption>
<thead>
<tr class="header">
<th align="right">time</th>
<th align="right">n_risk</th>
<th align="right">n_event</th>
<th align="right">n_cens</th>
<th align="right">survival</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">59</td>
<td align="right">26</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.9615385</td>
</tr>
<tr class="even">
<td align="right">115</td>
<td align="right">25</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.9230769</td>
</tr>
<tr class="odd">
<td align="right">156</td>
<td align="right">24</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.8846154</td>
</tr>
<tr class="even">
<td align="right">268</td>
<td align="right">23</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.8461538</td>
</tr>
<tr class="odd">
<td align="right">329</td>
<td align="right">22</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.8076923</td>
</tr>
<tr class="even">
<td align="right">353</td>
<td align="right">21</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.7692308</td>
</tr>
<tr class="odd">
<td align="right">365</td>
<td align="right">20</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.7307692</td>
</tr>
<tr class="even">
<td align="right">431</td>
<td align="right">17</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">0.6877828</td>
</tr>
<tr class="odd">
<td align="right">464</td>
<td align="right">15</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0.6419306</td>
</tr>
<tr class="even">
<td align="right">475</td>
<td align="right">14</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.5960784</td>
</tr>
<tr class="odd">
<td align="right">563</td>
<td align="right">12</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0.5464052</td>
</tr>
<tr class="even">
<td align="right">638</td>
<td align="right">11</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0.4967320</td>
</tr>
</tbody>
</table>
<p>To demonstrate the effect of including (and correctly treating) the censored data, we can do the same thing, but this time (1) leaving out all censored data and (2) treating all censored data times as deaths. Figure <a href="time-to-event-data-and-survival-analysis.html#fig:kmov">6.3</a> shows the resulting survival curve estimates.</p>
<div class="figure"><span style="display:block;" id="fig:kmov"></span>
<img src="CT4H_notes_files/figure-html/kmov-1.png" alt="Kaplan-Meier estimate of survival curve for ovarian cancer data." width="672" />
<p class="caption">
Figure 6.3: Kaplan-Meier estimate of survival curve for ovarian cancer data.
</p>
</div>
<p>Leaving out the censored observations entirely is the most problematic approach, since it causes a serious underestimate, and in this case behaves as though there are no survivors after <span class="math inline">\(t=638\)</span>, which is untrue. Treating the censored data as deaths also leads to an underestimate of the survival probability, and notably creates a rather spurious curve past the last real death observation.</p>
<p>The ‘correct’ Kaplan-Meier estimate may seem a bit disatisfying, since it stops at <span class="math inline">\(t=638\)</span> with a probabiilty of <span class="math inline">\(0.497\)</span>. However, this is really (in a non-parametric setting) all we can say with the data available; 10 of the participants were definitely still alive at <span class="math inline">\(t=638\)</span>, and some of the other censored participants may also have been.</p>
</div>
</div>
<div id="a-parametric-approach" class="section level3 hasAnchor" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> A parametric approach<a href="time-to-event-data-and-survival-analysis.html#a-parametric-approach" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In a parametric approach, we’ll assume that the survival time <span class="math inline">\(T\)</span> follows some probability distribution, up to unknown parameters which we will estimate from the data. The simplest distribution for time-to-event data is the <em>exponential distribution</em>, which has density</p>
<p><span class="math display">\[f\left(t\right) = \lambda e^{-\lambda t} \text{ for }t&gt;0,\]</span></p>
<p>survival function</p>
<p><span class="math display">\[\operatorname{S}\left(t\right) = 1- \int\limits_{0}^t{\lambda e^{-\lambda t}} = e^{-\lambda t}, \]</span>
and mean survival time <span class="math inline">\(\frac{1}{\lambda}\)</span>.</p>
<p>Having only one parameter, the exponential distribution is not very flexible, and often doesn’t fit data at all well. A related, but more suitable distribution is the <strong>Weibull distribution</strong>.</p>
<div class="definition">
<p><span id="def:unlabeled-div-35" class="definition"><strong>Definition 6.3  </strong></span>The probability density function of a <strong>Weibull</strong> random variable is</p>
<p><span class="math display">\[
f\left(x\mid \lambda,\,k\right) =
\begin{cases}
\lambda\gamma t^{\gamma-1}\exp\left[{-\lambda t^{\gamma}}\right] &amp; \text{for }t\geq{0}\\
0 &amp; \text{otherwise}.
\end{cases}
\]</span></p>
<p>Here, <span class="math inline">\(\gamma\)</span> is the <em>shape</em> parameter, and <span class="math inline">\(\lambda\)</span> is the scale parameter. If <span class="math inline">\(\gamma=1\)</span> then this reduces to an exponential distribution.</p>
</div>
<p>For the Weibull distribution, we have</p>
<p><span class="math display">\[\operatorname{S}\left(t\right) = \exp\left(-\lambda t^{\gamma}\right). \]</span></p>
<div id="assessing-the-suitability-of-a-parametric-model" class="section level4 unnumbered hasAnchor">
<h4>Assessing the suitability of a parametric model<a href="time-to-event-data-and-survival-analysis.html#assessing-the-suitability-of-a-parametric-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>[Modelling survival data book, p155]</p>
<p>Presented with some data, we can estimate the paremeters of a Weibull or exponential distribution using maximum likelihood. This is (mostly) nothing new, so we will skirt over most details, focussing only on those that are particular to time-to-event data. Since the interesting points don’t really pertain to the actual distribution, we will work through the method with the exponential distribution, because it is simpler.</p>
</div>
<div id="maximum-likelihood-for-time-to-event-data" class="section level4 unnumbered hasAnchor">
<h4>Maximum likelihood for time-to-event data<a href="time-to-event-data-and-survival-analysis.html#maximum-likelihood-for-time-to-event-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Suppose our dataset has <span class="math inline">\(n\)</span> times <span class="math inline">\(t_1,\,t_2,\,\ldots,t_n\)</span>. Of these, <span class="math inline">\(m\)</span> are fully observed and <span class="math inline">\(n-m\)</span> are censored. We can create a set of indicators <span class="math inline">\(\delta_1,\ldots,\delta_n\)</span>, where <span class="math inline">\(\delta_i=1\)</span> if observation <span class="math inline">\(i\)</span> is fully observed and <span class="math inline">\(\delta_i=0\)</span> if it is censored.</p>
<p>Usually, the likelihood function is computed by multiplying the density function evaluated at each data point, <span class="math inline">\(f\left(t_i\right)\)</span>. However, this won’t work for survival data, because for our censored times (those for which <span class="math inline">\(\delta_i=0\)</span>) we only know that the time-to-event is greater than <span class="math inline">\(t_i\)</span>. For these observations, it is the survival time (remember that this is <span class="math inline">\(p\left(T&gt;t\right)\)</span>) that contributes what we need to the likelihood function.</p>
<p>Therefore (for either probability distribution) we have</p>
<p><span class="math display">\[L = \prod\limits_{i=1}^n f\left(t_i\right)^\delta_i S\left(t_i\right)^{1-\delta_i}.\]</span>
If we have <span class="math inline">\(T\sim Exp\left(\lambda\right)\)</span> then the log-likelihood is</p>
<p><span class="math display">\[
\begin{aligned}
\ell &amp;= \sum\limits_{i=1}^n \delta_i\left(\log\lambda - \lambda t_i\right) - \sum\limits_{i=1}^n\left(1-\delta_i\right)\lambda t_i \\
&amp; =  m\log\lambda - \lambda\sum\limits_{i=1}^n t_i.
\end{aligned}
\]</span></p>
<p>From this we can find the maximum likelihood estimator (MLE)</p>
<p><span class="math display">\[\hat{\lambda} = \frac{m}{\sum\limits_{i=1}^n t_i}.\]</span>
The variance of the MLE is</p>
<p><span class="math display" id="eq:lambdavar">\[\begin{equation}
\operatorname{var}\left(\hat\lambda\right) = \frac{\lambda^2}{m},
\tag{6.1}
\end{equation}\]</span></p>
<p>which we can approximate by</p>
<p><span class="math display">\[\operatorname{var}\left(\hat\lambda\right) \approx \frac{m}{\left(\sum\limits_{i=1}^n t_i\right)^2}.\]</span></p>
<p>Notice that the denominator in Equation <a href="time-to-event-data-and-survival-analysis.html#eq:lambdavar">(6.1)</a> is <span class="math inline">\(m\)</span>, the number of complete observations (rather than <span class="math inline">\(n\)</span> the total number including censored observations). This shows that there is a limit to the amount we can learn if a lot of the data is censored.</p>
</div>
</div>
<div id="sample-size-calculations-for-time-to-event-data" class="section level3 hasAnchor" number="6.2.3">
<h3><span class="header-section-number">6.2.3</span> Sample size calculations for time-to-event data<a href="time-to-event-data-and-survival-analysis.html#sample-size-calculations-for-time-to-event-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are implications here for sample size calculations, which must take into account the duration of a trial; it is important that trials monitor patients until a sufficient proportion have experienced the event (whatever it is). Sample size calculations for time-to-event data therefore have two components:</p>
<ol style="list-style-type: decimal">
<li>The power of the trial can first be expressed in terms of <span class="math inline">\(m\)</span>, the number of complete observations.</li>
<li>A separate calculation is needed to estimate the number of participants needing to be recruited, and length of trial, to be sufficiently likely to achieve that value of <span class="math inline">\(m\)</span>.</li>
</ol>
<p>Both of these calculations rely on a number of modelling assumptions, and on previous scientific/clinical data (if available).</p>
<div class="example">
<p><span id="exm:unlabeled-div-36" class="example"><strong>Example 6.2  </strong></span>Returning to the dataset from Example <a href="time-to-event-data-and-survival-analysis.html#exm:surveg1">6.1</a>, we can fit an exponential distribution to the data simply by estimating the MLE</p>
<p><span class="math display">\[
\begin{aligned}
\hat{\lambda} &amp;= \frac{m}{\sum\limits_{i=1}^n t_i}\\
&amp; =\frac{12}{15588}\\
&amp; = 0.00077
\end{aligned}
\]</span></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="time-to-event-data-and-survival-analysis.html#cb39-1" tabindex="-1"></a>m_eg <span class="ot">=</span> <span class="fu">sum</span>(ovarian<span class="sc">$</span>fustat)</span>
<span id="cb39-2"><a href="time-to-event-data-and-survival-analysis.html#cb39-2" tabindex="-1"></a>sum_time <span class="ot">=</span> <span class="fu">sum</span>(ovarian<span class="sc">$</span>futime)</span>
<span id="cb39-3"><a href="time-to-event-data-and-survival-analysis.html#cb39-3" tabindex="-1"></a>lambda_hat <span class="ot">=</span> m_eg <span class="sc">/</span> sum_time</span>
<span id="cb39-4"><a href="time-to-event-data-and-survival-analysis.html#cb39-4" tabindex="-1"></a><span class="fu">round</span>(lambda_hat,<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 0.00077</code></pre>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="comparing-survival-curves" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Comparing survival curves<a href="time-to-event-data-and-survival-analysis.html#comparing-survival-curves" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Really what we would like to be able to do is to compare two survival curves (showing, for example, the results from different treatments), so that we can say whether one is significantly different from the other. In most cases, this boils down to constructing a hypothesis test along the lines of</p>
<p><span class="math display">\[
\begin{aligned}
H_0:&amp;\text{ the treatments are the same}\\
H_1:&amp;\text{ the treatments are different.}
\end{aligned}
\]</span></p>
<p>From here, we should be able to construct a confidence interval that gives some indication of the extent of the difference, and our confidence/uncertainty.</p>
<p>In a parametric approach, everything relates to parameter values; we will come to this later. However, for a non-parametric approach, things are not so simple (or at least not so neat and tidy) since we can’t summarise the data using a small collection of parameters. We’ll see too that there are other advantages to the parametric approach, such as the ability to adjust for baseline covariates.</p>
<div id="non-parametric-the-log-rank-test" class="section level3 hasAnchor" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Non-parametric: the log-rank test<a href="time-to-event-data-and-survival-analysis.html#non-parametric-the-log-rank-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The log-rank test is performed by creating a series of 2x2 tables, and combining the information.</p>
<p>[LOOK AT NON-PARAMETRIC WAYS OF DEALING WITH BINARY - MANTEL-HAENSZEL IN 7.4.4]</p>

<div id="refs" class="references csl-bib-body hanging-indent">
<div class="csl-entry">
al, Geoffrey Marshall et. 1948. <span>“STREPTOMYCIN TREATMENT OF PULMONARY TUBERCULOSIS a MEDICAL RESEARCH COUNCIL INVESTIGATION.”</span> <em>British Medical Journal</em>. <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2091872/pdf/brmedj03701-0007.pdf">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2091872/pdf/brmedj03701-0007.pdf</a>.
</div>
<div class="csl-entry">
Altman, Douglas G. 1990. <em>Practical Statistics for Medical Research</em>. CRC press.
</div>
<div class="csl-entry">
———. 1998. <span>“Confidence Intervals for the Number Needed to Treat.”</span> <em>Bmj</em> 317 (7168): 1309–12.
</div>
<div class="csl-entry">
Altman, Douglas G, and J Martin Bland. 1999. <span>“Treatment Allocation in Controlled Trials: Why Randomise?”</span> <em>Bmj</em> 318 (7192): 1209–9.
</div>
<div class="csl-entry">
Collett, David. 2003. <em>Modelling Survival Data in Medical Research</em>. 2nd ed. Texts in Statistical Science. Chapman &amp; Hall.
</div>
<div class="csl-entry">
Cottingham, Marci D, and Jill A Fisher. 2022. <span>“Gendered Logics of Biomedical Research: Women in US Phase i Clinical Trials.”</span> <em>Social Problems</em> 69 (2): 492–509.
</div>
<div class="csl-entry">
Edmonson, John H, Thomas R Fleming, David G Decker, George D Malkasian, Edward O Jorgensen, John A Jefferies, Maurice J Webb, and Larry K Kvols. 1979. <span>“Prognosis in Advanced Ovarian Carcinoma Versus Minimal Residual.”</span> <em>Cancer Treatment Reports</em> 63 (2): 241–47.
</div>
<div class="csl-entry">
Fentiman, Ian S, Robert D Rubens, and John L Hayward. 1983. <span>“Control of Pleural Effusions in Patients with Breast Cancer a Randomized Trial.”</span> <em>Cancer</em> 52 (4): 737–39.
</div>
<div class="csl-entry">
Freedman, LS, and Susan J White. 1976. <span>“On the Use of Pocock and Simon’s Method for Balancing Treatment Numbers over Prognostic Factors in the Controlled Clinical Trial.”</span> <em>Biometrics</em>, 691–94.
</div>
<div class="csl-entry">
Hayes, Richard J, and Lawrence H Moulton. 2017. <em>Cluster Randomised Trials</em>. CRC press.
</div>
<div class="csl-entry">
Health, National Institute of. 2023. <span>“History of Women’s Participation in Clinical Research.”</span> Office of Research on Women’s Health. https://orwh. od. nih. gov/toolkit …. <a href="https://orwh.od.nih.gov/toolkit/recruitment/history">https://orwh.od.nih.gov/toolkit/recruitment/history</a>.
</div>
<div class="csl-entry">
Hjalmas, Hanson, and Kruse Hellstrom. 1998. <span>“Long‐term Treatment with Desmopressin in Children with Primary Monosymptomatic Nocturnal Enuresis: An Open Multicentre Study.”</span> <em>British Journal of Urology</em>.
</div>
<div class="csl-entry">
Hommel, EHEBMJ, Hans-Henrik Parving, Elisabeth Mathiesen, Berit Edsberg, M Damkjaer Nielsen, and Jørn Giese. 1986. <span>“Effect of Captopril on Kidney Function in Insulin-Dependent Diabetic Patients with Nephropathy.”</span> <em>Br Med J (Clin Res Ed)</em> 293 (6545): 467–70.
</div>
<div class="csl-entry">
Hulley, Stephen B, Steven R. Cummings, Warren S. Browner, Deborah G. Grady, and Thomas B. Newman. 2013. <em>Designing Clinical Research, Fourth Edition</em>. Lippincott Williams &amp; Wilkins.
</div>
<div class="csl-entry">
Kallis, P, JA Tooze, S Talbot, D Cowans, DH Bevan, and T Treasure. 1994. <span>“Pre-Operative Aspirin Decreases Platelet Aggregation and Increases Post-Operative Blood Loss–a Prospective, Randomised, Placebo Controlled, Double-Blind Clinical Trial in 100 Patients with Chronic Stable Angina.”</span> <em>European Journal of Cardio-Thoracic Surgery: Official Journal of the European Association for Cardio-Thoracic Surgery</em> 8 (8): 404–9.
</div>
<div class="csl-entry">
Kar, Sumit, Ajay Krishnan, Preetha K, and Atul Mohankar. 2012. <span>“A Review of Antihistamines Used During Pregnancy.”</span> <em>Journal of Pharmacology and Pharmacotherapeutics</em> 3 (2): 105–8.
</div>
<div class="csl-entry">
Kassambara, Alboukadel. 2019. <em>Datarium: Data Bank for Statistical Analysis and Visualization</em>. <a href="https://CRAN.R-project.org/package=datarium">https://CRAN.R-project.org/package=datarium</a>.
</div>
<div class="csl-entry">
Matthews, John NS. 2006. <em>Introduction to Randomized Controlled Clinical Trials</em>. CRC Press.
</div>
<div class="csl-entry">
Newcombe, Robert G. 1998. <span>“Interval Estimation for the Difference Between Independent Proportions: Comparison of Eleven Methods.”</span> <em>Statistics in Medicine</em> 17 (8): 873–90.
</div>
<div class="csl-entry">
Pocock, Stuart J, and Richard Simon. 1975. <span>“Sequential Treatment Assignment with Balancing for Prognostic Factors in the Controlled Clinical Trial.”</span> <em>Biometrics</em>, 103–15.
</div>
<div class="csl-entry">
Ruetzler, Kurt, Michael Fleck, Sabine Nabecker, Kristina Pinter, Gordian Landskron, Andrea Lassnigg, Jing You, and Daniel I Sessler. 2013. <span>“A Randomized, Double-Blind Comparison of Licorice Versus Sugar-Water Gargle for Prevention of Postoperative Sore Throat and Postextubation Coughing.”</span> <em>Anesthesia &amp; Analgesia</em> 117 (3): 614–21.
</div>
<div class="csl-entry">
Smith, AC, JF Dowsett, RCG Russell, ARW Hatfield, and PB Cotton. 1994. <span>“Randomised Trial of Endoscopic Steriting Versus Surgical Bypass in Malignant Low Bileduct Obstruction.”</span> <em>The Lancet</em> 344 (8938): 1655–60.
</div>
<div class="csl-entry">
Syriopoulou, Elisavet, Tove Wästerlid, Paul C Lambert, and Therese M-L Andersson. 2022. <span>“Standardised Survival Probabilities: A Useful and Informative Tool for Reporting Regression Models for Survival Data.”</span> <em>British Journal of Cancer</em> 127 (10): 1808–15.
</div>
<div class="csl-entry">
Taves, Donald R. 1974. <span>“Minimization: A New Method of Assigning Patients to Treatment and Control Groups.”</span> <em>Clinical Pharmacology &amp; Therapeutics</em> 15 (5): 443–53.
</div>
<div class="csl-entry">
Treasure, Tom, and Kenneth D MacRae. 1998. <span>“Minimisation: The Platinum Standard for Trials?: Randomisation Doesn’t Guarantee Similarity of Groups; Minimisation Does.”</span> <em>Bmj</em>. British Medical Journal Publishing Group.
</div>
<div class="csl-entry">
Villar, Jesús, Carlos Ferrando, Domingo Martı́nez, Alfonso Ambrós, Tomás Muñoz, Juan A Soler, Gerardo Aguilar, et al. 2020. <span>“Dexamethasone Treatment for the Acute Respiratory Distress Syndrome: A Multicentre, Randomised Controlled Trial.”</span> <em>The Lancet Respiratory Medicine</em> 8 (3): 267–76.
</div>
<div class="csl-entry">
Vitale, Cristiana, Massimo Fini, Ilaria Spoletini, Mitja Lainscak, Petar Seferovic, and Giuseppe MC Rosano. 2017. <span>“Under-Representation of Elderly and Women in Clinical Trials.”</span> <em>International Journal of Cardiology</em> 232: 216–21.
</div>
<div class="csl-entry">
Zhong, Baoliang. 2009. <span>“How to Calculate Sample Size in Randomized Controlled Trial?”</span> <em>Journal of Thoracic Disease</em> 1 (1): 51.
</div>
</div>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-collett_surv" class="csl-entry">
Collett, David. 2003. <em>Modelling Survival Data in Medical Research</em>. 2nd ed. Texts in Statistical Science. Chapman &amp; Hall.
</div>
<div id="ref-edmonson1979prognosis" class="csl-entry">
Edmonson, John H, Thomas R Fleming, David G Decker, George D Malkasian, Edward O Jorgensen, John A Jefferies, Maurice J Webb, and Larry K Kvols. 1979. <span>“Prognosis in Advanced Ovarian Carcinoma Versus Minimal Residual.”</span> <em>Cancer Treatment Reports</em> 63 (2): 241–47.
</div>
<div id="ref-syriopoulou2022standardised" class="csl-entry">
Syriopoulou, Elisavet, Tove Wästerlid, Paul C Lambert, and Therese M-L Andersson. 2022. <span>“Standardised Survival Probabilities: A Useful and Informative Tool for Reporting Regression Models for Survival Data.”</span> <em>British Journal of Cancer</em> 127 (10): 1808–15.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="binary-outcome-variable.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["CT4H_notes.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"bookdown": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
